Repository PIVX-Project/PIVX, pull requests merged in 2018-09, with the labels that each got.

#708 [Build] Remove stale m4 file
  pkg.m4
Labels: Build System, review

#706 [Build] Remove throw keywords in leveldb function signatures
  src/leveldbwrapper.cpp
  src/leveldbwrapper.h
Labels: Build System, Upstream, review

#711 [RPC] Don't allow backupwallet to overwrite the wallet-in-use
  src/walletdb.cpp
Labels: RPC, review

#692 [Zerocoin] Remove explicit copy assignement operator from Accumulator
  src/libzerocoin/Accumulator.cpp
  src/libzerocoin/Accumulator.h
Labels: review, zPiv

#715 [Refactor] Remove GetCoinAge
  src/main.cpp
  src/main.h
  src/primitives/transaction.h
Labels: Cleanup, Refactoring, review

#719 [RPC] Fix verifychain
  src/rpc/blockchain.cpp
Labels: RPC, review

#720 [RPC] Sanitize walletpassphrase timeout argument
  src/rpcwallet.cpp
Labels: RPC, review
