Repository PIVX-Project/PIVX, pull requests merged in 2018-05, with the labels that each got.

#583 [Docs] Update release notes for v3.1.0
  doc/release-notes.md
Labels: Docs and Output, review

#585 [Doc] Change aarch assert sign output folder
  doc/release-process.md
Labels: review

#587 [Bug] Fix Windows icon files
  share/pixmaps/bitcoin.ico
  share/pixmaps/nsis-header.bmp
  share/pixmaps/nsis-wizard.bmp
  src/qt/res/icons/bitcoin.ico
  src/qt/res/icons/bitcoin_testnet.ico
Labels: Windows, review

#590 [Budget] Fix wrong budget amount
  src/masternode-budget.cpp
Labels: review

#591 Add unit test for budget value.
  src/Makefile.test.include
  src/test/budget_tests.cpp
Labels: review

#592 Update protocol to 70914.
  src/version.h
Labels: review

#595 [Tests] Fix chain ordering in budget tests
  src/test/budget_tests.cpp
Labels: Tests, review

#594 [Trivial] Add gpdionisio gpg key for gitian
  contrib/gitian-keys/gpdionisio-key.gpg
Labels: review

#596 [Build] Bump master to 3.1.99
  configure.ac
  contrib/gitian-descriptors/gitian-aarch64.yml
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win.yml
Labels: Build System, review

#597 [Wallet] Write new transactions to wtxOrdered properly
  src/wallet.cpp
Labels: RPC, Wallet, review

#600 [GUI] Only enable/disable PrivacyDialog zPIV elements if needed.
  src/qt/privacydialog.cpp
Labels: GUI, review, zPiv

#599 Fix bad masternode IPv6 signature
  src/masternode.cpp
  src/netbase.cpp
  src/netbase.h
  src/obfuscation.cpp
Labels: Bug, Masternode, review

#598 [GUI] Fix wrongly displayed balance on Overview tab
  src/qt/overviewpage.cpp
Labels: review

#605 [Build] Remove unnecessary BOOST dependency
  src/wallet.cpp
Labels: review

#606 [Trivial] clean logs from CObfuScationSigner::VerifyMessage
  src/obfuscation.cpp
Labels: review

#608 [Budget] Make sorting of finalized budgets deterministic
  src/masternode-budget.cpp
Labels: review

#610 [Main] Check whether tx is in chain in ContextualCheckZerocoinMint().
  src/main.cpp
Labels: Block Storage, Validation, review, zPiv

#619 [Net] Revert #599 and #606
  src/masternode.cpp
  src/netbase.cpp
  src/netbase.h
  src/obfuscation.cpp
Labels: review

#609 [MoveOnly] Remove zPIV code from main.cpp
  src/Makefile.am
  src/accumulators.cpp
  src/blocksignature.cpp
  src/init.cpp
  src/kernel.cpp
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/qt/transactionrecord.cpp
  src/rpcrawtransaction.cpp
  src/rpcwallet.cpp
  src/test/zerocoin_implementation_tests.cpp
  src/wallet.cpp
  src/zpivchain.cpp
  src/zpivchain.h
  src/zpivwallet.cpp
Labels: Refactoring, review

#611 [Output] Properly log reason(s) for increasing a peer's DoS score.
  src/masternode-budget.cpp
  src/masternode-payments.cpp
  src/masternodeman.cpp
Labels: Docs and Output, review

#624 [Core] Missing seesaw value for block 325000
  src/main.cpp
Labels: review

#622 [Build] Make sure Boost headers are included for libzerocoin
  src/Makefile.am
Labels: Build System
