Repository PIVX-Project/PIVX, pull requests merged in 2018-08, with the labels that each got.

#656 [Wallet] Fix double locked coin when wallet and MN are on same machine
  src/wallet.cpp
Labels: GUI, Wallet

#675 [Qt] SwiftX - intuitiveness
  src/qt/forms/sendcoinsdialog.ui
  src/qt/sendcoinsdialog.cpp
Labels: Cleanup, GUI, Needs Translating, Usability, review

#680 [Qt] Privacy dialog: hide/show denominations
  src/qt/forms/privacydialog.ui
  src/qt/privacydialog.cpp
  src/qt/privacydialog.h
Labels: GUI, Usability, review

#655 [Qt] Fix PIV balances on overview page
  src/qt/overviewpage.cpp
Labels: GUI, review

#669 [Utils] Fix syntax error in gitian-build.sh
  contrib/gitian-build.sh
Labels: Scripts and Tools

#697 [Trivial] Remove Redundant Declarations
  src/libzerocoin/ParamGeneration.h
  src/main.h
Labels: Cleanup, review

#699 [Refactor] Use references instead of copies in for loops
  src/accumulators.cpp
  src/denomination_functions.cpp
  src/main.cpp
  src/miner.cpp
  src/primitives/transaction.cpp
  src/qt/clientmodel.cpp
  src/qt/transactionrecord.cpp
  src/rpcwallet.cpp
  src/test/zerocoin_implementation_tests.cpp
  src/wallet.cpp
  src/zpivchain.cpp
Labels: Cleanup, Refactoring, review

#703 [Docs] Add missing automake dependency
  doc/build-unix.md
Labels: review

#693 [UI] Add address to the payment request history
  src/qt/receivecoinsdialog.cpp
  src/qt/receivecoinsdialog.h
  src/qt/recentrequeststablemodel.cpp
  src/qt/recentrequeststablemodel.h
Labels: GUI, Usability, review

#700 [Wallet] Avoid autocombine getting stuck
  src/wallet.cpp
Labels: Wallet, review
