Repository PIVX-Project/PIVX, pull requests merged in 2018-02, with the labels that each got.

#532 [Depends] Update depends package versions.
  depends/Makefile
  depends/README.md
  depends/config.guess
  depends/config.site.in
  depends/config.sub
  depends/packages/boost.mk
  depends/packages/dbus.mk
  depends/packages/expat.mk
  depends/packages/libevent.mk
  depends/packages/native_ccache.mk
  depends/packages/native_ds_store.mk
  depends/packages/native_mac_alias.mk
  depends/packages/qrencode.mk
  depends/packages/zeromq.mk
  depends/patches/native_mac_alias/python3.patch
  depends/patches/qt/mac-qmake.conf
  depends/patches/zeromq/0001-fix-build-with-older-mingw64.patch
  depends/patches/zeromq/9114d3957725acd34aa8b8d011585812f3369411.patch
  depends/patches/zeromq/9e6745c12e0b100cd38acecc16ce7db02905e27c.patch
Labels: Build System, Upstream, review

#538 [Qt] Fix warning dialog popup for the Blockchain Explorer
  src/qt/blockexplorer.cpp
Labels: GUI, review

#541 [Build] Fix typo in Qt test makefile
  src/Makefile.qttest.include
Labels: Build System, review

#540 [Trival] blondfrogs gpg for gitian
  contrib/gitian-keys/blondfrogs-key.gpg
Labels: review

#542 [Network] Remove vfReachable and modify IsReachable to only use vfLimited.
  src/init.cpp
  src/net.cpp
  src/net.h
Labels: Backport, Network, review

#526 Refactor ConnectBlock() to segregate state tracking items
  src/accumulators.cpp
  src/accumulators.h
  src/main.cpp
  src/main.h
  src/miner.cpp
Labels: Block Storage, Refactoring, Validation, review, zPiv

#535 [core] Minor refacturing + unused variable removed
  src/miner.cpp
  src/util.cpp
  src/util.h
Labels: Minting, Refactoring, Wallet, review

#543 [RPC] Segfault pivx-cli getinfo while loading block index
  src/rpcmisc.cpp
Labels: Bug, RPC, review

#539 [RPC] Allow watchonly coins to be shown for listunspent
  src/rpcclient.cpp
  src/rpcrawtransaction.cpp
  src/wallet.cpp
  src/wallet.h
Labels: review

#544 [Trivial] Add debug info for CWallet::ReconsiderZerocoins().
  src/wallet.cpp
Labels: review, zPiv
