Repository PIVX-Project/PIVX, pull requests merged in 2018-03, with the labels that each got.

#552 [Trivial] Fix errant LogPrint in UpdateZPIVSupply
  src/main.cpp
Labels: Docs and Output, review

#551 [Consensus] Require standard transactions for testnet
  src/chainparams.cpp
Labels: Validation, review

#521 [GUI] Make "For anonymization and staking only" checked by default
  src/qt/addresstablemodel.cpp
  src/qt/askpassphrasedialog.cpp
  src/qt/askpassphrasedialog.h
  src/qt/bip38tooldialog.cpp
  src/qt/bitcoingui.cpp
  src/qt/masternodelist.cpp
  src/qt/multisigdialog.cpp
  src/qt/privacydialog.cpp
  src/qt/sendcoinsdialog.cpp
  src/qt/signverifymessagedialog.cpp
  src/qt/walletframe.cpp
  src/qt/walletframe.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/qt/walletview.cpp
  src/qt/walletview.h
Labels: GUI, Usability, review

#557 [Build] Revert #402 "Change git info in genbuild.sh"
  share/genbuild.sh
Labels: Build System, review

#554 [Docs] Added release notes for autocombine and proxy GUI.
  doc/release-notes.md
Labels: review

#558 [Core] Remove Gitan-OSX warning for High Sierra builds
  src/qt/pivx.cpp
Labels: Cleanup, review

#559 [Bug] Segfault with -enableswifttx=0 / -enableswifttx=false
  src/init.cpp
Labels: Bug, review

#565 [Wallet] Increase valid range for automint percentage
  src/init.cpp
  src/qt/forms/optionsdialog.ui
  src/qt/optionsmodel.cpp
Labels: Wallet, review, zPiv

#566 [Qt] Add automint status bar icon
  src/Makefile.qt.include
  src/qt/bitcoingui.cpp
  src/qt/bitcoingui.h
  src/qt/pivx.qrc
  src/qt/res/css/default.css
  src/qt/res/icons/automint_active.png
  src/qt/res/icons/automint_inactive.png
Labels: GUI, Usability, review

#568 [Qt] Connect automint icon to the UI automint setting change
  src/qt/bitcoingui.cpp
Labels: GUI, review

#571 [Qt] Update privacy tab info about zeromint on config change
  src/qt/privacydialog.cpp
  src/qt/privacydialog.h
Labels: GUI, review

#570 [Wallet] Add a check on zPIV spend to avoid a segfault
  src/wallet.cpp
Labels: Wallet, review

#572 [Qt] Refresh zPIV balance after resetting mints or spends
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/wallet.cpp
  src/wallet.h
Labels: GUI, review

#569 [Docs] OSX Build - Instructions on how to make the Homebrew OpenSSL headers visible
  doc/build-osx.md
Labels: Docs and Output, review
