Repository PIVX-Project/PIVX, pull requests merged in 2018-11, with the labels that each got.

#769 [Main] Unify shutdown proceedure in init rather than per-app
  src/init.cpp
  src/init.h
  src/pivxd.cpp
  src/qt/pivx.cpp
Labels: Refactoring, review

#747 [GUI] Hide orphans - contextMenu action
  src/qt/optionsdialog.cpp
  src/qt/optionsdialog.h
  src/qt/overviewpage.cpp
  src/qt/transactionview.cpp
  src/qt/transactionview.h
Labels: GUI, Needs Release Notes, review

#755 [Wallet] Fix zPIV spend when too much mints are selected
  src/wallet.cpp
Labels: Wallet, review, zPiv
