Repository PIVX-Project/PIVX, pull requests merged in 2018-12, with the labels that each got.

#776 [Qt] Add a security warning to the debug console's default output.
  src/qt/rpcconsole.cpp
Labels: GUI, Needs Release Notes, Needs Translating, review

#770 Do not record zerocoin tx's in ConnectBlock() if it is fJustCheck
  src/main.cpp
Labels: Validation, review

#771 [Main] Clean up sync.cpp/h with upstream declarations
  src/sync.cpp
  src/sync.h
Labels: Cleanup, Upstream, review

#762 [Random] WIN32 Seed Cleanup: Move nLastPerfmon behind win32 ifdef.
  src/random.cpp
Labels: Backport, Windows, review

#781 [Qt] Don't show staking/automint status icons without a wallet
  src/qt/bitcoingui.cpp
Labels: GUI, review

#774 [Budget] Make checks for MN-autovoting deterministic
  src/masternode-budget.cpp
  src/masternode-budget.h
Labels: Budget/Proposal System, review
