Repository PIVX-Project/PIVX, pull requests merged in 2019-02, with the labels that each got.

#804 [Depends] Update zmq to 4.3.1
  depends/packages/zeromq.mk
Labels: Build System

#758 [Depends] Update libsecp256k1 to latest master
  src/secp256k1/include/secp256k1_ecdh.h
  src/secp256k1/src/bench_ecdh.c
  src/secp256k1/src/java/org_bitcoin_NativeSecp256k1.c
  src/secp256k1/src/modules/ecdh/main_impl.h
  src/secp256k1/src/modules/ecdh/tests_impl.h
  src/secp256k1/src/tests.c
Labels: review

#802 [Refactor] Remove begin/end_ptr functions
  src/netbase.cpp
  src/random.cpp
  src/script/interpreter.cpp
  src/serialize.h
  src/test/base58_tests.cpp
  src/util.cpp
Labels: Backport, Refactoring, review

#757 [Doc] Update doc/build-windows.md
  doc/build-windows.md
Labels: Docs and Output, review

#816 [Doc] Update build-unix.md
  doc/build-unix.md
Labels: Docs and Output, review
