Repository PIVX-Project/PIVX, pull requests merged in 2019-04, with the labels that each got.

#813 [Refactoring] [Move Only] Move wallet files into their own folder
  src/Makefile.am
  src/Makefile.test.include
  src/activemasternode.h
  src/crypter.cpp
  src/init.cpp
  src/miner.cpp
  src/net.cpp
  src/qt/addresstablemodel.cpp
  src/qt/bip38tooldialog.cpp
  src/qt/coincontroldialog.cpp
  src/qt/masternodelist.cpp
  src/qt/multisigdialog.cpp
  src/qt/optionsdialog.cpp
  src/qt/optionsmodel.cpp
  src/qt/paymentserver.cpp
  src/qt/pivx.cpp
  src/qt/rpcconsole.cpp
  src/qt/sendcoinsdialog.cpp
  src/qt/signverifymessagedialog.cpp
  src/qt/splashscreen.cpp
  src/qt/transactiondesc.cpp
  src/qt/transactionrecord.cpp
  src/qt/transactiontablemodel.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/qt/walletmodeltransaction.cpp
  src/rpc/blockchain.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/rawtransaction.cpp
  src/stakeinput.cpp
  src/test/accounting_tests.cpp
  src/test/multisig_tests.cpp
  src/test/rpc_wallet_tests.cpp
  src/test/script_P2SH_tests.cpp
  src/test/test_pivx.cpp
  src/test/zerocoin_coinspend_tests.cpp
  src/test/zerocoin_denomination_tests.cpp
  src/test/zerocoin_implementation_tests.cpp
  src/test/zerocoin_transactions_tests.cpp
  src/wallet/db.cpp
  src/wallet/db.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_ismine.cpp
  src/wallet/wallet_ismine.h
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
  src/zpiv/zpivtracker.cpp
  src/zpiv/zpivwallet.cpp
Labels: Backport, Refactoring, Wallet, review

#858 [Build] [macOS] Fix macOS dmg issue (10.12+)
  contrib/macdeploy/custom_dsstore.py
Labels: Build System, Upstream, macOS, review

#862 [Build] Bump master to 3.2.99 (non-release)
  configure.ac
Labels: Build System, review

#808 [Scripts] Add optimize pngs python script
  contrib/devtools/optimize-pngs.py
Labels: Scripts and Tools

#865 [Main] Don't return an invalid state when shutting down the wallet
  src/main.cpp
Labels: Block Storage, Validation, review

#852 [QT] Fix a display bug about zPIV mints
  src/qt/zpivcontroldialog.cpp
Labels: GUI, review

#861 [Net] Add new checkpoints for mainnet/testnet
  src/chainparams.cpp
Labels: Network, P2P, review

#860 [Qt] Prevent double deletion of progress dialog
  src/main.cpp
Labels: GUI, review

#856 [Refactor] Move per-chain budget cycle blocks to chainparams
  src/chainparams.cpp
  src/chainparams.h
  src/masternode-budget.cpp
  src/masternode-budget.h
  src/masternode-payments.cpp
  src/qt/governancepage.cpp
  src/rpc/budget.cpp
Labels: Budget/Proposal System, NoFunctionalChanges, Refactoring, review

#845 [Cleanup] Fix redundant redeclaration of boost's to_internal
  src/util.cpp
Labels: Cleanup, Refactoring

#844 [Refactor] Replace deprecated auto_ptr with unique_ptr
  src/rpc/mining.cpp
Labels: Refactoring

#866 [Build] Update debian contrib files
  Makefile.am
  contrib/debian/README.md
  contrib/debian/changelog
  contrib/debian/control
  contrib/debian/manpages/pivx-qt.1
  contrib/debian/manpages/pivx.conf.5
  contrib/debian/manpages/pivxd.1
  contrib/debian/pivx-qt.desktop
  contrib/debian/pivx-qt.install
  contrib/debian/pivx-qt.manpages
  contrib/debian/pivxd.bash-completion
  contrib/debian/pivxd.install
  contrib/debian/pivxd.manpages
  contrib/debian/pivxd.postinst
  contrib/debian/pivxd.postrm
  contrib/debian/pivxd.service
  contrib/debian/rules
  contrib/debian/watch
  share/pixmaps/pivx-bc.ico
  share/pixmaps/pivx.ico
  share/pixmaps/pivx128.png
  share/pixmaps/pivx128.xpm
  share/pixmaps/pivx16.png
  share/pixmaps/pivx16.xpm
  share/pixmaps/pivx256.png
  share/pixmaps/pivx256.xpm
  share/pixmaps/pivx32.png
  share/pixmaps/pivx32.xpm
  share/pixmaps/pivx64.png
  share/pixmaps/pivx64.xpm
  share/setup.nsi.in
  share/ui.rc
Labels: Build System, Scripts and Tools, review

#868 [Performances] Decrease the number of wasted CPU cycles
  src/kernel.cpp
Labels: Usability, enhancement, review

#869 [Doc] Add historical release notes
  doc/release-notes.md
  doc/release-notes/release-notes-3.1.0.2.md
  doc/release-notes/release-notes-3.1.1.md
  doc/release-notes/release-notes-3.2.0.md
Labels: Docs and Output, NoFunctionalChanges, review

#872 add furszy gpg key for gitian
  contrib/gitian-keys/furszy-key.gpg
Labels: review

#744 [Refactor] Refactor bignum header file into several files
  configure.ac
  src/Makefile.am
  src/libzerocoin/bignum.cpp
  src/libzerocoin/bignum.h
  src/libzerocoin/bignum_gmp.cpp
  src/libzerocoin/bignum_openssl.cpp
Labels: NoFunctionalChanges, Refactoring, review

#877 [RPC] Remove deprecated masternode/budget RPC commands
  src/rpc/budget.cpp
  src/rpc/client.cpp
  src/rpc/masternode.cpp
  src/rpc/server.cpp
  src/rpc/server.h
Labels: Cleanup, RPC, review
