Repository PIVX-Project/PIVX, pull requests merged in 2019-06, with the labels that each got.

#899 [zPIV] Disable zPIV staking
  src/wallet/wallet.cpp
Labels: Block Generation, Wallet, review, zPiv

#909 [Consensus] Mainnet public spend enforcement height set.
  src/chainparams.cpp
Labels: zPiv

#903 [Log] Handle errors during log message formatting
  src/util.h
Labels: Backport, Upstream

#912 [Cleanup] compiler warnings in coinSpend object.
  src/libzerocoin/CoinSpend.cpp
  src/libzerocoin/CoinSpend.h
  src/zpiv/zpivmodule.h
Labels: Build System

#901 [RPC] Fix typos and oversights in listunspent
  src/rpc/rawtransaction.cpp
Labels: RPC

#910 [Build] Clean all coverage files during make clean
  src/Makefile.am
Labels: Build System

#919 [zPIV] Debug missing jump line.
  src/zpiv/accumulators.cpp
Labels: zPiv

#916 [Staking] Don't assert if we were beaten to the block
  src/main.cpp
Labels: Block Generation

#922 [Build] Fix app name casing in mac deploy related files
  contrib/macdeploy/detached-sig-create.sh
  contrib/macdeploy/fancy.plist
Labels: Build System

#914 [Gitian] Bump gitian build versions
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx-signer.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win-signer.yml
  contrib/gitian-descriptors/gitian-win.yml
Labels: Build System

#913 [Depends] Update from upstream
  .python-version
  .travis.yml
  configure.ac
  depends/Makefile
  depends/README.md
  depends/builders/darwin.mk
  depends/config.site.in
  depends/funcs.mk
  depends/packages.md
  depends/packages/bdb.mk
  depends/packages/expat.mk
  depends/packages/fontconfig.mk
  depends/packages/freetype.mk
  depends/packages/libX11.mk
  depends/packages/libXau.mk
  depends/packages/libXext.mk
  depends/packages/libxcb.mk
  depends/packages/miniupnpc.mk
  depends/packages/native_biplist.mk
  depends/packages/native_cctools.mk
  depends/packages/native_cdrkit.mk
  depends/packages/native_ds_store.mk
  depends/packages/native_mac_alias.mk
  depends/packages/native_protobuf.mk
  depends/packages/packages.mk
  depends/packages/qt.mk
  depends/packages/xcb_proto.mk
  depends/packages/xextproto.mk
  depends/packages/xproto.mk
  depends/packages/xtrans.mk
  depends/packages/zlib.mk
  src/Makefile.am
Labels: Build System

#904 [zPIV] Free memory from ToString()
  src/libzerocoin/bignum_gmp.cpp
Labels: review

#908 [NET] Non-running dns servers removed from chainParams.
  src/chainparams.cpp
Labels: Cleanup, Network

#930 [Net] Add a couple new testnet checkpoints
  src/chainparams.cpp
Labels: Network

#926 [Doc] 3.3.0 Notable Changes
  doc/release-notes.md
Labels: Docs and Output

#929 [Net] Update hard-coded seeds
  src/chainparamsseeds.h
Labels: Network

#934 [Build] Bump master to 3.3.99 (pre-3.4)
  configure.ac
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win.yml
Labels: Build System

#932 [Node] Do all block index writes in a batch
  src/chain.h
  src/main.cpp
  src/txdb.cpp
  src/txdb.h
Labels: Backport, Block Storage, UTXO DBs and Indexes, review
