Repository PIVX-Project/PIVX, pull requests merged in 2019-08, with the labels that each got.

#948 [Docs] Clean and re-structure the gitian-keys directory
  contrib/gitian-keys/README.md
  contrib/gitian-keys/blondfrogs-key.gpg
  contrib/gitian-keys/furszy-key.gpg
  contrib/gitian-keys/fuzzbawls-key.gpg
  contrib/gitian-keys/gpdionisio-key.gpg
  contrib/gitian-keys/jonspock-key.gpg
  contrib/gitian-keys/keys.txt
  contrib/gitian-keys/mrs-x-key.gpg
  contrib/gitian-keys/presstab-key.gpg
  contrib/gitian-keys/rejectedpromise-key.gpg
  contrib/gitian-keys/s3v3nh4cks-key.gpg
  contrib/gitian-keys/warrows-key.gpg
Labels: Docs and Output, Upstream

#971 [Wallet][zPIV] zc public spend parse crash in wallet startup.
  src/qt/transactionrecord.cpp
  src/zpiv/zpivmodule.cpp
  src/zpiv/zpivmodule.h
Labels: Wallet

#980 [Wallet] Remove Bitcoin Core 0.8 block hardlinking
  src/init.cpp
Labels: Cleanup, Upstream

#950 [RPC] require valid URL scheme on budget commands
  src/rpc/budget.cpp
  src/utilstrencodings.cpp
  src/utilstrencodings.h
Labels: Needs Release Notes, RPC

#982 [Miner] Don't create new keys when generating PoS blocks
  src/miner.cpp
  src/miner.h
  src/rpc/mining.cpp
Labels: Block Generation, Wallet

#976 [Refactor] Fix stake age checks for regtest
  src/chainparams.cpp
  src/chainparams.h
  src/kernel.cpp
  src/main.cpp
  src/main.h
  src/wallet/wallet.cpp
Labels: Bug, Cleanup, Tests

#987 [Net] Protocol update enforcement for 70917 and new spork keys
  src/chainparams.cpp
  src/main.cpp
  src/spork.cpp
  src/spork.h
  src/version.h
  test/functional/test_framework/messages.py
Labels: Network, Protocol-Update

#988 [Maintenance] Bump master to 3.4.99 (pre-4.0)
  configure.ac
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win.yml
  doc/release-notes.md
  doc/release-notes/release-notes-3.4.0.md
Labels: Build System, Docs and Output
