Repository PIVX-Project/PIVX, pull requests merged in 2019-09, with the labels that each got.

#990 [Build] Fix wrong argument when verifying MacOS signatures
  contrib/gitian-build.py
Labels: Build System

#997 [Trivial][UI] MN screen, texts typo.
  src/qt/pivx/masternodeswidget.cpp
Labels: GUI

#998 [Qt] Guard MN tab from possible missing TXs in masternode.conf
  src/qt/pivx/mnmodel.cpp
Labels: GUI

#1014 [GUI] Refresh coin control upon reopening
  src/qt/coincontroldialog.h
  src/qt/pivx/send.cpp
Labels: GUI

#1001 [Consensus] Remove Old message format in CMasternodeBroadcast
  src/masternode.cpp
  src/masternode.h
Labels: Cleanup, Consensus, Masternode

#1016 [GUI] Tx detail dialog, show seconds in toString date.
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/pivx/forms/sendconfirmdialog.ui
  src/qt/pivx/sendconfirmdialog.cpp
Labels: GUI

#1015 [Qt] Update source strings
  src/qt/locale/pivx_en.ts
  src/qt/pivxstrings.cpp
Labels: GUI

#999 [UI] Send screen, total amounts refresh after custom options cleaned.
  src/coincontrol.h
  src/qt/pivx/send.cpp
  src/qt/pivx/send.h
Labels: GUI

#1018 [GUI] Update amounts when entry is removed from SendMultiRow
  src/qt/pivx/send.cpp
Labels: GUI

#1017 [GUI][Trivial] Remove hardcoded address.
  src/qt/pivx/forms/addnewaddressdialog.ui
Labels: Cleanup, GUI

#1013 [Build] Clean up GUI dependency checking
  build-aux/m4/bitcoin_qt.m4
  configure.ac
Labels: Build System

#1025 [Startup] Stop loading the wallet if shutdown was requested.
  src/init.cpp
Labels: Startup

#1027 [Cleanup] Get rid of compiler warnings
  src/init.cpp
  src/qt/pivx/qtutils.cpp
  src/qt/pivx/qtutils.h
  src/utilstrencodings.cpp
  src/wallet/wallet.cpp
Labels: Cleanup, NoFunctionalChanges
