Repository PIVX-Project/PIVX, pull requests merged in 2019-10, with the labels that each got.

#1031 [Wallet] fix CreateZerocoinSpendTransaction with empty addressesTo
  src/qt/pivx/privacywidget.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: Bug, Wallet, zPiv

#1009 [QT] Dashboard chart, left and right day range movement control buttons.
  src/qt/pivx/dashboardwidget.cpp
  src/qt/pivx/dashboardwidget.h
  src/qt/pivx/forms/dashboardwidget.ui
  src/qt/pivx/res/css/style_dark.css
  src/qt/pivx/res/css/style_light.css
Labels: GUI

#1040 [Bug] Fix GetDepthInMainChain returning 0 when tx is not in mempool
  src/qt/transactiondesc.cpp
  src/qt/transactionrecord.cpp
  src/qt/walletmodel.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Bug, Wallet

#1042 [TravisCI] Run CMake tests earlier
  .travis.yml
Labels: Build System

#1045 [travis] Update .travis.yml
  .travis.yml
Labels: Build System

#1052 [CMake] Fix macOS Boost detection
  CMakeLists.txt
Labels: Build System

#1051 [Doxygen] Generate Todo list
  doc/Doxyfile.in
Labels: Docs and Output

#1048 [Qt] Make CoinControlTreeWidget focusable
  src/qt/forms/coincontroldialog.ui
Labels: GUI

#1055 [Wallet] Create label for addresses generated via masternode wizard
  src/qt/pivx/masternodewizarddialog.cpp
Labels: GUI, Wallet

#1054 [UI] Guard a call to GetDepthInMainChain
  src/qt/pivx/sendconfirmdialog.cpp
Labels: Bug, GUI, Windows

#1056 [Wallet][Refactor] Updating ancient getbalanceXXX methods to a lambda call.
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Refactoring, Wallet

#1058 [Wallet] Transaction IsEquivalentTo method backported + code cleanup.
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Backport, Wallet

#1063 [Node] Remove a call to IsSuperMajority
  src/main.cpp
Labels: Validation

#1070 [Bug] Fix contextCheckBlock for the first block that it's a v1 block.
  src/main.cpp
Labels: Bug

#1067 [Node] Replace IsSuperMajority with height checks
  src/chainparams.cpp
  src/chainparams.h
  src/main.cpp
Labels: Validation
