Repository PIVX-Project/PIVX, pull requests merged in 2019-11, with the labels that each got.

#1072 [Qt] Update welcomecontentwidget.ui
  src/qt/pivx/forms/welcomecontentwidget.ui
Labels: GUI

#1074 [UI] TransactionFilter, do not invalidate filter if range is already set.
  src/qt/transactionfilterproxy.cpp
Labels: GUI

#1071 [UI] Settings, options buttons hover css.
  src/qt/pivx/res/css/style_dark.css
  src/qt/pivx/res/css/style_light.css
Labels: GUI

#1083 [Qt] Hide option for 3rd party transaction URLs
  src/qt/pivx/settings/settingsdisplayoptionswidget.cpp
Labels: GUI

#1084 [Qt] Show display unit option as text
  src/qt/pivx/settings/forms/settingsdisplayoptionswidget.ui
Labels: GUI

#1099 [GUI][Model][Performance] Dashboard, remove call to isCoinStakeMine method.
  src/qt/pivx/dashboardwidget.cpp
  src/qt/pivx/dashboardwidget.h
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/qt/transactiontablemodel.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: GUI

#1104 [Trivial][GUI] Fix typos in welcome widget
  src/qt/pivx/forms/welcomecontentwidget.ui
Labels: GUI, Trivial

#1105 [GUI] Fix bug in change wallet passphrase
  src/qt/askpassphrasedialog.cpp
  src/qt/pivx/settings/settingsbackupwallet.cpp
Labels: Bug, GUI

#1069 [Wallet] Enable miner with mnsync incomplete
  src/masternode-sync.cpp
  src/masternode-sync.h
  src/miner.cpp
Labels: Block Generation, Masternode

#1111 [Trivial] Fix help text for delegatorremove
  src/wallet/rpcwallet.cpp
Labels: RPC, Trivial

#1112 [Qt] Refresh coin control when re-opening from CS widget
  src/qt/pivx/coldstakingwidget.cpp
Labels: GUI

#1066 [Cleanup][Refactor]Main.cpp code cleanup.
  src/main.cpp
  src/main.h
Labels: Cleanup, Refactoring

#1118 [Sporks] Guard chainActive.Tip() and chainActive.Height() methods call.
  src/spork.cpp
Labels: Cleanup

#1116 [Wallet] Do not use p2cs outputs in the autocombine flow.
  src/wallet/wallet.cpp
Labels: Wallet

#1109 [Trivial] [GUI] Customize Fee Dialog text change
  src/qt/pivx/sendcustomfeedialog.cpp
Labels: GUI, Trivial

#1064 [Wallet][RPC] Diagnose unsuitable outputs in lockunspent()
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Backport, RPC, Wallet

#1065 [Wallet] Unlock spent outputs
  src/wallet/wallet.cpp
Labels: Backport, Wallet

#1057 [UI] Fix AA_EnableHighDpiScaling warning
  src/qt/pivx.cpp
Labels: GUI

#1073 [Model][Backport] Remove mapWallet not needed call + stop treating coinbase differently
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
Labels: GUI, Upstream

#1075 [Model][UI] Receive dialog, create address if addressbook is empty
  src/qt/addresstablemodel.cpp
  src/qt/addresstablemodel.h
  src/qt/pivx/receivewidget.cpp
  src/qt/pivx/send.cpp
  src/qt/pivx/topbar.cpp
Labels: GUI

#1120 [GUI][BUG] Bad top padding on the dashboard nav icon in dark theme fix.
  src/qt/pivx/res/css/style_dark.css
Labels: Bug, GUI

#1122 [GUI][Backport] Explicitly disable "Dark Mode" appearance on macOS
  share/qt/Info.plist.in
Labels: Backport, GUI, macOS

#1130 [UI] Copy correct data from mninfo dialog
  src/qt/pivx/mninfodialog.cpp
Labels: Bug, GUI

#1126 [BUG] Fix send transaction detail destinations
  src/qt/pivx/sendconfirmdialog.cpp
Labels: Bug, GUI

#1123 [GUI] Prevent worker constant creation and invalid removal
  src/qt/pivx/loadingdialog.cpp
  src/qt/pivx/loadingdialog.h
  src/qt/pivx/pwidget.cpp
  src/qt/pivx/pwidget.h
Labels: Bug, GUI

#1132 [Bug][GUI] Tx list row amount color changing invalidly.
  src/qt/pivx/txrow.cpp
Labels: Bug, GUI

#1133 [Bug][GUI] Topbar sync progressbar not expanding fixed.
  src/qt/pivx/topbar.cpp
  src/qt/pivx/topbar.h
Labels: Bug, GUI

#1134 [Trivial] Remove a duplicate variable definition
  src/chainparams.cpp
Labels: Trivial

#1085 [Qt] Fixup topbar balance calculation
  src/qt/pivx/topbar.cpp
Labels: GUI

#1129 [Consensus] Define TestNet changeover block for PIVX v4.0 RC
  src/chainparams.cpp
Labels: Consensus

#1137 [Net] Protocol update enforcement for 70918
  src/main.cpp
  src/version.h
  test/functional/test_framework/messages.py
Labels: Consensus, Network, Protocol-Update

#1139 [Qt] Fix segfault when running GUI client with --help or -?
  src/qt/utilitydialog.cpp
Labels: Bug, GUI

#1125 [GUI] Inform if open pivx.conf and/or backups folder fail.
  src/qt/pivx/settings/forms/settingsconsolewidget.ui
  src/qt/pivx/settings/forms/settingsinformationwidget.ui
  src/qt/pivx/settings/settingsconsolewidget.cpp
  src/qt/pivx/settings/settingsinformationwidget.cpp
  src/qt/pivx/settings/settingswidget.cpp
Labels: Bug, GUI

#1121 [GUI] Cold staking, alert user if the owner address is not from the wallet
  src/qt/pivx/coldstakingwidget.cpp
Labels: GUI

#1142 [Bug] Fix segfault on GUI initialization for cold staker wallet
  src/qt/addresstablemodel.cpp
Labels: Bug, GUI

#1141 [GUI][Model] isTestNetwork regtest correction.
  src/qt/pivx/masternodewizarddialog.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: Bug, GUI, Tests

#1131 [Bug] URI read from file coded properly..
  src/qt/openuridialog.cpp
  src/qt/openuridialog.h
Labels: Bug, GUI
