Repository PIVX-Project/PIVX, pull requests merged in 2019-05, with the labels that each got.

#879 [Refactor] Rename ui_interface.h file
  src/Makefile.am
  src/alert.cpp
  src/guiinterface.h
  src/httprpc.cpp
  src/httpserver.cpp
  src/init.cpp
  src/main.cpp
  src/masternodeconfig.cpp
  src/net.cpp
  src/noui.cpp
  src/obfuscation.cpp
  src/pivx-tx.cpp
  src/pivxd.cpp
  src/qt/bitcoingui.cpp
  src/qt/blockexplorer.cpp
  src/qt/clientmodel.cpp
  src/qt/paymentserver.cpp
  src/qt/pivx.cpp
  src/qt/sendcoinsdialog.cpp
  src/qt/splashscreen.cpp
  src/qt/transactiondesc.cpp
  src/qt/transactionview.cpp
  src/qt/walletmodel.cpp
  src/qt/walletview.cpp
  src/qt/walletview.h
  src/rpc/client.cpp
  src/rpc/net.cpp
  src/rpc/server.cpp
  src/test/test_pivx.cpp
  src/timedata.cpp
  src/wallet/wallet.h
  src/zpivchain.cpp
Labels: NoFunctionalChanges, Refactoring, review

#880 [NET] Valid forked blocks rejected fix.
  src/main.cpp
Labels: High Priority, review

#884 [Net] Add additional checkpoints
  src/chainparams.cpp
Labels: Network, review

#887 [Net] Fix incorrect last checkpoint timestamp
  src/chainparams.cpp
Labels: Network, review

#890 [Refactor] Remove unused setStakeSeen variable
  src/main.cpp
  src/main.h
  src/txdb.cpp
Labels: Cleanup, Refactoring, review

#896 [UI] Simplify Qt margins.
  src/qt/forms/governancepage.ui
  src/qt/forms/masternodelist.ui
  src/qt/forms/multisenddialog.ui
  src/qt/forms/overviewpage.ui
  src/qt/forms/privacydialog.ui
  src/qt/forms/receivecoinsdialog.ui
  src/qt/forms/sendcoinsdialog.ui
Labels: Refactoring, review

#888 [Zerocoin] remove CTransaction::IsZerocoinSpend/IsZerocoinMint
  src/blocksignature.cpp
  src/bloom.cpp
  src/coins.cpp
  src/coins.h
  src/kernel.cpp
  src/main.cpp
  src/masternode-payments.cpp
  src/miner.cpp
  src/primitives/block.cpp
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/qt/privacydialog.cpp
  src/qt/transactionrecord.cpp
  src/rpc/blockchain.cpp
  src/rpc/rawtransaction.cpp
  src/script/script.cpp
  src/script/script.h
  src/script/standard.cpp
  src/test/zerocoin_implementation_tests.cpp
  src/txmempool.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/zpiv/zpivwallet.cpp
  src/zpivchain.cpp
Labels: review, zPiv

#898 [Qt] Fixup duplicate label names
  src/qt/forms/receivecoinsdialog.ui
  src/qt/forms/zpivcontroldialog.ui
Labels: Cleanup, GUI, NoFunctionalChanges, review
