Repository PIVX-Project/PIVX, pull requests merged in 2019-12, with the labels that each got.

#1157 [Travis] Increase functional tests reserved time
  .travis.yml
Labels: Scripts and Tools

#1159 [GUI][Trivial] Rewording of Error message when wallet is unlocked for staking only
  src/qt/pivx/guitransactionsutils.cpp
Labels: GUI, Trivial

#1156 [GUI] Decreasing the tooltip padding for #1076 windows issue.
  src/qt/coincontroldialog.cpp
  src/qt/pivx/res/css/style_dark.css
  src/qt/pivx/res/css/style_light.css
  src/qt/transactiontablemodel.cpp
Labels: GUI

#1158 [BUG] Masternodes wizard, IPv6 addresses storage in .conf file.
  src/qt/pivx/masternodewizarddialog.cpp
Labels: Bug, GUI

#1161 [GUI][Trivial] Custom change address, editable box focus.
  src/qt/pivx/sendchangeaddressdialog.cpp
  src/qt/pivx/sendchangeaddressdialog.h
Labels: GUI, Usability

#1160 [GUI][Model] Do not re request passphrase when the wallet is unlocked.
  src/qt/pivx/topbar.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: GUI, Usability

#1162 [Qt] Periodic make translate
  src/qt/locale/pivx_en.ts
  src/qt/pivxstrings.cpp
Labels: GUI

#1167 [Trivial] Remove time offset warning when it gets back within range
  src/timedata.cpp
Labels: Trivial

#1166 [Qt] properly copy IPv6 externalip MN info
  src/qt/pivx/masternodeswidget.cpp
Labels: Bug, GUI

#1180 [Build] Add random-zebra gitian GPG public key fingerprint
  contrib/gitian-keys/keys.txt
Labels: Build System

#1179 [Qt] Fix for dead link to wrong PIVX website
  src/qt/pivx/settings/forms/settingsfaqwidget.ui
Labels: GUI, Trivial

#1173 [GUI][Trivial] Remove every pushButton focus decoration property.
  src/qt/pivx/forms/addnewaddressdialog.ui
  src/qt/pivx/forms/addnewcontactdialog.ui
  src/qt/pivx/forms/addresseswidget.ui
  src/qt/pivx/forms/coincontrolpivwidget.ui
  src/qt/pivx/forms/coldstakingwidget.ui
  src/qt/pivx/forms/csrow.ui
  src/qt/pivx/forms/dashboardwidget.ui
  src/qt/pivx/forms/defaultdialog.ui
  src/qt/pivx/forms/denomgenerationdialog.ui
  src/qt/pivx/forms/expandablebutton.ui
  src/qt/pivx/forms/masternodeswidget.ui
  src/qt/pivx/forms/masternodewizarddialog.ui
  src/qt/pivx/forms/mninfodialog.ui
  src/qt/pivx/forms/mnrow.ui
  src/qt/pivx/forms/navmenuwidget.ui
  src/qt/pivx/forms/optionbutton.ui
  src/qt/pivx/forms/privacywidget.ui
  src/qt/pivx/forms/receivedialog.ui
  src/qt/pivx/forms/receivewidget.ui
  src/qt/pivx/forms/requestdialog.ui
  src/qt/pivx/forms/send.ui
  src/qt/pivx/forms/sendchangeaddressdialog.ui
  src/qt/pivx/forms/sendconfirmdialog.ui
  src/qt/pivx/forms/sendcustomfeedialog.ui
  src/qt/pivx/forms/sendmultirow.ui
  src/qt/pivx/forms/snackbar.ui
  src/qt/pivx/forms/topbar.ui
  src/qt/pivx/forms/txrow.ui
  src/qt/pivx/forms/walletpassworddialog.ui
  src/qt/pivx/forms/welcomecontentwidget.ui
  src/qt/pivx/settings/forms/settingsbackupwallet.ui
  src/qt/pivx/settings/forms/settingsbittoolwidget.ui
  src/qt/pivx/settings/forms/settingsconsolewidget.ui
  src/qt/pivx/settings/forms/settingsdisplayoptionswidget.ui
  src/qt/pivx/settings/forms/settingsfaqwidget.ui
  src/qt/pivx/settings/forms/settingsinformationwidget.ui
  src/qt/pivx/settings/forms/settingsmainoptionswidget.ui
  src/qt/pivx/settings/forms/settingsmultisenddialog.ui
  src/qt/pivx/settings/forms/settingsmultisendwidget.ui
  src/qt/pivx/settings/forms/settingssignmessagewidgets.ui
  src/qt/pivx/settings/forms/settingswalletoptionswidget.ui
  src/qt/pivx/settings/forms/settingswalletrepairwidget.ui
  src/qt/pivx/settings/forms/settingswidget.ui
Labels: GUI

#1178 [GUI][Bug] Cold staking screen, fixing show receive addresses list.
  src/qt/pivx/coldstakingwidget.cpp
Labels: Bug, GUI

#1186 [GUI][Trivial] move caps lock warning in askpassphrase dialog
  src/qt/forms/askpassphrasedialog.ui
Labels: Bug, GUI, Trivial

#1187 [GUI][Trivial] Fix tx detail dialog expanding policy
  src/qt/pivx/dashboardwidget.cpp
  src/qt/pivx/forms/sendconfirmdialog.ui
Labels: GUI, Trivial

#1185 [GUI][Trivial] Make amount optional in staking address gen dialog
  src/qt/pivx/requestdialog.cpp
Labels: GUI, Trivial

#1183 [GUI][Trivial] Allow immediate typing in dialogs / tools widget
  src/qt/askpassphrasedialog.cpp
  src/qt/pivx/addnewcontactdialog.cpp
  src/qt/pivx/addnewcontactdialog.h
  src/qt/pivx/masternodewizarddialog.cpp
  src/qt/pivx/masternodewizarddialog.h
  src/qt/pivx/requestdialog.cpp
  src/qt/pivx/requestdialog.h
  src/qt/pivx/settings/settingsconsolewidget.cpp
  src/qt/pivx/settings/settingsconsolewidget.h
  src/qt/pivx/settings/settingssignmessagewidgets.cpp
  src/qt/pivx/settings/settingssignmessagewidgets.h
Labels: Feature Request, GUI, Trivial, Usability

#1177 [Network] Add SPORK 17 & 18 to the fMissingSporks flag + code reorg.
  src/main.cpp
Labels: Network, P2P

#1163 [GUI] Validate wallet password on enter key press
  src/qt/askpassphrasedialog.cpp
Labels: GUI, Usability

#1190 [GUI] Feature/Bug CoinControl Update on Open
  src/qt/coincontroldialog.cpp
  src/qt/coincontroldialog.h
  src/qt/pivx/coldstakingwidget.cpp
  src/qt/pivx/privacywidget.cpp
  src/qt/pivx/send.cpp
Labels: Bug, GUI

#1124 [GUI] Use QRegexValidator instead of the QDoubleValidator.
  src/qt/bitcoinunits.cpp
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/pivx/forms/sendmultirow.ui
  src/qt/pivx/requestdialog.cpp
  src/qt/pivx/sendmultirow.cpp
  src/qt/test/uritests.cpp
Labels: Bug, GUI

#1192 [GUI][Bug] Accept P2CS locked coins in coincontrol
  src/qt/walletmodel.cpp
Labels: Bug, GUI

#1191 [Consensus] Define MainNet changeover block for PIVX v4.0
  src/chainparams.cpp
Labels: Consensus, Needs Release Notes, Protocol-Update

#1193 [GUI][Wallet] Allow spending of P2CS without coincontrol selection
  src/qt/walletmodel.cpp
Labels: Bug, GUI, Wallet

#1195 [Qt] Update translations from transifex
  src/qt/locale/pivx_bg.ts
  src/qt/locale/pivx_ca.ts
  src/qt/locale/pivx_cs.ts
  src/qt/locale/pivx_da.ts
  src/qt/locale/pivx_de.ts
  src/qt/locale/pivx_en.ts
  src/qt/locale/pivx_en_GB.ts
  src/qt/locale/pivx_eo.ts
  src/qt/locale/pivx_es.ts
  src/qt/locale/pivx_es_ES.ts
  src/qt/locale/pivx_fi.ts
  src/qt/locale/pivx_fr_FR.ts
  src/qt/locale/pivx_hi_IN.ts
  src/qt/locale/pivx_hr.ts
  src/qt/locale/pivx_hr_HR.ts
  src/qt/locale/pivx_it.ts
  src/qt/locale/pivx_ja.ts
  src/qt/locale/pivx_ko_KR.ts
  src/qt/locale/pivx_lt_LT.ts
  src/qt/locale/pivx_nl.ts
  src/qt/locale/pivx_pl.ts
  src/qt/locale/pivx_pt.ts
  src/qt/locale/pivx_pt_BR.ts
  src/qt/locale/pivx_ro_RO.ts
  src/qt/locale/pivx_ru.ts
  src/qt/locale/pivx_sk.ts
  src/qt/locale/pivx_sv.ts
  src/qt/locale/pivx_tr.ts
  src/qt/locale/pivx_uk.ts
  src/qt/locale/pivx_vi.ts
  src/qt/locale/pivx_zh_CN.ts
  src/qt/locale/pivx_zh_TW.ts
Labels: GUI

#1188 [GUI] Workaround to the OSX border-image pink stripes.
  src/Makefile.qt.include
  src/qt/CMakeLists.txt
  src/qt/pivx/forms/topbar.ui
  src/qt/pivx/forms/welcomecontentwidget.ui
  src/qt/pivx/pfborderimage.h
  src/qt/pivx/res/css/style_dark.css
  src/qt/pivx/res/css/style_light.css
  src/qt/pivx/settings/forms/settingsfaqwidget.ui
  src/qt/pivx/settings/settingsdisplayoptionswidget.cpp
  src/qt/pivx/settings/settingsfaqwidget.cpp
  src/qt/pivx/settings/settingswidget.cpp
  src/qt/pivx/topbar.cpp
  src/qt/pivx/welcomecontentwidget.cpp
Labels: Bug, Build System, GUI

#1181 [Docs] 4.0.0 release notes
  doc/release-notes.md
Labels: Documentation

#1194 [GUI] ColdStaking widget: fix "total staking" amount
  src/qt/addresstablemodel.cpp
  src/qt/addresstablemodel.h
  src/qt/pivx/coldstakingmodel.cpp
  src/qt/pivx/coldstakingmodel.h
  src/qt/pivx/coldstakingwidget.cpp
  src/qt/pivx/coldstakingwidget.h
Labels: Bug, GUI

#1200 [Build] Bump master to 4.0.99
  configure.ac
Labels: Build System, Trivial

#1204 [Build] Bump snapcraft nightlies to 4.0.99
  build-aux/snap/snapcraft.yaml
Labels: Build System, Trivial

#1205 [Cleanup] Remove unnecessary QtCreator files
  pivxd-new-gui.config
  pivxd-new-gui.creator
  pivxd-new-gui.creator.user
  pivxd-new-gui.files
  pivxd-new-gui.includes
Labels: Cleanup, Trivial

#1199 Clean up 4.0 compiler warnings
  src/init.cpp
  src/qt/pivx/welcomecontentwidget.cpp
  src/qt/transactionrecord.cpp
  src/wallet/wallet.cpp
Labels: Cleanup

#1222 [Wallet] Remove un-necessary CheckTransaction call when loading wallet.
  src/wallet/walletdb.cpp
Labels: Startup, Wallet

#1203 [Backport][Performance] Cache + guard best block hash.
  src/init.cpp
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/rpc/mining.cpp
Labels: Backport

#1223 [GUI][Bug] Show locked balance in the available total amount.
  src/qt/pivx/topbar.cpp
Labels: Bug, GUI

#1206 [BUG][RPC] fix signature check (against old format) in mnbudgetrawvote
  src/rpc/budget.cpp
Labels: Bug, Masternode, RPC
