Repository PIVX-Project/PIVX, pull requests merged in 2019-07, with the labels that each got.

#933 [Qt] Add blockhash + datadir to information tab
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/qt/forms/rpcconsole.ui
  src/qt/rpcconsole.cpp
Labels: GUI

#947 [Scripts] Sync github-merge.py with upstream
  contrib/devtools/github-merge.py
Labels: Scripts and Tools, Upstream

#957 [Build] Add info about '--with-unsupported-ssl'
  configure.ac
Labels: Build System

#939 [Wallet] Remove (explicitely) unused tx comparator
  src/primitives/transaction.h
Labels: Bug, GUI, Refactoring

#941 [Refactor] Move ThreadStakeMinter out of net.cpp
  src/init.cpp
  src/miner.cpp
  src/miner.h
  src/net.cpp
Labels: Block Generation, Minting, Refactoring

#961 [Trivial][Tests] Do not fail test when warnings are written to stderr
  test/functional/test_runner.py
Labels: Tests
