Repository PIVX-Project/PIVX, pull requests merged in 2019-03, with the labels that each got.

#821 [RPC] Fixup signrawtransaction on regtest
  src/rpc/rawtransaction.cpp
Labels: RPC, review

#826 [Qt] Fix a windows only crash when r-clicking a proposal
  src/qt/proposalframe.cpp
Labels: Bug, GUI, Windows, review

#840 [QT] cleanup, remove old trading dialog form
  src/qt/forms/tradingdialog.ui
  src/qt/walletframe.h
Labels: review

#815 [Doc] Update release notes with forthcoming 3.2.0 changes
  doc/release-notes.md
Labels: Docs and Output, review

#843 [Net] Increment Protocol Version
  src/version.h
Labels: Network, NoFunctionalChanges, review
