Repository PIVX-Project/PIVX, pull requests merged in 2019-01, with the labels that each got.

#783 [Depends] Update QT to 5.9.7
  depends/packages/qt.mk
Labels: Build System

#791 [Qt] Fix Missing Explorer Icon
  src/qt/pivx.qrc
Labels: GUI

#788 Update license year 2019
  COPYING
Labels: Docs and Output

#794 [UI] Open related options tab when clicking automint icon
  src/qt/bitcoingui.cpp
  src/qt/optionsdialog.cpp
  src/qt/optionsdialog.h
Labels: GUI, review

#800 [Net] nLastTry is only used for addrman entries
  src/addrman.cpp
  src/addrman.h
  src/net.cpp
  src/protocol.cpp
  src/protocol.h
Labels: Backport, Refactoring, review

#798 [Net] Improve addrman Select() performance when buckets are nearly empty
  src/addrman.cpp
Labels: Backport, Network, review
