Repository PIVX-Project/PIVX, pull requests merged in 2020-07, with the labels that each got.

#1689 [Cleanup] Small main.cpp cleanup
  src/main.cpp
  src/main.h
Labels: Cleanup, Refactoring

#1698 [Wallet] Masternodes start performance boost
  src/wallet/wallet.cpp
Labels: Masternode, Refactoring, Wallet

#1704 [Net] Pre-requirements for network encapsulation
  src/Makefile.am
  src/Makefile.test.include
  src/activemasternode.cpp
  src/bloom.cpp
  src/bloom.h
  src/main.cpp
  src/main.h
  src/mruset.h
  src/net.cpp
  src/net.h
  src/rpc/net.cpp
  src/test/DoS_tests.cpp
  src/test/bloom_tests.cpp
  src/test/main_tests.cpp
  src/test/mruset_tests.cpp
  src/test/net_tests.cpp
  test/functional/mining_pos_coldStaking.py
  test/functional/wallet_zerocoin_publicspends.py
Labels: Network, P2P, Upstream

#1623 [GUI][Trivial] Change Custom fee amount when Recommended fee is selected
  src/qt/pivx/forms/sendcustomfeedialog.ui
Labels: GUI, Trivial

#1718 [Trivial] Spelling Error
  src/wallet/wallet.cpp
Labels: NoFunctionalChanges, Trivial

#1702 [RPC] Table registration update and wallet table decoupled.
  src/Makefile.am
  src/init.cpp
  src/rpc/rawtransaction.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/wallet/rpcwallet.cpp
  src/wallet/rpcwallet.h
  src/wallet/test/wallet_test_fixture.cpp
Labels: RPC, Upstream

#1669 Better sigcache implementation (CuckooCache)
  src/Makefile.am
  src/Makefile.test.include
  src/cuckoocache.h
  src/init.cpp
  src/script/sigcache.cpp
  src/script/sigcache.h
  src/test/cuckoocache_tests.cpp
  src/test/test_pivx.cpp
Labels: Refactoring, Resource usage, Upstream, Validation

#1724 [GUI] Return early in pollBalanceChanged
  src/qt/walletmodel.cpp
Labels: GUI

#1729 [Core] Add checkpoints for PIVX v4.1.1 enforcement
  src/chainparams.cpp
Labels: Validation

#1679 Prepare for non-Base58 addresses [Step 3]
  src/base58.cpp
  src/base58.h
  src/qt/paymentserver.cpp
  src/qt/pivx/settings/settingsmultisendwidget.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/rpc/blockchain.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_zerocoin.cpp
Labels: Refactoring, Upstream, Wallet

#1707 RPC & Mempool back ports.
  src/coins.cpp
  src/coins.h
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/rpc/server.cpp
  src/test/mempool_tests.cpp
  src/test/miner_tests.cpp
  src/test/rpc_tests.cpp
  src/test/test_pivx.cpp
  src/test/test_pivx.h
  src/test/util_tests.cpp
  src/txmempool.cpp
  src/txmempool.h
  src/utilstrencodings.cpp
  src/utilstrencodings.h
  test/functional/mempool_packages.py
  test/functional/mempool_reorg.py
  test/functional/rpc_fundrawtransaction.py
  test/functional/rpc_rawtransaction.py
  test/functional/test_framework/util.py
Labels: Mempool, RPC, Tests, Upstream

#1722 Unused methods cleanup
  src/main.cpp
  src/masternodeman.cpp
  src/masternodeman.h
Labels: Cleanup

#1708 [BUG][GUI] Non-static coinControl object in CoinControlDialogs
  src/base58.h
  src/qt/coincontroldialog.cpp
  src/qt/coincontroldialog.h
  src/qt/pivx/coldstakingwidget.cpp
  src/qt/pivx/send.cpp
  src/qt/pivx/sendchangeaddressdialog.cpp
  src/qt/pivx/sendchangeaddressdialog.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: Bug, GUI

#1728 IsInitialBlockDownload: usually avoid locking
  src/main.cpp
Labels: Refactoring, Upstream

#1059 [UI] Improve staking chart workflow
  src/qt/pivx/dashboardwidget.cpp
Labels: GUI

#1719 [Cleanup] remove masternode broadcast from CActiveMasternode class
  doc/release-notes.md
  src/activemasternode.cpp
  src/activemasternode.h
  src/masternode-budget.cpp
  src/masternode-payments.cpp
  src/masternode.cpp
  src/rpc/budget.cpp
  src/rpc/masternode.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/swifttx.cpp
  src/wallet/wallet.h
Labels: Cleanup, Masternode

#1713 [Refactor] zerocoin code moved from wallet.cpp to wallet_zerocoin.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_zerocoin.cpp
Labels: NoFunctionalChanges, Refactoring

#1734 [Wallet][BUG] fix detection of wallet conflicts in CWallet::AddToWallet
  src/wallet/wallet.cpp
Labels: Bug, Upstream, Wallet

#1737 [GUI] Replace more deprecated Qt methods
  src/Makefile.qt.include
  src/qt/CMakeLists.txt
  src/qt/addresstablemodel.cpp
  src/qt/bantablemodel.cpp
  src/qt/guiutil.cpp
  src/qt/peertablemodel.cpp
  src/qt/pivx/dashboardwidget.cpp
  src/qt/pivx/pivxgui.cpp
  src/qt/pivx/splash.cpp
  src/qt/pivx/welcomecontentwidget.cpp
  src/qt/rpcconsole.cpp
  src/qt/splashscreen.cpp
  src/qt/splashscreen.h
  src/qt/utilitydialog.h
Labels: Cleanup, GUI

#1732 [GUI] Better start single MN error description.
  src/masternode.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Refactoring

#1740 [GUI] Periodic make translate
  src/qt/locale/pivx_en.ts
  src/qt/pivx/topbar.cpp
  src/qt/pivxstrings.cpp
Labels: GUI

#1717 [Wallet] AddToWallet split in AddToWallet and LoadToWallet
  src/init.cpp
  src/main.cpp
  src/test/accounting_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_zerocoin.cpp
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
  src/zpiv/zpivwallet.cpp
  src/zpivchain.cpp
Labels: Needs Backport, Refactoring, Upstream, Wallet

#1733 Move zerocoin validation to its own legacy file.
  CMakeLists.txt
  src/Makefile.am
  src/legacy/validation_zerocoin_legacy.cpp
  src/legacy/validation_zerocoin_legacy.h
  src/main.cpp
Labels: Cleanup, Needs Backport, NoFunctionalChanges, Refactoring

#1736 [Cleanup] Transaction primitive unused methods cleanup.
  src/primitives/transaction.cpp
  src/primitives/transaction.h
Labels: Cleanup, Needs Backport, NoFunctionalChanges

#1742 [GUI] Fix settings language combobox initialization.
  src/qt/optionsmodel.h
  src/qt/pivx/settings/settingsdisplayoptionswidget.cpp
  src/qt/pivx/settings/settingswidget.cpp
Labels: Bug, GUI, Needs Backport

#1741 [GUI] Settings console message moved to read only.
  src/qt/pivx/settings/settingsconsolewidget.cpp
Labels: Bug, GUI, Needs Backport

#1743 [Build] Bump version to 4.2.0rc1
  configure.ac
  doc/man/pivx-cli.1
  doc/man/pivx-qt.1
  doc/man/pivx-tx.1
  doc/man/pivxd.1
Labels: Build System

#1744 [GUI] Recognize key event for clearing console
  src/qt/pivx/settings/settingsconsolewidget.cpp
Labels: Bug, GUI, Needs Backport

#1703 [Build] Require minimum boost version 1.57.0
  .travis.yml
  configure.ac
  doc/dependencies.md
  src/fs.h
  src/init.cpp
  src/qt/guiutil.cpp
  src/qt/pivx.cpp
  src/qt/pivx/masternodeswidget.cpp
  src/qt/pivx/masternodewizarddialog.cpp
  src/rpc/protocol.cpp
  src/scheduler.cpp
  src/test/scheduler_tests.cpp
  src/torcontrol.cpp
  src/util.cpp
  src/utiltime.cpp
Labels: Build System, Needs Release Notes

#1746 [Core] Only include undo.h from main.cpp
  src/coins.cpp
  src/coins.h
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/txmempool.cpp
  src/undo.h
Labels: Refactoring, Upstream

#1287 [GUI] Load persisted transaction filter during start
  src/qt/pivx/dashboardwidget.cpp
  src/qt/pivx/dashboardwidget.h
Labels: Bug, GUI, Needs Backport

#1751 [Miner] Unused reserveKey cleanup
  src/miner.cpp
Labels: Cleanup, Needs Backport

#1747 NU custom activation height startup arg.
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/upgrades.cpp
  src/init.cpp
  src/rpc/blockchain.cpp
Labels: Bug, Needs Backport, Startup

#1749 [GUI] Solving old, not loaded at startup, transactions notification issue.
  src/qt/transactiontablemodel.cpp
Labels: Bug, GUI, Needs Backport

#1762 [Doc] 4.2.0 Release Notes
  doc/release-notes.md
Labels: Docs and Output

#1735 [Validation] DisconnectBlock updates.
  src/main.cpp
Labels: Refactoring, Upstream

#1754 [Model] Wallet interface refactor + code cleanup.
  CMakeLists.txt
  src/Makefile.am
  src/interface/wallet.cpp
  src/interface/wallet.h
  src/qt/pivx/topbar.cpp
  src/qt/pivx/topbar.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: GUI, Refactoring, Wallet

#1752 [Wallet] Simple unused methods cleanup.
  src/primitives/block.cpp
  src/primitives/block.h
  src/wallet/wallet.h
  src/wallet/wallet_zerocoin.cpp
Labels: Cleanup, Wallet, zPiv

#1765 [Build] Bump master to 4.2.99 (pre-5.0)
  build-aux/snap/snapcraft.yaml
  configure.ac
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win.yml
Labels: Build System, Trivial

#1764 [wallet] Securely erase potentially sensitive keys/values
  src/support/cleanse.h
  src/wallet/db.h
Labels: Upstream, Wallet

#1767 [Wallet] Ignore MarkConflict if block hash is not known
  src/wallet/wallet.cpp
Labels: Bug, Needs Backport, Upstream, Wallet

#1769 [Net] Remove bogus assert on number of oubound connections.
  src/net.cpp
Labels: Needs Backport, P2P, Upstream

#1772 [Doc] save historical rel notes for 4.2.0 and reset template
  doc/release-notes.md
  doc/release-notes/release-notes-4.2.0.md
Labels: Documentation, NoFunctionalChanges, Trivial

#1694 [Backport] Test LowS in standardness, removes nuisance malleability vector
  src/policy/policy.h
Labels: Upstream
