Repository PIVX-Project/PIVX, pull requests merged in 2020-05, with the labels that each got.

#1594 [GUI][Bug] Reconnect CS owner address edit-label action
  src/qt/pivx/coldstakingwidget.cpp
Labels: Bug, GUI, Needs Backport

#1591 Removing dead seeder
  src/chainparams.cpp
Labels: Cleanup, Needs Backport, P2P

#1595 [GUI][Bug] Fix "Select all" / "Unselect all" logic in coincontrol
  src/qt/coincontroldialog.cpp
  src/qt/coincontroldialog.h
Labels: Bug, GUI, Needs Backport

#1590 [GUI] Update translations from Transifex for 4.1
  .tx/config
  src/Makefile.qt_locale.include
  src/qt/locale/pivx_bg.ts
  src/qt/locale/pivx_ca.ts
  src/qt/locale/pivx_cs.ts
  src/qt/locale/pivx_da.ts
  src/qt/locale/pivx_de.ts
  src/qt/locale/pivx_en.ts
  src/qt/locale/pivx_en_GB.ts
  src/qt/locale/pivx_en_US.ts
  src/qt/locale/pivx_eo.ts
  src/qt/locale/pivx_es.ts
  src/qt/locale/pivx_es_ES.ts
  src/qt/locale/pivx_fi.ts
  src/qt/locale/pivx_fr_FR.ts
  src/qt/locale/pivx_hi_IN.ts
  src/qt/locale/pivx_hr.ts
  src/qt/locale/pivx_hr_HR.ts
  src/qt/locale/pivx_it.ts
  src/qt/locale/pivx_ja.ts
  src/qt/locale/pivx_ko_KR.ts
  src/qt/locale/pivx_lt_LT.ts
  src/qt/locale/pivx_nl.ts
  src/qt/locale/pivx_pl.ts
  src/qt/locale/pivx_pt.ts
  src/qt/locale/pivx_pt_BR.ts
  src/qt/locale/pivx_ro_RO.ts
  src/qt/locale/pivx_ru.ts
  src/qt/locale/pivx_sk.ts
  src/qt/locale/pivx_sv.ts
  src/qt/locale/pivx_tr.ts
  src/qt/locale/pivx_uk.ts
  src/qt/locale/pivx_vi.ts
  src/qt/locale/pivx_zh_CN.ts
  src/qt/locale/pivx_zh_TW.ts
  src/qt/pivx_locale.qrc
  src/qt/pivxstrings.cpp
Labels: GUI, Needs Backport

#1599 [GUI][Bug] Fix language selection invalidly stored
  src/qt/pivx.cpp
  src/qt/pivx/settings/settingsdisplayoptionswidget.cpp
  src/qt/pivx/welcomecontentwidget.cpp
  src/qt/pivx/welcomecontentwidget.h
Labels: Bug, GUI, Needs Backport

#1588 [GUI][Bug] Fix editing of CS address labels
  src/wallet/wallet.cpp
Labels: Bug, GUI, Needs Backport

#1589 [GUI][Bug] Don't clear address label during send address validation
  src/qt/pivx/send.cpp
  src/qt/pivx/sendmultirow.cpp
  src/qt/pivx/sendmultirow.h
Labels: Bug, GUI, Needs Backport

#1584 [Doc] Finalize 4.1.0 release notes
  doc/release-notes.md
Labels: Docs and Output, Needs Backport

#1579 [Net] Use SeedSpec6's rather than CAddress's for fixed seeds
  src/chainparams.cpp
  src/chainparams.h
  src/net.cpp
Labels: Network, Refactoring

#1542 [Net] Add and document network messages in protocol.h
  src/main.cpp
  src/masternode-budget.cpp
  src/masternode-payments.cpp
  src/masternode-sync.cpp
  src/masternodeman.cpp
  src/net.cpp
  src/protocol.cpp
  src/protocol.h
  src/qt/walletmodel.cpp
  src/rpc/budget.cpp
  src/spork.cpp
  src/swifttx.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Network, P2P

#1607 [QT] Add password mismatch warnings
  src/qt/askpassphrasedialog.cpp
  src/qt/askpassphrasedialog.h
  src/qt/forms/askpassphrasedialog.ui
Labels: Feature Request, GUI, Usability

#1414 uint256 to arith_uint256 migration (Second step).
  CMakeLists.txt
  src/Makefile.am
  src/Makefile.test.include
  src/arith_uint256.cpp
  src/arith_uint256.h
  src/blob_uint256.cpp
  src/blob_uint256.h
  src/test/arith_uint256_tests.cpp
  src/uint256.cpp
  src/uint256.h
  src/uint512.h
Labels: Refactoring, Upstream

#1616 [P2P] Enforce expected outbound services
  src/activemasternode.cpp
  src/addrman.cpp
  src/addrman.h
  src/init.cpp
  src/main.cpp
  src/masternodeman.cpp
  src/net.cpp
  src/net.h
  src/protocol.cpp
  src/protocol.h
  src/rpc/masternode.cpp
  src/test/DoS_tests.cpp
  src/test/addrman_tests.cpp
  src/test/net_tests.cpp
Labels: P2P, Upstream

#1610 [GUI][UX] Add accept/close keyboard controls to all dialogs
  src/Makefile.qt.include
  src/qt/CMakeLists.txt
  src/qt/pivx/addnewcontactdialog.cpp
  src/qt/pivx/addnewcontactdialog.h
  src/qt/pivx/defaultdialog.cpp
  src/qt/pivx/defaultdialog.h
  src/qt/pivx/focuseddialog.cpp
  src/qt/pivx/focuseddialog.h
  src/qt/pivx/masternodewizarddialog.cpp
  src/qt/pivx/masternodewizarddialog.h
  src/qt/pivx/mninfodialog.cpp
  src/qt/pivx/mninfodialog.h
  src/qt/pivx/receivedialog.cpp
  src/qt/pivx/receivedialog.h
  src/qt/pivx/requestdialog.cpp
  src/qt/pivx/requestdialog.h
  src/qt/pivx/sendchangeaddressdialog.cpp
  src/qt/pivx/sendchangeaddressdialog.h
  src/qt/pivx/sendconfirmdialog.cpp
  src/qt/pivx/sendconfirmdialog.h
  src/qt/pivx/sendcustomfeedialog.cpp
  src/qt/pivx/sendcustomfeedialog.h
Labels: Feature Request, GUI, Usability

#1625 [Doc] save historical release notes for 4.1.0 and reset template
  doc/release-notes.md
  doc/release-notes/release-notes-4.1.0.md
Labels: Docs and Output, Trivial

#1618 [P2P] Do not set extra flags for unfiltered DNS seed results
  src/chainparams.cpp
  src/chainparams.h
  src/net.cpp
Labels: P2P, Upstream

#1531 [Backport] Implement accurate UTXO cache size accounting
  src/Makefile.am
  src/coins.cpp
  src/coins.h
  src/init.cpp
  src/main.cpp
  src/main.h
  src/memusage.h
  src/test/coins_tests.cpp
  src/txdb.h
Labels: UTXO DBs and Indexes, Upstream

#1486 Replace OpenSSL AES with ctaes-based version
  CMakeLists.txt
  src/Makefile.am
  src/Makefile.test.include
  src/crypter.cpp
  src/crypter.h
  src/crypto/aes.cpp
  src/crypto/aes.h
  src/crypto/ctaes/COPYING
  src/crypto/ctaes/README.md
  src/crypto/ctaes/bench.c
  src/crypto/ctaes/ctaes.c
  src/crypto/ctaes/ctaes.h
  src/crypto/ctaes/test.c
  src/test/crypto_tests.cpp
  src/wallet/test/crypto_tests.cpp
Labels: Upstream, Wallet

#1554 [Core] Big endian support
  src/hash.cpp
  src/main.cpp
  src/net.cpp
  src/netbase.h
  src/primitives/block.cpp
  src/primitives/transaction.h
  src/script/script.h
  src/serialize.h
  src/test/serialize_tests.cpp
  src/txmempool.cpp
Labels: Upstream

#1488 CCrypter using secure allocator vector.
  src/allocators.h
  src/crypter.cpp
  src/crypter.h
  src/wallet/test/crypto_tests.cpp
Labels: Upstream, Wallet

#1557 [Core] Prevector
  src/Makefile.am
  src/Makefile.test.include
  src/coins.h
  src/hash.h
  src/masternode-budget.h
  src/masternode-payments.cpp
  src/masternode-payments.h
  src/memusage.h
  src/prevector.h
  src/primitives/transaction.h
  src/qt/transactionrecord.h
  src/script/interpreter.cpp
  src/script/script.cpp
  src/script/script.h
  src/script/sign.cpp
  src/serialize.h
  src/test/miner_tests.cpp
  src/test/prevector_tests.cpp
  src/test/script_P2SH_tests.cpp
  src/test/script_tests.cpp
  src/test/sigopcount_tests.cpp
  src/wallet/walletdb.cpp
Labels: Refactoring, Resource usage, Upstream, Util / log / libs, Validation

#1593 Prepare for non-Base58 addresses [Step 1]
  src/activemasternode.cpp
  src/base58.cpp
  src/base58.h
  src/bip38.cpp
  src/core_write.cpp
  src/masternode-budget.cpp
  src/masternode-payments.cpp
  src/masternode.cpp
  src/messagesigner.cpp
  src/net.cpp
  src/pivx-tx.cpp
  src/qt/addresstablemodel.cpp
  src/qt/bitcoinaddressvalidator.cpp
  src/qt/coincontroldialog.cpp
  src/qt/guiutil.cpp
  src/qt/pivx/addresseswidget.cpp
  src/qt/pivx/coldstakingmodel.cpp
  src/qt/pivx/coldstakingwidget.cpp
  src/qt/pivx/masternodewizarddialog.cpp
  src/qt/pivx/receivewidget.cpp
  src/qt/pivx/requestdialog.cpp
  src/qt/pivx/send.cpp
  src/qt/pivx/settings/settingssignmessagewidgets.cpp
  src/qt/transactionrecord.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/rpc/budget.cpp
  src/rpc/masternode.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/rawtransaction.cpp
  src/script/standard.cpp
  src/script/standard.h
  src/test/base58_tests.cpp
  src/test/key_tests.cpp
  src/test/zerocoin_transactions_tests.cpp
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_zerocoin.cpp
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
Labels: Upstream, Wallet

#1516 [GUI] MacOS fix open files with no default app.
  src/qt/guiutil.cpp
Labels: GUI, Upstream, macOS

#1533 [Backport] Make connect=0 disable automatic outbound connections.
  src/init.cpp
  src/net.cpp
Labels: P2P, Upstream

#1534 [Backport] Preemptively catch a few potential bugs
  src/coins.h
Labels: Refactoring, Upstream

#1564 Abstract out CTransaction-specific signing into SignatureCreator
  src/script/sign.cpp
  src/script/sign.h
Labels: Refactoring, Upstream

#1547 [Refactor] Define constant string variable for currency unit
  src/amount.cpp
  src/amount.h
  src/init.cpp
  src/qt/askpassphrasedialog.cpp
  src/qt/bitcoinunits.cpp
  src/qt/pivx/coldstakingwidget.cpp
  src/qt/pivx/dashboardwidget.cpp
  src/qt/pivx/masternodeswidget.cpp
  src/qt/pivx/requestdialog.cpp
  src/qt/pivx/send.cpp
  src/qt/transactiontablemodel.cpp
  src/qt/walletmodel.cpp
  src/rpc/budget.cpp
  test/functional/feature_help.py
Labels: Refactoring

#1638 [Net] Fix masking of irrelevant bits in address groups
  src/netbase.cpp
  src/test/netbase_tests.cpp
Labels: Bug, Network, P2P

#1634 [Core] prevector: named union and defaults vars initialization
  src/prevector.h
Labels: Refactoring, Upstream

#1626 [GUI][Bug] Notify transaction creation failure reason
  src/qt/pivx/guitransactionsutils.cpp
  src/qt/pivx/pivxgui.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: Bug, GUI

#1644 [GUI] Fix invalid Destination toString encoding.
  src/base58.h
  src/qt/walletmodel.cpp
Labels: Bug, GUI

#1640 [P2P][RPC] Rework addnode behaviour
  src/net.cpp
  src/net.h
  src/netbase.cpp
  src/rpc/net.cpp
Labels: Needs Release Notes, P2P, RPC

#1629 [DB] Bitcoin 0.12-0.14 dbwrapper improvements
  CMakeLists.txt
  src/Makefile.am
  src/Makefile.test.include
  src/dbwrapper.cpp
  src/dbwrapper.h
  src/rpc/blockchain.cpp
  src/sporkdb.cpp
  src/sporkdb.h
  src/test/dbwrapper_tests.cpp
  src/txdb.cpp
  src/txdb.h
Labels: Refactoring, UTXO DBs and Indexes, Upstream
