Repository PIVX-Project/PIVX, pull requests merged in 2020-04, with the labels that each got.

#1445 [Refactor] Init wallet parameters interaction
  src/Makefile.am
  src/guiinterfaceutil.h
  src/init.cpp
  src/init.h
  src/rpc/server.cpp
  src/stakeinput.h
  src/test/test_pivx.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/zpiv/zpos.h
Labels: Refactoring, Startup, Upstream

#1474 [Wallet] Fix wrong Lock/Unlock zWallet method call.
  src/crypter.cpp
  src/crypter.h
  src/init.cpp
  src/test/zerocoin_transactions_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_zerocoin.cpp
  src/zpiv/zpivtracker.cpp
  src/zpiv/zpivtracker.h
  src/zpiv/zpivwallet.cpp
  src/zpiv/zpivwallet.h
Labels: Wallet, zPiv

#1477 [GUI][Trivial] ColdStakingWidget: fix containerSend margins
  src/qt/pivx/forms/coldstakingwidget.ui
Labels: GUI, Trivial

#1437 [Util] LogAcceptCategory: use uint32_t rather than sets of strings
  src/activemasternode.cpp
  src/addrman.cpp
  src/addrman.h
  src/consensus/zerocoin_verify.cpp
  src/denomination_functions.cpp
  src/httprpc.cpp
  src/httpserver.cpp
  src/init.cpp
  src/kernel.cpp
  src/main.cpp
  src/masternode-budget.cpp
  src/masternode-payments.cpp
  src/masternode-sync.cpp
  src/masternode.cpp
  src/masternodeman.cpp
  src/miner.cpp
  src/net.cpp
  src/netbase.cpp
  src/obfuscation.cpp
  src/obfuscation.h
  src/protocol.cpp
  src/qt/pivx.cpp
  src/qt/transactiondesc.cpp
  src/qt/winshutdownmonitor.cpp
  src/random.cpp
  src/rpc/server.cpp
  src/spork.cpp
  src/swifttx.cpp
  src/timedata.cpp
  src/torcontrol.cpp
  src/txdb.cpp
  src/txmempool.cpp
  src/util.cpp
  src/util.h
  src/wallet/db.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet_zerocoin.cpp
  src/wallet/walletdb.cpp
  src/zmq/zmqnotificationinterface.cpp
  src/zmq/zmqpublishnotifier.cpp
  src/zpiv/zpivtracker.cpp
  src/zpiv/zpivwallet.cpp
  src/zpivchain.cpp
Labels: Refactoring, Upstream, Util / log / libs

#1473 [GUI] Hide charts container when not USE_QTCHARTS
  src/qt/pivx/dashboardwidget.cpp
Labels: GUI

#1483 [Depends] Update OpenSSL download URL
  depends/packages/openssl.mk
Labels: Build System, Trivial

#1481 [BugFix] Tor topbar button text.
  src/qt/pivx/topbar.cpp
Labels: GUI, Trivial

#1487 [GUI] ClientModel cacheTip sync with back-end.
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
Labels: GUI

#1439 [Core] Add -debugexclude option
  src/init.cpp
Labels: Tests, Upstream, Util / log / libs

#1469 [GUI][Cleanup] Coin Control Cleanup
  src/Makefile.qt.include
  src/qt/CMakeLists.txt
  src/qt/coincontroldialog.cpp
  src/qt/forms/coincontroldialog.ui
  src/qt/pivx/coincontrolpivwidget.cpp
  src/qt/pivx/coincontrolpivwidget.h
  src/qt/pivx/forms/coincontrolpivwidget.ui
Labels: Cleanup, GUI, Trivial

#1484 [Net] Fix resource leak in ReadBinaryFile
  src/torcontrol.cpp
Labels: P2P, Upstream

#1489 [GUI] Add missing error notification in encrypt wallet.
  src/qt/askpassphrasedialog.cpp
Labels: GUI

#1492 [Net] Relay actual peers instead of localhost on getaddr
  src/net.h
Labels: P2P

#1393 [GUI] Customizable sorting for address books
  doc/release-notes.md
  src/qt/pivx/addresseswidget.cpp
  src/qt/pivx/addresseswidget.h
  src/qt/pivx/coldstakingwidget.cpp
  src/qt/pivx/coldstakingwidget.h
  src/qt/pivx/contactsdropdown.cpp
  src/qt/pivx/dashboardwidget.cpp
  src/qt/pivx/forms/addresseswidget.ui
  src/qt/pivx/forms/coldstakingwidget.ui
  src/qt/pivx/forms/receivewidget.ui
  src/qt/pivx/qtutils.cpp
  src/qt/pivx/qtutils.h
  src/qt/pivx/receivewidget.cpp
  src/qt/pivx/receivewidget.h
  src/qt/pivx/res/css/style_dark.css
  src/qt/pivx/res/css/style_light.css
Labels: Feature Request, GUI, Usability

#1495 [Wallet] Clean wrong pwalletMain inside wallet class.
  src/crypter.cpp
  src/crypter.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_zerocoin.cpp
  src/zpiv/zpivwallet.cpp
Labels: Bug, Wallet, zPiv

#1497 [Trivial][RPC] Remove references to old command list-conf
  src/rpc/masternode.cpp
Labels: RPC, Trivial

#1450 [Util] Buffer log messages and explicitly open logs
  src/init.cpp
  src/util.cpp
  src/util.h
Labels: Refactoring, Upstream, Util / log / libs

#1451 [RPC] Add logging RPC
  doc/release-notes.md
  src/httpserver.cpp
  src/httpserver.h
  src/rpc/client.cpp
  src/rpc/misc.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/util.cpp
  src/util.h
Labels: RPC, Upstream, Util / log / libs

#1446 [Test] Wallet testing setup.
  src/Makefile.test.include
  src/test/accounting_tests.cpp
  src/test/test_pivx.cpp
  src/test/zerocoin_transactions_tests.cpp
  src/wallet/test/wallet_test_fixture.cpp
  src/wallet/test/wallet_test_fixture.h
  src/wallet/test/wallet_tests.cpp
Labels: Tests, Upstream, Wallet

#1047 [Qt] Add more information to settings info panel
  src/qt/clientmodel.h
  src/qt/pivx/res/css/style_dark.css
  src/qt/pivx/res/css/style_light.css
  src/qt/pivx/settings/forms/settingsinformationwidget.ui
  src/qt/pivx/settings/settingsinformationwidget.cpp
  src/qt/pivx/settings/settingsinformationwidget.h
  src/qt/rpcconsole.cpp
Labels: GUI

#1501 [GUI] Update MNs count every 40 seconds.
  src/qt/clientmodel.cpp
Labels: GUI, Trivial

#1493 [Depends] Include qt-gif plugin.
  build-aux/m4/bitcoin_qt.m4
  depends/packages/qt.mk
  src/qt/pivx.cpp
Labels: Build System, GUI

#1447 [GUI] Add address-label to sendconfirm-popup
  src/qt/pivx/forms/sendconfirmdialog.ui
  src/qt/pivx/sendconfirmdialog.cpp
Labels: GUI, Usability

#1406 [GUI] Save custom fee selected
  doc/release-notes.md
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/qt/pivx/send.cpp
  src/qt/pivx/send.h
  src/qt/pivx/sendcustomfeedialog.cpp
  src/qt/pivx/sendcustomfeedialog.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
Labels: Feature Request, GUI, Usability

#1470 [GUI] Mark delegated UTXOs in CoinControl
  src/qt/coincontroldialog.cpp
Labels: GUI, Usability

#1391 [GUI] Spend cold-stake delegations
  doc/release-notes.md
  src/qt/pivx/coldstakingwidget.cpp
  src/qt/pivx/forms/send.ui
  src/qt/pivx/masternodewizarddialog.cpp
  src/qt/pivx/send.cpp
  src/qt/pivx/send.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/rpc/rawtransaction.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_zerocoin.cpp
Labels: Cold Staking, GUI, Usability

#1499 [GUI] Settings console, clear history button.
  src/qt/pivx/settings/forms/settingsconsolewidget.ui
  src/qt/pivx/settings/settingsconsolewidget.cpp
  src/qt/pivx/settings/settingsconsolewidget.h
Labels: GUI

#1491 [Consensus] Revert 1462
  src/chain.cpp
  src/chain.h
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/tx_verify.cpp
  src/consensus/tx_verify.h
  src/kernel.cpp
  src/main.cpp
  src/miner.cpp
  src/primitives/block.h
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/rpc/blockchain.cpp
  src/script/interpreter.cpp
  src/script/script.cpp
  src/script/script.h
  src/script/script_error.cpp
  src/script/script_error.h
  src/version.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  test/functional/mining_pos_reorg.py
  test/functional/test_framework/messages.py
  test/functional/test_framework/test_framework.py
Labels: Consensus

#1485 [Wallet] Fix BIP38 import crashing on empty DecKey
  src/qt/pivx/settings/settingsbittoolwidget.cpp
Labels: Bug, GUI

#1494 [Qt] Convert leftover connects to Qt5 syntax
  src/qt/pivx/loadingdialog.cpp
  src/qt/pivx/pwidget.cpp
Labels: GUI

#1475 [GUI] Hide charts at startup or at runtime
  doc/release-notes.md
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/qt/pivx/dashboardwidget.cpp
  src/qt/pivx/dashboardwidget.h
  src/qt/pivx/settings/forms/settingsdisplayoptionswidget.ui
  src/qt/pivx/settings/settingsdisplayoptionswidget.cpp
  src/qt/utilitydialog.cpp
Labels: GUI

#1455 [Init] Add `-debuglogfile` option
  doc/release-notes.md
  src/init.cpp
  src/util.cpp
  src/util.h
  test/functional/feature_logging.py
  test/functional/test_runner.py
Labels: Tests, Upstream, Util / log / libs

#1509 Correct the reference to ColdStakingWidget address
  src/qt/pivx/pivxgui.cpp
Labels: Bug, GUI

#1510 [GUI] Fix text cut-off in sendchangeaddressdialog
  src/qt/pivx/forms/sendchangeaddressdialog.ui
Labels: Bug, GUI

#1504 [BUG] Fix ambiguous call to distance in ParseAccChecksum
  src/zpiv/zpos.cpp
Labels: Bug, Trivial

#1507 [Trivial] Remove leftover temporary comment
  src/qt/pivx/dashboardwidget.h
Labels: NoFunctionalChanges, Trivial

#1508 [BUG] Prevent StartAll from starting mns with immature collateral
  src/qt/pivx/masternodeswidget.cpp
  src/qt/pivx/mnmodel.cpp
  src/qt/pivx/mnmodel.h
Labels: Bug, GUI, Masternode

#1502 [Core] Reduce CBlockIndex RAM usage
  configure.ac
  doc/release-notes.md
  src/chain.cpp
  src/chain.h
  src/consensus/zerocoin_verify.cpp
  src/consensus/zerocoin_verify.h
  src/init.cpp
  src/main.cpp
  src/main.h
  src/masternode-payments.cpp
  src/rpc/blockchain.cpp
  src/rpc/misc.cpp
  src/txdb.cpp
  src/txdb.h
  src/zpivchain.cpp
  src/zpivchain.h
  test/functional/mining_pos_reorg.py
Labels: Cleanup, UTXO DBs and Indexes, enhancement

#1513 [Trivial] Remove CMasternode::SliceHash
  src/masternode.h
Labels: Bug, Cleanup, Trivial

#1517 Shutdown: remove PID file at the very end.
  src/init.cpp
Labels: Trivial

#1490 [Cleanup] Nuke obfuscation from orbit
  CMakeLists.txt
  doc/release-notes.md
  src/Makefile.am
  src/activemasternode.cpp
  src/activemasternode.h
  src/chainparams.cpp
  src/coincontrol.h
  src/consensus/params.h
  src/init.cpp
  src/main.cpp
  src/masternode-budget.cpp
  src/masternode-payments.cpp
  src/masternode.cpp
  src/masternode.h
  src/masternodeman.cpp
  src/masternodeman.h
  src/net.cpp
  src/net.h
  src/obfuscation-relay.cpp
  src/obfuscation-relay.h
  src/obfuscation.cpp
  src/obfuscation.h
  src/protocol.cpp
  src/qt/coincontroldialog.cpp
  src/qt/optionsdialog.cpp
  src/qt/pivx/pivxgui.cpp
  src/qt/pivx/topbar.cpp
  src/qt/pivx/txrow.cpp
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/rpc/budget.cpp
  src/rpc/masternode.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/spork.cpp
  src/spork.h
  src/swifttx.cpp
  src/util.cpp
  src/util.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Cleanup

#1388 [GUI] Customize the timeout of the SnackBar based on its message length
  src/qt/pivx/snackbar.cpp
  src/qt/pivx/snackbar.h
Labels: GUI, Usability

#1423 [GUI][Trivial] Fix button size in welcomecontentwidget
  src/qt/pivx/forms/welcomecontentwidget.ui
Labels: GUI, Trivial

#1503 [GUI] Fix cold staking owner dropdown position.
  src/qt/pivx/coldstakingwidget.cpp
Labels: Bug, GUI

#1436 [Trivial] Rewording of remote masternode data export notification
  src/qt/pivx/masternodeswidget.cpp
Labels: Trivial

#1515 [GUI] Back port latest MacOS dock icon handler.
  configure.ac
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/macdockiconhandler.h
  src/qt/macdockiconhandler.mm
  src/qt/pivx/pivxgui.cpp
  src/qt/pivx/pivxgui.h
Labels: Bug, Build System, GUI, Upstream, macOS

#1520 SetMerkleBranch: remove unused code, remove cs_main lock requirement
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Refactoring, Upstream, Wallet

#1459 [Util] Refactor logging code into a global object
  CMakeLists.txt
  src/Makefile.am
  src/activemasternode.cpp
  src/httpserver.cpp
  src/httpserver.h
  src/init.cpp
  src/logging.cpp
  src/logging.h
  src/main.cpp
  src/qt/transactiondesc.cpp
  src/rpc/misc.cpp
  src/test/test_pivx.cpp
  src/timedata.cpp
  src/util.cpp
  src/util.h
Labels: Refactoring, Upstream, Util / log / libs

#1479 [BUG][GUI] Fix MasternodeWidget StartAll
  src/qt/pivx/loadingdialog.cpp
  src/qt/pivx/loadingdialog.h
  src/qt/pivx/masternodeswidget.cpp
  src/qt/pivx/masternodeswidget.h
  src/qt/pivx/pwidget.cpp
  src/qt/pivx/pwidget.h
  src/qt/pivx/topbar.cpp
  src/qt/pivx/topbar.h
Labels: Bug, GUI, Masternode, Refactoring

#1522 [Qt] Fixup filter dropdown localizations
  src/qt/pivx/qtutils.cpp
  src/qt/pivx/qtutils.h
Labels: GUI

#1523 [Trivial] [GUI] Fix masternodeswidget snackbar typos
  src/qt/pivx/masternodeswidget.cpp
Labels: GUI, Trivial

#1525 [Build] Bump version to 4.1.0rc1
  configure.ac
Labels: Build System

#1530 [GUI] Don't log to console by default.
  src/qt/pivx.cpp
Labels: GUI, Upstream

#1425 [Trivial][GUI] Add more room to contacts dropdown
  src/qt/pivx/coldstakingwidget.cpp
  src/qt/pivx/send.cpp
Labels: GUI, Trivial

#1429 [GUI] Dark theme, inactive icons color fix.
  src/qt/pivx/res/img/dark/ic-transaction-mint-inactive.svg
  src/qt/pivx/res/img/dark/ic-transaction-received-inactive.svg
  src/qt/pivx/res/img/dark/ic-transaction-sent-inactive.svg
  src/qt/pivx/res/img/dark/ic-transaction-staked-inactive.svg
Labels: Bug, GUI, Needs Backport

#1532 [Build] Bump master to 4.1.99
  build-aux/snap/snapcraft.yaml
  configure.ac
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win.yml
Labels: Build System

#1527 [GUI] Warn about change address not belonging to the wallet.
  src/qt/pivx/send.cpp
Labels: GUI, Needs Backport

#1529 [Trivial] Fix compiler warning in mousePressEvent.
  src/qt/pivx/expandablebutton.cpp
  src/qt/pivx/expandablebutton.h
Labels: GUI, Needs Backport, Trivial

#1536 [Build] Disable apt-cacher for Windows WSL gitian setup
  contrib/gitian-build.py
Labels: Build System, Needs Backport, Scripts and Tools, Windows

#1535 [Qt] Don't translate dummy strings in mnrow
  src/qt/pivx/forms/mnrow.ui
Labels: GUI, Trivial

#1538 [P2P] Update hard coded seed nodes
  contrib/seeds/generate-seeds.py
  contrib/seeds/makeseeds.py
  contrib/seeds/suspicious_hosts.txt
  src/chainparamsseeds.h
Labels: Needs Backport, P2P, Scripts and Tools

#1537 BugFix: Cleanup invalid IsMasternodeReward method in OutPoint primitive.
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/wallet/wallet.cpp
Labels: Cleanup, Needs Backport

#1550 [QA] Avoid printing to console during cache creation
  test/functional/test_framework/test_node.py
  test/functional/test_framework/util.py
Labels: Needs Backport, Tests, Upstream

#1545 [GUI] MasternodeWizard validations
  src/net.cpp
  src/net.h
  src/qt/pivx/masternodewizarddialog.cpp
  src/qt/pivx/mnmodel.cpp
  src/qt/pivx/mnmodel.h
  src/test/netbase_tests.cpp
Labels: Bug, GUI, Masternode, Needs Backport, Network

#1543 [GUI][Bug] CoinControl: mark delegated after setting checked state
  src/qt/coincontroldialog.cpp
Labels: Bug, Cold Staking, GUI, Needs Backport

#1556 [GUI] CoinControlDialog remove duplicate esc button
  src/qt/coincontroldialog.cpp
  src/qt/forms/coincontroldialog.ui
Labels: Cleanup, GUI, Needs Backport

#1573 [Doc] Note that v3 onion addresses are not supported
  doc/tor.md
Labels: Docs and Output, Needs Backport

#1551 [GUI][Bug] Reset custom change address
  src/qt/pivx/send.cpp
  src/qt/pivx/sendchangeaddressdialog.cpp
  src/qt/pivx/sendchangeaddressdialog.h
Labels: Bug, GUI, Needs Backport, Usability

#1575 [Bug][Wallet] Fix insane fees
  src/wallet/wallet.cpp
Labels: Bug, Needs Backport, Wallet

#1565 [Bug] Simpler nTimeSmart computation
  src/qt/transactionrecord.cpp
  src/qt/transactiontablemodel.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Bug, Needs Backport, Wallet

#1574 [Bug][GUI] SendCustomFee: reset checkbox on clearAll
  src/qt/pivx/sendcustomfeedialog.cpp
Labels: Bug, GUI, Needs Backport

#1577 [RPC][GUI][Bug] Disable/Hide multisend
  src/main.cpp
  src/qt/pivx/settings/settingswidget.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/walletdb.cpp
Labels: Bug, GUI, Needs Backport, Needs Release Notes, RPC

#1578 [GUI][Bug] Fix transaction details output-index
  src/qt/transactionrecord.cpp
Labels: Bug, GUI, Needs Backport

#1580 [QA][Bug] Shorter wallet_basic.py functional test
  test/functional/test_framework/util.py
  test/functional/test_runner.py
  test/functional/wallet_basic.py
  test/functional/wallet_zapwallettxes.py
Labels: Bug, High Priority, Needs Backport, Tests

#1581 [GUI] Do not create new SettingsMultisendWidget
  src/qt/pivx/settings/settingswidget.cpp
Labels: Bug, GUI, Needs Backport

#1576 [GUI] SendCustomFeeDialog: prevent user from saving insane fees
  src/qt/pivx/send.cpp
  src/qt/pivx/sendcustomfeedialog.cpp
  src/qt/pivx/sendcustomfeedialog.h
Labels: Bug, GUI, Needs Backport, Usability
