Repository PIVX-Project/PIVX, pull requests merged in 2020-12, with the labels that each got.

#1995 [Tests] Fix double bug in sapling_mempool functional test
  test/functional/sapling_mempool.py
Labels: Bug, Sapling, Tests

#1988 [Trivial] Rename placeholder for v5 network upgrade info
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/upgrades.cpp
  src/miner.cpp
  src/policy/policy.cpp
  src/qt/walletmodel.cpp
  src/sapling/sapling_validation.cpp
  src/sapling/saplingscriptpubkeyman.cpp
  src/sapling/transaction_builder.cpp
  src/test/librust/utiltest.cpp
  src/validation.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  test/functional/mining_pos_coldStaking.py
  test/functional/mining_v5_upgrade.py
  test/functional/sapling_changeaddresses.py
  test/functional/sapling_key_import_export.py
  test/functional/sapling_mempool.py
  test/functional/sapling_supply.py
  test/functional/sapling_wallet.py
  test/functional/sapling_wallet_anchorfork.py
  test/functional/sapling_wallet_listreceived.py
  test/functional/sapling_wallet_nullifiers.py
  test/functional/test_framework/test_framework.py
Labels: Trivial

#1994 [Consensus] Bump active protocol version to 70920
  src/validation.cpp
  src/version.h
  test/functional/test_framework/messages.py
Labels: Consensus

#2000 [Core] Masternode collateral index
  src/activemasternode.cpp
  src/budget/budgetmanager.cpp
  src/budget/budgetproposal.cpp
  src/budget/finalizedbudget.cpp
  src/masternode-payments.cpp
  src/masternode.cpp
  src/masternode.h
  src/masternodeman.cpp
  src/masternodeman.h
  src/messagesigner.cpp
  src/qt/pivx/mnmodel.cpp
  src/rpc/budget.cpp
  src/rpc/masternode.cpp
  src/serialize.h
  src/validation.cpp
Labels: Masternode, Refactoring

#2003 [GUI] Tx detail, don't show inputs if there is no information for them.
  src/qt/pivx/sendconfirmdialog.cpp
  src/qt/pivx/sendconfirmdialog.h
Labels: GUI

#2001 [Build] Address more issues with GA
  .github/workflows/build-and-test.yml
Labels: Build System

#2004 [BugFix] [GUI] Shield all transparent balance fee calculation.
  src/qt/pivx/send.cpp
Labels: Bug, GUI

#2008 [BUG] label of coin type in send widget after shielded coin control
  src/qt/pivx/send.cpp
Labels: Bug, GUI

#1999 [GUI] Encrypted memo feature implemented
  src/Makefile.qt.include
  src/qt/CMakeLists.txt
  src/qt/pivx.qrc
  src/qt/pivx/coldstakingwidget.cpp
  src/qt/pivx/forms/sendconfirmdialog.ui
  src/qt/pivx/forms/sendmemodialog.ui
  src/qt/pivx/forms/sendmultirow.ui
  src/qt/pivx/res/css/style_dark.css
  src/qt/pivx/res/css/style_light.css
  src/qt/pivx/res/img/ic-chevron-right-liliac.svg
  src/qt/pivx/send.cpp
  src/qt/pivx/send.h
  src/qt/pivx/sendconfirmdialog.cpp
  src/qt/pivx/sendmemodialog.cpp
  src/qt/pivx/sendmemodialog.h
  src/qt/pivx/sendmultirow.cpp
  src/qt/pivx/sendmultirow.h
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/walletmodel.cpp
  src/sapling/saplingscriptpubkeyman.cpp
  src/sapling/saplingscriptpubkeyman.h
Labels: GUI, Sapling

#1998 [BUG] g_IsSapling active flag during reindex
  src/init.cpp
Labels: Bug, Validation

#2007 [Wallet] Sapling: don't update witnesses for external notes
  src/sapling/saplingscriptpubkeyman.cpp
  src/test/librust/sapling_wallet_tests.cpp
Labels: Sapling, Wallet

#1985 [Cleanup] Remove zerocoin wallet
  CMakeLists.txt
  src/Makefile.am
  src/Makefile.test.include
  src/denomination_functions.cpp
  src/denomination_functions.h
  src/init.cpp
  src/init.h
  src/legacy/validation_zerocoin_legacy.cpp
  src/miner.cpp
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/rpc/misc.cpp
  src/rpc/rawtransaction.cpp
  src/rpc/server.h
  src/test/CMakeLists.txt
  src/test/zerocoin_bignum_tests.cpp
  src/test/zerocoin_denomination_tests.cpp
  src/test/zerocoin_transactions_tests.cpp
  src/validation.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/rpcwallet.h
  src/wallet/rpczpiv.cpp
  src/wallet/test/wallet_test_fixture.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_zerocoin.cpp
  src/wallet/walletdb.h
  src/zpiv/zpivmodule.cpp
  src/zpiv/zpivmodule.h
  src/zpiv/zpivtracker.cpp
  src/zpiv/zpivtracker.h
  src/zpiv/zpivwallet.cpp
  src/zpiv/zpivwallet.h
  src/zpivchain.cpp
  src/zpivchain.h
Labels: Cleanup, zPiv

#2012 [Backport] P2P open network connection, fix race condition
  src/net.cpp
Labels: Bug, P2P, Upstream

#2006 [Refactor] Masternode activeState on-demand
  src/activemasternode.cpp
  src/masternode-payments.cpp
  src/masternode-payments.h
  src/masternode.cpp
  src/masternode.h
  src/masternodeman.cpp
  src/masternodeman.h
  src/qt/pivx/mnmodel.cpp
  src/rpc/masternode.cpp
Labels: Masternode, Refactoring

#2009 [Trivial] constant functions in SaplingScriptPubKeyMan
  src/sapling/saplingscriptpubkeyman.cpp
  src/sapling/saplingscriptpubkeyman.h
Labels: Docs and Output, Sapling, Trivial

#2010 [BUG][GUI] Encrypted memo with transparent recipient address
  src/qt/pivx/send.cpp
Labels: Bug, GUI

#2015 [Net] Prevent un-necessary disconnections in version handshake
  src/spork.cpp
Labels: Network, P2P

#2011 [BUG][GUI] memo not reset after hitting reset button
  src/qt/pivx/sendmemodialog.cpp
Labels: Bug, GUI

#2013 [Wallet] Initial cleanup to the v1 transparent CreateTransaction flow.
  src/coincontrol.h
  src/wallet/wallet.cpp
Labels: Cleanup, Wallet

#2014 [RPC] redirect sendmany to shieldedsendmany when recipient is shielded
  src/sapling/sapling_operation.cpp
  src/sapling/sapling_operation.h
  src/wallet/rpcwallet.cpp
  test/functional/sapling_wallet.py
  test/functional/test_runner.py
Labels: RPC, Sapling

#2016 [Tests] Add --all option to test_runner for complete functional tests coverage
  test/functional/test_runner.py
Labels: Tests

#2023 [BUG] Fix lock order issue with CMMan::CheckAndRemove and CMPayments::CleanPaymentList
  src/masternode-payments.cpp
  src/masternode-payments.h
  src/masternodeman.cpp
  src/masternodeman.h
  src/qt/clientmodel.cpp
  src/rpc/masternode.cpp
Labels: Masternode, Refactoring

#2024 [BUG] GetLastPaid/SecondsSincePayment locking cs_main
  src/masternode.cpp
  src/masternode.h
  src/masternodeman.cpp
  src/masternodeman.h
  src/rpc/masternode.cpp
Labels: Masternode, Refactoring

#2017 [GUI] Guard shielded flows pre-v5 enforcement
  src/qt/pivx/receivewidget.cpp
  src/qt/pivx/send.cpp
  src/qt/transactionrecord.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: GUI

#2018 [BUG][RPC] Save collateral errors into proposals/budgets strInvalid
  src/budget/budgetmanager.cpp
  src/budget/budgetproposal.h
  src/budget/finalizedbudget.h
Labels: Budget/Proposal System, Bug, RPC

#2025 [GUI] Cold staking screen, hide memo entry button.
  src/qt/pivx/forms/sendmultirow.ui
  src/qt/pivx/sendmultirow.cpp
Labels: GUI

#2026 [Cleanup] [Trivial] Remove stale siphash.py file
  qa/rpc-tests/test_framework/siphash.py
Labels: Cleanup, Trivial

#2020 [Wallet] HD wallets automatic upgrade to sapling features.
  src/qt/pivx/topbar.cpp
  src/qt/pivx/topbar.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Wallet

#2028 [P2P] Add missing lock in CAddrMan::Clear()
  src/addrman.h
Labels: P2P, Upstream

#2029 [P2P] When clearing addrman clear mapInfo and mapAddr
  src/addrman.h
Labels: P2P, Upstream

#2027 [Sapling] Try to recover corruption of notes cache during send operation
  src/sapling/sapling_operation.cpp
  src/sapling/saplingscriptpubkeyman.cpp
  src/sapling/saplingscriptpubkeyman.h
  src/test/librust/sapling_rpc_wallet_tests.cpp
  src/wallet/wallet.cpp
Labels: Sapling, Wallet

#1927 [RPC] Add additional warning to dumpwallet result object
  src/wallet/rpcdump.cpp
  test/functional/wallet_dump.py
Labels: RPC, User Support

#2021 [GA] Reduce number of concurrent jobs
  .github/workflows/build-and-test.yml
Labels: Build System

#2031 [Masternodes] remove recursive lock in CMasternode::Status()
  src/masternode.h
Labels: Masternode

#2030 [GUI] Workaround to the MN MISSING/REMOVE labeling
  src/qt/pivx/mnmodel.cpp
Labels: GUI, Masternode

#2034 [SSPKM] Crash fix, external notes witness decrement
  src/sapling/saplingscriptpubkeyman.cpp
Labels: Bug, Sapling

#2035 [BUG][GUI] TxDetail dialog memo: plain text edit + copy button
  src/qt/pivx/forms/sendconfirmdialog.ui
  src/qt/pivx/res/css/style_dark.css
  src/qt/pivx/res/css/style_light.css
  src/qt/pivx/send.cpp
  src/qt/pivx/sendconfirmdialog.cpp
Labels: Bug, GUI

#2037 [GUI] Address generation error on locked wallets fix plus extra corrections.
  src/qt/pivx/receivewidget.cpp
  src/qt/pivx/send.cpp
  src/qt/pivx/send.h
  src/qt/pivx/settings/forms/settingsfaqwidget.ui
Labels: Bug, GUI

#2032 doc: Windows WSL build recommendation to temporarily disable Win32 PE support
  doc/build-windows.md
Labels: Build System, Upstream

#2036 [Build] Proper coverage for ppa, local, and snapcraft
  build-aux/snap/snapcraft.yaml
  params/Makefile.am
  params/install-params.sh
  src/util.cpp
Labels: Build System

#1928 [GUI] Double confirmation dialog for dumpwallet command.
  src/qt/pivx/settings/settingsconsolewidget.cpp
  src/qt/pivx/settings/settingsconsolewidget.h
  src/qt/pivx/settings/settingswidget.cpp
Labels: GUI, RPC, User Support

#2039 [GUI] Periodic make translate
  src/qt/locale/pivx_en.ts
  src/qt/pivxstrings.cpp
Labels: GUI

#2038 [Consensus] Set final enforcement height for V5 on Testnet
  src/chainparams.cpp
Labels: Consensus

#2040 [Build] Bump version to 4.9.99tr1
  configure.ac
  doc/man/pivx-cli.1
  doc/man/pivx-qt.1
  doc/man/pivx-tx.1
  doc/man/pivxd.1
Labels: Build System

#2041 [Build] CMake pivxd and unit tests: fixing missing MacOS framework.
  CMakeLists.txt
  src/test/CMakeLists.txt
Labels: Build System

#2046 [Sapling] Transparent inputs selection, fixing inverted order.
  src/sapling/sapling_operation.cpp
Labels: Bug, Sapling, Wallet

#2045 [TierTwo] Remove unneeded extra logging.
  src/tiertwo_networksync.cpp
Labels: Trivial

#2052 [Miner] Update block header's current version to v8
  src/miner.cpp
  src/primitives/block.h
Labels: Block Generation

#2047 [BUG][RPC] Fix check in wallet upgrade RPC
  src/wallet/rpcwallet.cpp
Labels: Bug, RPC

#2049 [RPC] Add nullifiers to listshieldedunspent output
  src/wallet/rpcwallet.cpp
  test/functional/sapling_wallet_listreceived.py
Labels: RPC

#2048 [Wallet] BugFix: automatic upgrade for unlocked wallet
  src/wallet/wallet.cpp
Labels: Bug, Wallet

#2059 [Test] Make rpc_ban unit test pass again
  src/test/rpc_tests.cpp
Labels: Bug, Tests, Upstream

#2055 [GUI] Transaction detail, scroll memo fix, starting from the top.
  src/qt/pivx/sendconfirmdialog.cpp
Labels: GUI, Sapling

#2054 [Net] Socks5 netbase back ports, less scary failures.
  src/netbase.cpp
Labels: P2P, Refactoring, Upstream

#2056 [Masternode] Encapsulate global and do not parse privkey redundantly everywhere.
  src/activemasternode.cpp
  src/activemasternode.h
  src/budget/budgetmanager.cpp
  src/masternode-payments.cpp
  src/masternodeman.h
  src/rpc/budget.cpp
  src/util.cpp
Labels: Masternode, Refactoring

#2058 [Cleanup] Removing unused DisconnectBlocks and ReprocessBlocks
  src/validation.cpp
  src/validation.h
Labels: Cleanup

#2060 [BUG][MN] Immediately detect forked masternodes
  src/activemasternode.cpp
  src/masternode.cpp
  src/masternode.h
Labels: Bug, Masternode

#2050 [RPC] redirect sendtoaddress to shieldedsendmany for shielded recipient
  src/wallet/rpcwallet.cpp
  test/functional/sapling_wallet.py
Labels: RPC

#2061 [Trivial] Add Zcash copyright statement
  COPYING
Labels: Trivial, Upstream ZCash

#2062 [Consensus] Max block space available for shielded txes
  src/consensus/consensus.h
  src/miner.cpp
  src/validation.cpp
  test/functional/sapling_fillblock.py
  test/functional/test_runner.py
Labels: Consensus, Sapling

#2033 [GUI][Trivial] Adjust CoinControl column widths for readability
  src/qt/coincontroldialog.cpp
Labels: GUI, Usability

#2064 [Script][BUG] Fix signature malleability for t inputs in Sapling txes
  src/kernel.cpp
  src/pivx-tx.cpp
  src/policy/policy.cpp
  src/primitives/transaction.h
  src/rpc/rawtransaction.cpp
  src/sapling/saplingscriptpubkeyman.cpp
  src/sapling/transaction_builder.cpp
  src/script/bitcoinconsensus.cpp
  src/script/interpreter.cpp
  src/script/interpreter.h
  src/script/sign.cpp
  src/script/sign.h
  src/test/data/sighash.json
  src/test/multisig_tests.cpp
  src/test/script_P2SH_tests.cpp
  src/test/script_tests.cpp
  src/test/sighash_tests.cpp
  src/test/transaction_tests.cpp
  src/validation.cpp
  src/wallet/wallet.cpp
  test/functional/sapling_malleable_sigs.py
  test/functional/test_framework/messages.py
  test/functional/test_runner.py
Labels: Bug, Consensus, Sapling, Tests

#2063 [Backport] Fix races for strMiscWarning and fLargeWork*Found
  CMakeLists.txt
  src/Makefile.am
  src/guiinterface.h
  src/init.cpp
  src/pivx-cli.cpp
  src/pivx-tx.cpp
  src/pivxd.cpp
  src/qt/clientmodel.cpp
  src/qt/pivx.cpp
  src/qt/pivx/pivxgui.cpp
  src/rpc/client.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/test/test_pivx.cpp
  src/timedata.cpp
  src/util.cpp
  src/util.h
  src/validation.cpp
  src/validation.h
  src/warnings.cpp
  src/warnings.h
Labels: GUI, Refactoring, Upstream

#2067 [Consensus][Validation] Reject outdated block version after v5 enforcement
  src/miner.cpp
  src/validation.cpp
  src/validation.h
Labels: Consensus, Validation

#2051 [Consensus] Bump TxVersion::SAPLING to 3
  src/consensus/upgrades.cpp
  src/init.cpp
  src/primitives/transaction.h
  src/sapling/sapling_validation.cpp
  src/sapling/sapling_validation.h
  src/wallet/wallet.cpp
Labels: Consensus, Sapling

#2065 [Wallet][Sapling] Dummy ECDSA sigs and zk-proofs during fee calculation loop
  src/sapling/sapling_operation.cpp
  src/sapling/transaction_builder.cpp
  src/sapling/transaction_builder.h
  src/uint256.h
  src/wallet/wallet.cpp
Labels: Sapling, Wallet, enhancement

#2066 [BUG][GUI] Receive widget: check typeRole before refreshing view
  src/qt/pivx/receivewidget.cpp
Labels: Bug, GUI

#2068 [Consensus] Budget: Fix instant killing of proposals
  src/budget/budgetproposal.cpp
  src/budget/budgetproposal.h
Labels: Budget/Proposal System, Consensus

#2069 [Consensus] Start new Testnet (v5)
  src/chainparams.cpp
  src/chainparamsbase.cpp
  src/miner.cpp
  src/validation.cpp
Labels: Consensus

#2073 [GUI] Dashboard, fix type filtering disappearance.
  src/qt/pivx/dashboardwidget.cpp
Labels: Bug, GUI

#2071 [Consensus] Update Spork keys for v5
  src/chainparams.cpp
  src/spork.cpp
Labels: Consensus

#2080 [BUG][Wallet] return unconfirmed balance for all spendable coins by default
  src/wallet/wallet.h
Labels: Bug, Wallet

#2081 [Tests] minor fixes for mining_pos_reorg.py
  test/functional/mining_pos_reorg.py
Labels: Cleanup, Tests

#2084 [BUG][Masternode] Miner not paying valid finalized budget if <20 active masternodes
  src/budget/budgetmanager.cpp
  src/masternode-payments.cpp
Labels: Bug, Consensus, Masternode

#2087 [Build] Unify header file extensions
  src/Makefile.am
  src/coins.h
  src/keystore.h
  src/rpc/rawtransaction.cpp
  src/sapling/address.cpp
  src/sapling/address.h
  src/sapling/incrementalmerkletree.cpp
  src/sapling/incrementalmerkletree.h
  src/sapling/note.cpp
  src/sapling/note.h
  src/sapling/noteencryption.cpp
  src/sapling/noteencryption.h
  src/sapling/proof.cpp
  src/sapling/proof.h
  src/sapling/sapling_transaction.h
  src/sapling/saplingscriptpubkeyman.h
  src/sapling/transaction_builder.h
  src/sapling/zip32.h
  src/test/coins_tests.cpp
  src/test/librust/merkletree_tests.cpp
  src/test/librust/noteencryption_tests.cpp
  src/test/librust/sapling_key_tests.cpp
  src/test/librust/sapling_keystore_tests.cpp
  src/test/librust/sapling_note_tests.cpp
  src/test/librust/sapling_rpc_wallet_tests.cpp
  src/test/librust/sapling_wallet_tests.cpp
  src/test/librust/utiltest.h
  src/test/librust/wallet_zkeys_tests.cpp
  src/validationinterface.h
  src/wallet/test/wallet_shielded_balances_tests.cpp
  src/wallet/wallet.h
Labels: Build System, Trivial

#2088 [RPC] Cleanup RPC help output
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/net.cpp
  src/wallet/rpcwallet.cpp
Labels: RPC, Trivial

#2083 [Core] Prevector Optimizations
  src/Makefile.bench.include
  src/bench/prevector.cpp
  src/bench/prevector_destructor.cpp
  src/prevector.h
Labels: Refactoring, Upstream

#2070 [GUI] coin-control: remove column checkbox extra white space in tree-mode
  src/qt/coincontroldialog.cpp
  src/qt/coincontroldialog.h
Labels: GUI, Usability

#2075 [GUI] Settings information, fix missing initial masternodes count value.
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/qt/pivx/settings/settingsinformationwidget.cpp
  src/qt/pivx/settings/settingsinformationwidget.h
Labels: Bug, GUI

#2086 [RPC] Use "shield" nomenclature instead of "shielded"
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/rpc/misc.cpp
  src/sapling/saplingscriptpubkeyman.cpp
  src/test/librust/sapling_rpc_wallet_tests.cpp
  src/wallet/rpcwallet.cpp
  test/functional/mining_pos_coldStaking.py
  test/functional/sapling_changeaddresses.py
  test/functional/sapling_fillblock.py
  test/functional/sapling_key_import_export.py
  test/functional/sapling_malleable_sigs.py
  test/functional/sapling_mempool.py
  test/functional/sapling_supply.py
  test/functional/sapling_wallet.py
  test/functional/sapling_wallet_anchorfork.py
  test/functional/sapling_wallet_listreceived.py
  test/functional/sapling_wallet_nullifiers.py
  test/functional/sapling_wallet_persistence.py
Labels: RPC, Refactoring

#2091 [Trivial][Refactor] Pass caught logic_error by reference in CreateSig
  src/script/sign.cpp
Labels: Refactoring, Trivial

#2094 [GUI] Hide shield all coins button.
  src/qt/pivx/send.cpp
Labels: GUI, Needs Backport

#2093 [Trivial][RPC] Drop 'ed' suffix from vShielded* in TxSaplingToJSON
  src/sapling/sapling_core_write.cpp
  test/functional/sapling_mempool.py
  test/functional/sapling_wallet.py
  test/functional/sapling_wallet_listreceived.py
Labels: Needs Backport, RPC, Trivial

#2095 [Doc] Main readme re-written, updated to the current project state.
  README.md
Labels: Docs and Output, Needs Backport

#2096 [GUI][BugFix] Duplicate transaction records.
  src/qt/transactionrecord.cpp
Labels: Bug, GUI, Needs Backport

#2098 [Trivial][GUI] coin control: Fixed column size in list-mode
  src/qt/coincontroldialog.cpp
Labels: GUI, Needs Backport, Trivial

#2104 [BUG][GUI] Don't return StakingOnlyUnlocked from WalletModel::sendCoins
  src/qt/walletmodel.cpp
Labels: Bug, GUI, Needs Backport

#2102 [BUG][GUI] Cache unconfirmed_balance only for transparent outs
  src/interface/wallet.cpp
Labels: Bug, GUI, Needs Backport

#2097 [RPC] Fix more RPC help output
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  test/functional/sapling_malleable_sigs.py
  test/functional/sapling_mempool.py
  test/functional/sapling_wallet.py
Labels: Needs Backport, RPC

#2103 [Startup] Do not block local peer port selection for Masternodes running over tor.
  src/activemasternode.cpp
  src/init.cpp
  test/functional/test_framework/test_framework.py
Labels: Bug, Masternode, Needs Backport

#2101 [Consensus] Max payment count for budget proposals
  src/budget/budgetmanager.cpp
  src/budget/budgetproposal.cpp
  src/budget/budgetproposal.h
  src/chainparams.cpp
  src/consensus/params.h
  src/rpc/budget.cpp
  src/test/budget_tests.cpp
  test/functional/rpc_budget.py
  test/functional/tiertwo_governance_sync_basic.py
Labels: Budget/Proposal System, Consensus, Needs Backport

#2108 [Policy] Set DEFAULT_SHIELDEDTXFEE_K to 100 (from 1000)
  src/policy/policy.cpp
  src/test/librust/sapling_wallet_tests.cpp
  src/test/librust/transaction_builder_tests.cpp
  src/validation.cpp
  src/validation.h
  test/functional/sapling_mempool.py
  test/functional/sapling_supply.py
  test/functional/sapling_wallet.py
  test/functional/sapling_wallet_listreceived.py
Labels: TX fees and policy

#2109 [Wallet] clear StakeableCoins before initializing
  src/wallet/wallet.cpp
Labels: Block Generation, Bug, Needs Backport

#2107 [Backport] 5.0 backports Part 2
  README.md
  src/activemasternode.cpp
  src/budget/budgetmanager.cpp
  src/budget/budgetproposal.cpp
  src/budget/budgetproposal.h
  src/chainparams.cpp
  src/consensus/params.h
  src/init.cpp
  src/interface/wallet.cpp
  src/policy/policy.cpp
  src/qt/coincontroldialog.cpp
  src/qt/pivx/send.cpp
  src/qt/transactionrecord.cpp
  src/qt/walletmodel.cpp
  src/rpc/budget.cpp
  src/sapling/sapling_core_write.cpp
  src/test/budget_tests.cpp
  src/test/librust/sapling_wallet_tests.cpp
  src/test/librust/transaction_builder_tests.cpp
  src/validation.cpp
  src/validation.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  test/functional/rpc_budget.py
  test/functional/sapling_malleable_sigs.py
  test/functional/sapling_mempool.py
  test/functional/sapling_supply.py
  test/functional/sapling_wallet.py
  test/functional/sapling_wallet_listreceived.py
  test/functional/test_framework/test_framework.py
  test/functional/tiertwo_governance_sync_basic.py
Labels: Backport

#2112 [Consensus] Set v5 enforcement height for mainnet
  src/chainparams.cpp
Labels: Consensus, Needs Backport

#2113 [Doc] RPC getrawtransaction and decoderawtransaction, sapling tx data.
  src/rpc/rawtransaction.cpp
Labels: Docs and Output, Needs Backport, RPC

#2116 [Test] Print error if shield diversified address is equal to the default address
  src/test/librust/wallet_zkeys_tests.cpp
Labels: Needs Backport, Tests

#2111 [BUG][GUI] coin-control dialog: more accurate "after fee" + fDust for shield recipient
  src/qt/coincontroldialog.cpp
  src/qt/coincontroldialog.h
Labels: Bug, GUI, Needs Backport, Refactoring

#2100 [GUI] Support for op_return proposal output records.
  src/qt/pivx/qtutils.cpp
  src/qt/pivx/txrow.cpp
  src/qt/pivx/txviewholder.cpp
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/rpc/budget.cpp
  src/wallet/wallet.h
Labels: GUI, Needs Backport
