Repository PIVX-Project/PIVX, pull requests merged in 2020-08, with the labels that each got.

#1700 Move coinbase & coinstake to P2PKH
  src/blocksignature.cpp
  src/blocksignature.h
  src/main.cpp
  src/miner.cpp
  src/stakeinput.cpp
  src/stakeinput.h
  src/test/main_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/zpiv/zpos.h
  test/functional/mining_v5_upgrade.py
  test/functional/rpc_blockchain.py
  test/functional/test_runner.py
Labels: Block Generation, Refactoring, Validation

#1781 [Wallet] Acquire cs_main lock before cs_wallet during wallet initialization
  src/wallet/wallet.cpp
Labels: Upstream, Wallet

#1780 [Net] cs_vSend-cs_main deadlock detection fixed.
  src/addrman.h
  src/main.cpp
  src/net.cpp
  src/net.h
Labels: P2P, Refactoring, Upstream

#1775 [Core] Remove BIP30 check
  src/chain.h
  src/main.cpp
  test/functional/feature_block.py
Labels: Upstream, Validation

#1782 [GUI] Start masternodes polling timer only when is needed.
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/qt/pivx/settings/settingsinformationwidget.cpp
  src/qt/pivx/settings/settingsinformationwidget.h
  src/qt/rpcconsole.cpp
Labels: GUI

#1768 [Core] Use SipHash-2-4 for various non-cryptographic hashes
  src/arith_uint256.cpp
  src/arith_uint256.h
  src/blob_uint256.cpp
  src/blob_uint256.h
  src/coins.cpp
  src/coins.h
  src/hash.cpp
  src/hash.h
  src/main.cpp
  src/test/hash_tests.cpp
  src/txmempool.h
  src/uint256.cpp
  src/uint256.h
Labels: UTXO DBs and Indexes, Upstream

#1783 [Wallet] Do not try to resend transactions if the node is importing or in IBD
  src/main.cpp
Labels: Wallet

#1771 [Core] Use SipHash for node eviction
  qa/rpc-tests/test_framework/siphash.py
  src/coins.cpp
  src/coins.h
  src/hash.cpp
  src/hash.h
  src/main.cpp
  src/net.cpp
  src/net.h
  src/test/hash_tests.cpp
Labels: P2P, Tests, Upstream

#1666 Base work for the Sapling signatureHash
  src/kernel.cpp
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/pivx-tx.cpp
  src/policy/policy.cpp
  src/rpc/rawtransaction.cpp
  src/script/interpreter.cpp
  src/script/interpreter.h
  src/script/sigcache.h
  src/script/sign.cpp
  src/script/sign.h
  src/test/DoS_tests.cpp
  src/test/main_tests.cpp
  src/test/multisig_tests.cpp
  src/test/script_P2SH_tests.cpp
  src/test/script_tests.cpp
  src/test/sighash_tests.cpp
  src/test/transaction_tests.cpp
  src/txmempool.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet_ismine.cpp
  src/wallet/wallet_zerocoin.cpp
  test/functional/wallet_txn_clone.py
Labels: RPC, Refactoring, Upstream, Wallet

#1721 [Validation] Reduce cs_main locks during ConnectTip/SyncWithWallets
  src/main.cpp
  src/test/accounting_tests.cpp
  src/validationinterface.cpp
  src/validationinterface.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_zerocoin.cpp
  src/zmq/zmqnotificationinterface.cpp
  src/zmq/zmqnotificationinterface.h
  src/zpiv/zpivwallet.cpp
  src/zpivchain.cpp
Labels: Refactoring, Upstream

#1750 [Trivial] openssl.org dependency download link changed
  depends/packages/openssl.mk
Labels: Build System

#1770 [Build] Bump minimum libc to 2.17 for release binaries
  configure.ac
  contrib/devtools/symbol-check.py
  src/compat/glibc_compat.cpp
Labels: Build System

#1753 [Trivial] [RPC] Fix listcoldutxos help text
  src/wallet/rpcwallet.cpp
Labels: Docs and Output, NoFunctionalChanges, RPC, Trivial

#1790 [Build] Fix glibc compat
  src/compat/glibc_compat.cpp
Labels: Build System

#1774 [Core] Alter assumptions in CCoinsViewCache::BatchWrite
  src/coins.cpp
  src/test/coins_tests.cpp
Labels: UTXO DBs and Indexes, Upstream

#1777 [Core] ModifyNewCoins saves database lookups
  src/coins.cpp
  src/coins.h
  src/main.cpp
  src/test/coins_tests.cpp
Labels: UTXO DBs and Indexes, Upstream

#1755 [wallet] List COutput solvability + wallet_ismine refactoring.
  CMakeLists.txt
  src/Makefile.am
  src/qt/walletmodel.cpp
  src/rpc/rawtransaction.cpp
  src/script/ismine.cpp
  src/script/ismine.h
  src/test/multisig_tests.cpp
  src/test/script_P2SH_tests.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Upstream, Wallet

#1759 [Wallet] AvailableCoins remove duplicated watchonly config argument.
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  test/functional/wallet_basic.py
Labels: Wallet

#1785 lock cs_main for Misbehaving
  src/main.cpp
  src/main.h
  src/masternode-budget.cpp
  src/masternode-payments.cpp
  src/masternodeman.cpp
  src/test/DoS_tests.cpp
Labels: Bug, Needs Backport

#1796 [BUG] Properly copy fCoinStake memeber between CTxInUndo and CCoins
  src/main.cpp
  src/undo.h
Labels: Bug, Needs Backport, UTXO DBs and Indexes

#1799 [Core] Remove UTXO cache entries when the tx they were added for is removed
  src/coins.cpp
  src/coins.h
  src/main.cpp
  src/txmempool.cpp
  src/txmempool.h
Labels: Mempool, Upstream

#1797 [Refactoring] Break circular dependency main ↔ txdb
  src/coins.cpp
  src/coins.h
  src/legacy/validation_zerocoin_legacy.h
  src/main.cpp
  src/rpc/blockchain.cpp
  src/test/coins_tests.cpp
  src/test/netbase_tests.cpp
  src/txdb.cpp
  src/txdb.h
Labels: REST, Refactoring, UTXO DBs and Indexes, Upstream

#1795 [Core] Use unordered_map for CCoinsMap and fix empty vectors in streams
  src/coins.h
  src/memusage.h
  src/streams.h
Labels: UTXO DBs and Indexes, Upstream, Util / log / libs

#1776 [Model] TransactionRecord decomposeTransaction refactoring
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
Labels: GUI, Needs Backport

#1800 [P2P] Improve AlreadyHave
  src/main.cpp
Labels: P2P, Upstream

#1792 [Build] allow for empty RUST_TARGET in offline builds
  configure.ac
  src/Makefile.am
Labels: Build System

#1805 [BUG][GUI] Don't append cold-stake records twice
  src/qt/transactionrecord.cpp
Labels: Bug, GUI, Needs Backport

#1794 [Build] Use syslibs for nightly snap builds
  build-aux/snap/snapcraft.yaml
Labels: Build System

#1760 [wallet] AvailableCoins code readability improved
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Refactoring, Wallet

#1787 Improve usage of fee estimation code
  src/main.h
  src/policy/fees.cpp
  src/policy/fees.h
  src/policy/policy.h
  src/qt/coincontroldialog.cpp
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/rpc/mining.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/test/policyestimator_tests.cpp
  src/txmempool.cpp
  src/txmempool.h
  src/wallet/wallet.cpp
  test/functional/feature_fee_estimation.py
Labels: TX fees and policy, Tests, Upstream, Wallet

#1725 [Backport] mempool score index.
  src/main.cpp
  src/rpc/blockchain.cpp
  src/test/mempool_tests.cpp
  src/test/test_pivx.cpp
  src/test/test_pivx.h
  src/txmempool.cpp
  src/txmempool.h
Labels: Mempool, Needs Release Notes, Upstream

#1793 [Core] Safer modify new coins
  src/coins.cpp
  src/main.cpp
  src/test/coins_tests.cpp
Labels: Tests, UTXO DBs and Indexes, Upstream

#1807 [Backport] 4.2.1 backports
  depends/packages/openssl.mk
  src/addrman.h
  src/chain.h
  src/coins.cpp
  src/coins.h
  src/main.cpp
  src/main.h
  src/masternode-budget.cpp
  src/masternode-payments.cpp
  src/masternode.cpp
  src/masternode.h
  src/masternodeman.cpp
  src/miner.cpp
  src/net.cpp
  src/net.h
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/test/DoS_tests.cpp
  src/txmempool.cpp
  src/undo.h
  src/wallet/wallet.cpp
  test/functional/feature_block.py
Labels: Backport

#1773 [Core] per-txout model preparation
  doc/release-notes.md
  src/coins.cpp
  src/coins.h
  src/dbwrapper.h
  src/hash.cpp
  src/hash.h
  src/main.cpp
  src/rest.cpp
  src/rpc/blockchain.cpp
  src/test/coins_tests.cpp
  src/test/hash_tests.cpp
  src/test/transaction_tests.cpp
  src/txdb.cpp
  src/txdb.h
  src/undo.h
  test/functional/rpc_blockchain.py
Labels: Resource usage, UTXO DBs and Indexes, Upstream

#1804 [Core] Use std::unordered_{map,set} (C++11) instead of boost::unordered_*
  src/main.h
  src/memusage.h
Labels: Refactoring, Upstream

#1808 [Tests][Trivial] Remove mining in rpc_deprecated test
  test/functional/rpc_deprecated.py
  test/functional/test_runner.py
Labels: Tests, Trivial

#1809 [Miner] decouple zPIV duplicated serials checks from CreateNewBlock
  src/miner.cpp
Labels: Refactoring

#1811 [Wallet][Refactoring] wallet/init refactoring backports
  src/chainparamsbase.cpp
  src/chainparamsbase.h
  src/init.cpp
  src/init.h
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/miner.h
  src/net.cpp
  src/net.h
  src/pivx-cli.cpp
  src/policy/policy.cpp
  src/policy/policy.h
  src/qt/intro.cpp
  src/qt/pivx.cpp
  src/qt/pivx/settings/settingsinformationwidget.cpp
  src/qt/pivx/topbar.cpp
  src/qt/rpcconsole.cpp
  src/rpc/misc.cpp
  src/script/standard.cpp
  src/script/standard.h
  src/util.cpp
  src/util.h
  src/wallet/db.cpp
  src/wallet/db.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_zerocoin.cpp
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
  src/zpiv/zpivtracker.cpp
Labels: Cleanup, Refactoring, Upstream, Wallet

#1812 [P2P] Begin Network Encapsulation
  CMakeLists.txt
  src/Makefile.am
  src/activemasternode.cpp
  src/addrdb.cpp
  src/addrdb.h
  src/addrman.cpp
  src/addrman.h
  src/init.cpp
  src/main.cpp
  src/main.h
  src/masternode-budget.cpp
  src/masternode-payments.cpp
  src/masternode-sync.cpp
  src/masternode-sync.h
  src/masternode.cpp
  src/masternodeman.cpp
  src/merkleblock.h
  src/miner.cpp
  src/net.cpp
  src/net.h
  src/netaddress.cpp
  src/netbase.cpp
  src/netbase.h
  src/qt/bantablemodel.cpp
  src/qt/clientmodel.cpp
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/peertablemodel.cpp
  src/qt/peertablemodel.h
  src/qt/rpcconsole.cpp
  src/qt/walletmodel.cpp
  src/rpc/blockchain.cpp
  src/rpc/budget.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/net.cpp
  src/rpc/protocol.h
  src/rpc/rawtransaction.cpp
  src/spork.cpp
  src/swifttx.cpp
  src/test/DoS_tests.cpp
  src/test/addrman_tests.cpp
  src/test/miner_tests.cpp
  src/test/net_tests.cpp
  src/test/test_pivx.cpp
  src/test/test_pivx.h
  src/threadinterrupt.cpp
  src/threadinterrupt.h
  src/validationinterface.cpp
  src/validationinterface.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/wallet_zerocoin.cpp
Labels: Network, P2P, Upstream

#1813 [CMake] Define MAC_OSX for cmake builds on macOS
  CMakeLists.txt
Labels: Build System, Trivial
