Repository PIVX-Project/PIVX, pull requests merged in 2020-01, with the labels that each got.

#1184 [GUI][Trivial] Minor edits to written content
  src/qt/guiutil.cpp
  src/qt/pivx/addresseswidget.cpp
  src/qt/pivx/coldstakingwidget.cpp
  src/qt/pivx/forms/addresseswidget.ui
  src/qt/pivx/forms/coldstakingwidget.ui
  src/qt/pivx/forms/masternodeswidget.ui
  src/qt/pivx/forms/masternodewizarddialog.ui
  src/qt/pivx/forms/mninfodialog.ui
  src/qt/pivx/forms/privacywidget.ui
  src/qt/pivx/mninfodialog.cpp
  src/qt/pivx/privacywidget.cpp
  src/qt/pivx/receivewidget.cpp
  src/qt/pivx/requestdialog.cpp
  src/qt/pivx/send.cpp
  src/qt/pivx/sendchangeaddressdialog.cpp
  src/qt/pivx/sendmultirow.cpp
  src/qt/pivx/settings/forms/settingsfaqwidget.ui
  src/qt/pivx/settings/forms/settingsmultisendwidget.ui
  src/qt/pivx/settings/settingsbackupwallet.cpp
  src/qt/pivx/settings/settingsbittoolwidget.cpp
  src/qt/pivx/settings/settingsinformationwidget.cpp
  src/qt/pivx/settings/settingsmultisenddialog.cpp
  src/qt/pivx/settings/settingssignmessagewidgets.cpp
  src/qt/transactiontablemodel.cpp
Labels: GUI, NoFunctionalChanges, Trivial

#1233 [Trivial] Remove spammy log in in StakeV1
  src/kernel.cpp
Labels: Block Generation, Trivial

#1224 [Trivial][GUI] Minor changes within 4.0 wallet FAQ
  src/qt/pivx/settings/forms/settingsfaqwidget.ui
Labels: GUI, NoFunctionalChanges, Trivial

#1228 [GUI] Adding capability to decrease the screen size for small screens.
  src/qt/pivx/forms/navmenuwidget.ui
  src/qt/pivx/navmenuwidget.cpp
  src/qt/pivx/pivxgui.cpp
Labels: GUI

#1234 [Cleanup] Remove precomputing
  src/init.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Cleanup

#1207 [Doc] Update build-unix.md file
  doc/build-unix.md
Labels: Docs and Output, Documentation

#1229 [Wallet] Graceful shutdown in the unlock corrupted wallet.
  src/crypter.cpp
Labels: Wallet

#1211 [GUI] MN creation wizard, fail event detailing the failure cause.
  src/qt/pivx/coldstakingwidget.cpp
  src/qt/pivx/guitransactionsutils.cpp
  src/qt/pivx/guitransactionsutils.h
  src/qt/pivx/masternodewizarddialog.cpp
  src/qt/pivx/masternodewizarddialog.h
  src/qt/pivx/pwidget.h
  src/qt/pivx/send.cpp
Labels: GUI, Masternode

#1243 [Core][Trivial] Don't log missing MNs during CleanAndRemove
  src/masternode-budget.cpp
  src/masternode-budget.h
  src/messagesigner.cpp
  src/messagesigner.h
  src/rpc/budget.cpp
Labels: Cleanup, Masternode

#1221 [GUI] Masternodes start all and start missing flows implemented.
  src/qt/pivx/forms/masternodeswidget.ui
  src/qt/pivx/masternodeswidget.cpp
  src/qt/pivx/masternodeswidget.h
  src/qt/pivx/mnmodel.cpp
  src/qt/pivx/mnmodel.h
Labels: GUI, Masternode

#1240 [Model][Wallet][Performance] Several changes in txRecord updateStatus.
  src/qt/transactionrecord.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: GUI, Wallet

#1250 [GUI] Every MN action checking tier two synced.
  src/qt/pivx/masternodeswidget.cpp
  src/qt/pivx/masternodeswidget.h
  src/qt/pivx/mnmodel.cpp
  src/qt/pivx/mnmodel.h
Labels: GUI, Masternode

#1252 [Trivial] Log log2_work value with 16 decimals
  src/main.cpp
Labels: Trivial

#1253 [Qt] Initialize isLoading to false for CS view
  src/qt/pivx/coldstakingwidget.cpp
Labels: GUI

#1251 [RPC] Notate all account stuff as deprecated
  src/rpc/misc.cpp
  src/rpc/rawtransaction.cpp
  src/wallet/rpcwallet.cpp
Labels: Needs Release Notes, NoFunctionalChanges, RPC

#1261 [Bug][GUI] Double counted delegated balance.
  src/qt/pivx/topbar.cpp
Labels: Bug, High Priority

#1267 [Qt][Bug] Load the most recent instead of the first transactions
  src/qt/transactiontablemodel.cpp
Labels: Bug, GUI

#1263 [GUI] P2CS transaction divided in two types for visual accuracy.
  src/qt/pivx/dashboardwidget.cpp
  src/qt/pivx/txrow.cpp
  src/qt/transactionfilterproxy.cpp
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
Labels: GUI

#1264 [Wallet] Don't add P2CS automatically to GetLockedCredit
  src/wallet/wallet.cpp
Labels: Bug, Wallet

#1265 [GUI] Connect P2CSUnlockOwner and P2CSUnlockStaker records to the model
  src/qt/pivx/txrow.cpp
  src/qt/transactiontablemodel.cpp
Labels: Bug, GUI

#1268 [GUI] Display latest block number in the top bar
  src/qt/pivx/topbar.cpp
Labels: GUI

#1273 [Core] Update checkpoints for first v7 block
  src/chainparams.cpp
Labels: Validation

#1272 [Trivial] Update copyright headers for 4.0.2
  COPYING
  configure.ac
  src/init.cpp
  src/kernel.cpp
  src/main.cpp
  src/main.h
  src/masternode-budget.cpp
  src/masternode-budget.h
  src/messagesigner.cpp
  src/messagesigner.h
  src/miner.cpp
  src/miner.h
  src/qt/addresstablemodel.cpp
  src/qt/coincontroldialog.cpp
  src/qt/coincontroldialog.h
  src/qt/pivx/addresseswidget.cpp
  src/qt/pivx/coldstakingwidget.cpp
  src/qt/pivx/dashboardwidget.cpp
  src/qt/pivx/masternodeswidget.cpp
  src/qt/pivx/masternodeswidget.h
  src/qt/pivx/mnmodel.cpp
  src/qt/pivx/mnmodel.h
  src/qt/pivx/navmenuwidget.cpp
  src/qt/pivx/navmenuwidget.h
  src/qt/pivx/pivxgui.cpp
  src/qt/pivx/privacywidget.cpp
  src/qt/pivx/receivewidget.cpp
  src/qt/pivx/send.cpp
  src/qt/pivx/settings/settingsbittoolwidget.cpp
  src/qt/pivx/settings/settingsmultisendwidget.cpp
  src/qt/pivx/topbar.cpp
  src/qt/pivx/topbar.h
  src/qt/pivx/txrow.cpp
  src/qt/transactionfilterproxy.cpp
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/qt/zpivcontroldialog.cpp
  src/qt/zpivcontroldialog.h
  src/rpc/budget.cpp
  src/rpc/client.cpp
  src/rpc/misc.cpp
  src/rpc/rawtransaction.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/test/rpc_wallet_tests.cpp
  src/util.cpp
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
  src/zpiv/witness.cpp
  src/zpiv/witness.h
  src/zpiv/zpivtracker.cpp
  src/zpiv/zpivtracker.h
  test/functional/rpc_bip38.py
Labels: NoFunctionalChanges, Trivial

#1274 [RPC] Remove extra PoW rounds in 'generate'
  src/rpc/mining.cpp
Labels: Block Generation, Bug, RPC, Tests

#1279 [GUI] Transaction record cold staking fixes.
  src/qt/transactionrecord.cpp
Labels: Bug, GUI

#1284 [GUI] Min window size decreased to 1100px
  src/qt/pivx/pivxgui.cpp
Labels: GUI, enhancement

#1254 [Cleanup] ZLNP code removed entirely.
  CMakeLists.txt
  src/Makefile.am
  src/concurrentqueue.h
  src/genwit.cpp
  src/genwit.h
  src/init.cpp
  src/kernel.cpp
  src/lightzpivthread.cpp
  src/lightzpivthread.h
  src/main.cpp
  src/main.h
  src/masternode-sync.h
  src/net.cpp
  src/protocol.cpp
  src/protocol.h
  src/qt/guiutil.cpp
  src/rpc/misc.cpp
  src/zpiv/accumulators.cpp
  src/zpiv/accumulators.h
Labels: Cleanup

#1286 [GUI] Set width and default minimum scrollbar height
  src/qt/pivx/res/css/style_dark.css
  src/qt/pivx/res/css/style_light.css
Labels: GUI, Trivial, Usability

#1289 [GUI] Windowtitle parameter fix
  src/qt/pivx/pivxgui.cpp
Labels: Bug, GUI

#1282 [Trivial][Cleanup] Add IsRegTestNet() function in chainparams
  src/activemasternode.cpp
  src/chainparams.h
  src/kernel.cpp
  src/main.cpp
  src/masternode-sync.cpp
  src/masternode.cpp
  src/masternodeman.cpp
  src/net.cpp
  src/pow.cpp
  src/qt/walletmodel.cpp
  src/rpc/rawtransaction.cpp
  src/stakeinput.cpp
  src/timedata.cpp
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/zpiv/accumulators.cpp
Labels: Cleanup, Trivial

#1298 [Model][Performance] Unnecessary double cs_wallet and cs_main lock.
  src/qt/transactiontablemodel.cpp
Labels: GUI, Wallet

#1281 [Trivial][Cleanup] Remove extra checks before GetBlocksToMaturity
  src/wallet/wallet.cpp
Labels: Cleanup, Trivial

#1295 [Tests] Set '-staking' disabled by default on RegTest
  src/init.cpp
  test/functional/test_framework/util.py
Labels: Tests

#1316 [Trivial] fix typo "recomended" in sendcustomfee dialog
  src/qt/pivx/forms/sendcustomfeedialog.ui
Labels: GUI, Trivial
