Repository PIVX-Project/PIVX, pull requests merged in 2020-02, with the labels that each got.

#1319 [Refactor] Move CDiskTxPos/CBlockUndo to txdb.h/undo.h respectively
  src/main.h
  src/txdb.h
  src/undo.h
Labels: NoFunctionalChanges, Refactoring

#1308 [zPIV] Public coin, a super for-each removed.
  src/libzerocoin/Coin.cpp
Labels: Cleanup, zPiv

#1300 [Wallet] Add function CMerkleTx::IsInMainChainImmature
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Wallet

#1320 [Refactor] Move transaction checks out to consensus/tx_verify.cpp
  CMakeLists.txt
  src/Makefile.am
  src/consensus/tx_verify.cpp
  src/consensus/tx_verify.h
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/test/script_P2SH_tests.cpp
  src/test/sighash_tests.cpp
  src/test/transaction_tests.cpp
  src/wallet/wallet.h
Labels: NoFunctionalChanges, Refactoring

#1297 [GUI] Restore address list when switching panes in CSwidget
  src/qt/pivx/coldstakingwidget.cpp
  src/qt/pivx/coldstakingwidget.h
Labels: Bug, GUI

#1299 [Trivial][Regtest][RPC] generate call failing properly when the wallet is locked
  src/rpc/mining.cpp
Labels: RPC, Tests

#1307 [Net] Do not launch the clock warning dialog like crazy.
  src/net.cpp
Labels: GUI, Network

#1325 Add WITH_LOCK macro: run code while locking a mutex.
  src/sync.h
Labels: Upstream

#1330 [Cleanup] Remove stale UNITTEST network
  src/chainparams.cpp
  src/chainparams.h
  src/chainparamsbase.cpp
  src/chainparamsbase.h
  src/test/base58_tests.cpp
  src/test/test_pivx.cpp
Labels: Cleanup, Refactoring

#1331 [Core] CheckColdStakeFreeOutput: skip SPORK checks if mnsync incomplete
  src/main.cpp
Labels: Bug, Validation

#1324 [Build] Remove Windows 32 bit build.
  .travis.yml
  .travis/test_04_install.sh
  contrib/devtools/test-security-check.py
  contrib/gitian-descriptors/gitian-win.yml
  depends/README.md
  doc/build-windows.md
  doc/release-process.md
Labels: Build System, Upstream

#1333 [Backport] Wait locking for genesis connection.
  src/init.cpp
  src/main.cpp
  src/test/test_pivx.cpp
Labels: Upstream

#1249 [Script] Optimize and Cleanup CScript::FindAndDelete
  src/script/script.h
  src/test/script_tests.cpp
Labels: Upstream, Validation

#1340 [Cleanup] Remove MineBlocksOnDemand function in chainparams
  src/chainparams.cpp
  src/chainparams.h
  src/miner.cpp
  src/pow.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/wallet/wallet_zerocoin.cpp
Labels: Cleanup, Trivial

#1339 [GUI] Tor topbar icon status.
  src/Makefile.qt.include
  src/qt/pivx.qrc
  src/qt/pivx/forms/topbar.ui
  src/qt/pivx/res/css/style_dark.css
  src/qt/pivx/res/css/style_light.css
  src/qt/pivx/res/img/ic-check-tor-off.svg
  src/qt/pivx/res/img/ic-check-tor.svg
  src/qt/pivx/topbar.cpp
  src/qt/pivx/topbar.h
Labels: GUI

#1306 [GUI] Hide privacy widget when the wallet has no zPIV balance
  src/qt/pivx/navmenuwidget.cpp
  src/qt/pivx/pivxgui.cpp
Labels: GUI

#1323 [Qt] Hide zPIV balances when they are zero
  src/qt/pivx/forms/topbar.ui
  src/qt/pivx/topbar.cpp
Labels: GUI

#1328 [Refactor] Introduce Consensus namespace
  CMakeLists.txt
  src/Makefile.am
  src/chainparams.cpp
  src/chainparams.h
  src/consensus/params.h
  src/init.cpp
  src/kernel.cpp
  src/main.cpp
  src/qt/transactiondesc.cpp
  src/qt/transactionrecord.cpp
  src/txmempool.cpp
  src/wallet/wallet.cpp
Labels: Refactoring

#1343 [Bug] nStakeSplitThreshold: division by zero
  src/stakeinput.cpp
  src/wallet/rpcwallet.cpp
Labels: Block Generation, Bug, RPC, Wallet

#1341 [Refactor] ChainParams::consensus - Part 1
  src/amount.h
  src/chain.h
  src/chainparams.cpp
  src/chainparams.h
  src/consensus/params.h
  src/consensus/tx_verify.cpp
  src/kernel.cpp
  src/main.cpp
  src/masternode-budget.cpp
  src/masternode-payments.cpp
  src/miner.cpp
  src/pow.cpp
  src/qt/bitcoinunits.cpp
  src/qt/blockexplorer.cpp
  src/qt/transactiondesc.cpp
  src/qt/transactionrecord.cpp
  src/rpc/blockchain.cpp
  src/rpc/mining.cpp
  src/rpc/server.cpp
  src/test/main_tests.cpp
  src/txdb.cpp
  src/txmempool.cpp
  src/wallet/rpcdump.cpp
  src/wallet/wallet.cpp
Labels: Consensus, Refactoring

#1352 [Cleanup] Remove unused blockexplorer GUI files
  src/Makefile.qt.include
  src/qt/CMakeLists.txt
  src/qt/blockexplorer.cpp
  src/qt/blockexplorer.h
  src/qt/forms/blockexplorer.ui
Labels: Cleanup

#1338 [Core] CBlockIndex cleanup - Bump client version to 4.0.99.1
  configure.ac
  doc/release-notes.md
  src/chain.cpp
  src/chain.h
  src/init.cpp
  src/kernel.cpp
  src/kernel.h
  src/main.cpp
  src/main.h
  src/primitives/block.h
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/txdb.cpp
  src/wallet/rpcwallet.cpp
Labels: Cleanup, Refactoring

#1351 [Build] Bump minimum required Qt version to 5.5.1
  .travis.yml
  build-aux/m4/bitcoin_qt.m4
  doc/release-notes.md
  src/qt/CMakeLists.txt
  src/qt/macdockiconhandler.mm
  src/qt/pivx.cpp
  src/qt/pivx/settings/settingssignmessagewidgets.cpp
Labels: Build System

#1354 [Trivial] Minor showed amount fix
  src/qt/pivx/forms/masternodewizarddialog.ui
Labels: GUI, Trivial

#1335 Inlining sync.cpp with latest upstream, first step.
  CMakeLists.txt
  src/Makefile.am
  src/httpserver.cpp
  src/init.cpp
  src/main.cpp
  src/main.h
  src/miner.cpp
  src/obfuscation.cpp
  src/sync.cpp
  src/sync.h
  src/util.cpp
  src/util.h
  src/util/threadnames.cpp
  src/util/threadnames.h
  src/wallet/walletdb.cpp
Labels: Cleanup, Upstream

#1342 [Refactor] Move zerocoin checks out of main
  CMakeLists.txt
  src/Makefile.am
  src/consensus/tx_verify.cpp
  src/consensus/zerocoin_verify.cpp
  src/consensus/zerocoin_verify.h
  src/init.cpp
  src/main.cpp
  src/main.h
  src/test/zerocoin_denomination_tests.cpp
  src/test/zerocoin_transactions_tests.cpp
  src/wallet/wallet_zerocoin.cpp
Labels: Cleanup, Refactoring

#1344 [Refactor] ChainParams::consensus - Part 2
  src/chain.h
  src/chainparams.cpp
  src/chainparams.h
  src/consensus/consensus.h
  src/consensus/params.h
  src/consensus/tx_verify.cpp
  src/consensus/zerocoin_verify.cpp
  src/init.cpp
  src/kernel.cpp
  src/main.cpp
  src/masternode-budget.cpp
  src/masternode-payments.cpp
  src/miner.cpp
  src/obfuscation.cpp
  src/obfuscation.h
  src/pow.cpp
  src/qt/governancepage.cpp
  src/qt/pivx/privacywidget.cpp
  src/qt/pivx/send.cpp
  src/qt/walletmodel.cpp
  src/qt/zpivcontroldialog.cpp
  src/rpc/blockchain.cpp
  src/rpc/budget.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/spork.cpp
  src/test/budget_tests.cpp
  src/test/zerocoin_transactions_tests.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet_zerocoin.cpp
  src/zpiv/zpivmodule.cpp
  src/zpiv/zpivtracker.cpp
  src/zpiv/zpivwallet.cpp
  src/zpiv/zpos.cpp
  src/zpivchain.cpp
Labels: Consensus, Refactoring
