Repository PIVX-Project/PIVX, pull requests merged in 2020-03, with the labels that each got.

#1345 [Wallet][RPC][GUI] nStakeSplitThreshold as CAmount
  doc/release-notes.md
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/qt/pivx/res/css/style_dark.css
  src/qt/pivx/res/css/style_light.css
  src/qt/pivx/settings/forms/settingswalletoptionswidget.ui
  src/stakeinput.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
Labels: GUI, RPC, Wallet

#1356 [Wallet][GUI] Set default stake-split threshold to 500
  doc/release-notes.md
  src/qt/optionsmodel.cpp
  src/wallet/wallet.h
Labels: GUI, Wallet

#1357 [Qt] Replace deprecated Qt methods
  src/qt/addresstablemodel.cpp
  src/qt/bantablemodel.cpp
  src/qt/paymentserver.cpp
  src/qt/peertablemodel.cpp
  src/qt/recentrequeststablemodel.cpp
  src/qt/transactiontablemodel.cpp
Labels: GUI, Refactoring

#1359 [Chain][Bug] Fix mapZerocoinSupply recalculation
  src/consensus/zerocoin_verify.cpp
  src/consensus/zerocoin_verify.h
  src/init.cpp
Labels: Bug, Consensus, zPiv

#1336 Sync Upgrades, part 2.
  src/Makefile.am
  src/Makefile.test.include
  src/main.cpp
  src/rpc/rawtransaction.cpp
  src/sync.cpp
  src/sync.h
  src/test/sync_tests.cpp
  src/util/macros.h
Labels: Refactoring, Upstream

#1358 [Build] Cleanup Qt m4 file
  build-aux/m4/bitcoin_qt.m4
Labels: Build System, Cleanup

#1360 [Net] Split DNS resolving functionality out of net structures
  src/init.cpp
  src/masternodeman.cpp
  src/net.cpp
  src/netbase.cpp
  src/netbase.h
  src/rpc/masternode.cpp
Labels: Network, P2P, Upstream

#1337 Sync upgrade, part 3
  src/activemasternode.h
  src/addrman.h
  src/alert.cpp
  src/alert.h
  src/init.cpp
  src/keystore.h
  src/main.cpp
  src/main.h
  src/masternode-budget.cpp
  src/masternode-budget.h
  src/masternode-payments.cpp
  src/masternode-payments.h
  src/masternode.h
  src/masternodeman.h
  src/miner.cpp
  src/net.cpp
  src/net.h
  src/netbase.cpp
  src/rpc/mining.cpp
  src/rpc/server.cpp
  src/spork.h
  src/sync.cpp
  src/sync.h
  src/test/util_tests.cpp
  src/timedata.cpp
  src/txmempool.h
  src/util.cpp
  src/wallet/db.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.h
Labels: Refactoring, Upstream

#1361 [GUI] Dashboard, include owner cold stakes in the chart.
  src/qt/transactionfilterproxy.cpp
Labels: GUI

#1363 [Net] Banlist updates
  src/net.cpp
Labels: Network, P2P, Upstream

#1377 [Trivial] Fix typo in settingsbittoolwidget.cpp
  src/qt/pivx/settings/settingsbittoolwidget.cpp
Labels: GUI, Trivial

#1382 [Wallet] Don't initialize zpivwallet on first run
  src/crypter.cpp
  src/init.cpp
  src/zpiv/zpivwallet.cpp
Labels: Wallet

#1389 [GUI] MasternodeWidget-Wizard bugfixes
  src/qt/pivx/masternodeswidget.cpp
  src/qt/pivx/masternodewizarddialog.cpp
  src/qt/pivx/mninfodialog.cpp
  src/qt/pivx/mnmodel.cpp
  src/qt/pivx/mnrow.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: Bug, GUI, Masternode

#1327 [Wallet] HD Wallet - v2.
  CMakeLists.txt
  Makefile.am
  contrib/devtools/lint-whitespace.sh
  doc/release-notes.md
  src/Makefile.am
  src/Makefile.test.include
  src/base58.h
  src/crypter.h
  src/init.cpp
  src/key.cpp
  src/key.h
  src/key_io.cpp
  src/key_io.h
  src/keystore.h
  src/rpc/client.cpp
  src/rpc/misc.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/script/keyorigin.h
  src/script/standard.cpp
  src/script/standard.h
  src/test/bip32_tests.cpp
  src/test/rpc_wallet_tests.cpp
  src/util/memory.h
  src/wallet/hdchain.cpp
  src/wallet/hdchain.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/scriptpubkeyman.cpp
  src/wallet/scriptpubkeyman.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
  test/functional/test_runner.py
  test/functional/wallet_dump.py
  test/functional/wallet_hd.py
  test/functional/wallet_keypool.py
  test/functional/wallet_keypool_topup.py
  test/functional/wallet_upgrade.py
  test/util/data/pre_hd_wallet.dat
Labels: GUI, RPC, Wallet, enhancement

#1373 [Wallet] Remove reserve balance
  doc/release-notes.md
  src/init.cpp
  src/main.cpp
  src/main.h
  src/rpc/client.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: Cleanup, Wallet

#1369 [Wallet] Fix staking balance calculation
  src/wallet/wallet.cpp
Labels: Wallet

#1385 [GUI] Don't change selected address after editing its label
  src/qt/pivx/receivewidget.cpp
  src/qt/pivx/receivewidget.h
Labels: Bug, GUI

#1400 [Trivial] Rewording of Custom Fee dialog text
  src/qt/pivx/sendcustomfeedialog.cpp
Labels: Trivial

#1375 [Init] Do parameter interaction before creating the UI model
  src/init.cpp
  src/init.h
  src/pivxd.cpp
  src/qt/pivx.cpp
Labels: GUI, Upstream

#1376 [Init] Combine common error strings so translations can be shared
  src/init.cpp
Labels: Docs and Output, Refactoring, Upstream

#1372 [P2P] Remove p2p alert system
  CMakeLists.txt
  doc/release-notes.md
  src/Makefile.am
  src/Makefile.test.include
  src/alert.cpp
  src/alert.h
  src/chainparams.cpp
  src/chainparams.h
  src/guiinterface.h
  src/init.cpp
  src/main.cpp
  src/main.h
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/test/alert_tests.cpp
  src/test/data/alertTests.raw
Labels: P2P, Upstream

#1402 [GUI][Bug] Fix max decimals in sendcustomfeedialog
  src/qt/pivx/forms/sendcustomfeedialog.ui
  src/qt/pivx/sendcustomfeedialog.cpp
Labels: Bug, GUI

#1390 [Build] Add flag for enabling thread_local
  configure.ac
Labels: Build System

#1401 [Wallet][Bug] Fix ScriptPubKeyMan::CanGetAddresses
  src/wallet/scriptpubkeyman.cpp
Labels: Bug, Wallet

#1404 [GUI] SendMultiRow: clear address label when address is changed
  src/qt/pivx/sendmultirow.cpp
Labels: Bug, GUI, Trivial

#1408 [GUI][Model] Save cache BlockIndex tip in the model
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
Labels: GUI, enhancement

#1412 [Cleanup] Remove walletbroadcast and resendwallettransactions tests
  test/functional/test_runner.py
  test/functional/wallet_basic.py
  test/functional/wallet_resendwallettransactions.py
Labels: Cleanup, Tests

#1409 [MN] Refactor to the `mapMasternodesLastVote` map.
  src/masternode-payments.h
Labels: Cleanup, Masternode

#1378 [Net] Fix de-serialization bug where AddrMan is corrupted after exception
  src/Makefile.test.include
  src/net.cpp
  src/net.h
  src/test/net_tests.cpp
Labels: Network, P2P, Upstream

#1368 [RPC] Expand getstakingstatus output
  doc/release-notes.md
  src/rpc/misc.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  test/functional/mining_pos_coldStaking.py
  test/functional/test_framework/test_framework.py
Labels: RPC, Wallet

#1418 [Consensus] Remove IsSuperMajority
  src/chain.h
  src/chainparams.cpp
  src/consensus/params.h
  src/main.cpp
  src/miner.cpp
  src/rpc/blockchain.cpp
  test/functional/test_framework/blocktools.py
  test/functional/test_framework/messages.py
Labels: Consensus

#1405 [GUI] Upgrade to HD wallet functionality.
  src/qt/pivx/expandablebutton.cpp
  src/qt/pivx/expandablebutton.h
  src/qt/pivx/forms/topbar.ui
  src/qt/pivx/res/css/style_dark.css
  src/qt/pivx/res/css/style_light.css
  src/qt/pivx/topbar.cpp
  src/qt/pivx/topbar.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: GUI, Wallet

#1410 [Tests] Run tests on pre-HD wallets
  src/init.cpp
  src/wallet/scriptpubkeyman.cpp
  test/functional/test_framework/test_framework.py
  test/functional/test_runner.py
  test/functional/wallet_hd.py
  test/functional/wallet_keypool_topup.py
  test/functional/wallet_upgrade.py
Labels: Startup, Tests, Wallet

#1413 [GUI] Explicit cast from quint32 to bool in filterAcceptsRow
  src/qt/transactionfilterproxy.cpp
Labels: Bug, GUI

#1381 [RPC][Bug] Fix masternodecurrent: return next winner, not rank-1 mn
  src/rpc/masternode.cpp
Labels: Bug, Masternode, RPC

#1367 [Net] Max block locator entries size.
  src/main.cpp
  src/net.h
Labels: P2P, Upstream

#1403 [GUI] SendWidget: automatically set focus on last recipient entry
  src/qt/pivx/send.cpp
  src/qt/pivx/send.h
Labels: GUI, Usability

#1435 [Travis][Build] Restore macOS Travis tests
  .travis.yml
  CMakeLists.txt
Labels: Build System

#1428 [GUI][Trivial] Emphasize warning better
  src/qt/askpassphrasedialog.cpp
Labels: GUI, Trivial

#1392 [GUI] Accept dialogs with ENTER, reject with ESC
  doc/release-notes.md
  src/qt/guiutil.h
  src/qt/pivx/defaultdialog.cpp
  src/qt/pivx/defaultdialog.h
  src/qt/pivx/sendconfirmdialog.cpp
  src/qt/pivx/sendconfirmdialog.h
Labels: GUI, Usability

#1411 [Wallet][Bug] Fix ScriptPubKeyMan::CanGenerateKeys
  src/wallet/scriptpubkeyman.cpp
Labels: Bug, Wallet

#1364 [Refactor][PoS] Kernel Refactoring
  CMakeLists.txt
  src/Makefile.am
  src/chain.cpp
  src/chain.h
  src/chainparams.cpp
  src/kernel.cpp
  src/kernel.h
  src/legacy/stakemodifier.cpp
  src/legacy/stakemodifier.h
  src/main.cpp
  src/rpc/blockchain.cpp
  src/stakeinput.cpp
  src/stakeinput.h
  src/timedata.cpp
  src/timedata.h
  src/wallet/wallet.cpp
  src/zpiv/zpos.cpp
  src/zpiv/zpos.h
Labels: Consensus, Refactoring

#1387 [GUI] Add Unlock/Relock context flow
  doc/release-notes.md
  src/Makefile.qt.include
  src/qt/CMakeLists.txt
  src/qt/addresstablemodel.cpp
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/pivx/coldstakingwidget.cpp
  src/qt/pivx/forms/walletpassworddialog.ui
  src/qt/pivx/guitransactionsutils.cpp
  src/qt/pivx/lockunlock.cpp
  src/qt/pivx/masternodeswidget.cpp
  src/qt/pivx/privacywidget.cpp
  src/qt/pivx/pwidget.cpp
  src/qt/pivx/pwidget.h
  src/qt/pivx/receivewidget.cpp
  src/qt/pivx/send.cpp
  src/qt/pivx/settings/settingsbittoolwidget.cpp
  src/qt/pivx/settings/settingsmultisendwidget.cpp
  src/qt/pivx/settings/settingssignmessagewidgets.cpp
  src/qt/pivx/topbar.cpp
  src/qt/pivx/topbar.h
  src/qt/pivx/walletpassworddialog.cpp
  src/qt/pivx/walletpassworddialog.h
  src/qt/proposalframe.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Feature Request, GUI, Usability, Wallet

#1434 [QA] Continuous Testing Environment for legacy pre-HD wallets
  .travis.yml
  test/functional/test_runner.py
Labels: Build System, Tests

#1442 [Tests] Remove non-determinism which is breaking net_tests
  src/test/net_tests.cpp
Labels: Tests, Upstream

#1448 [CMake] Fix missing file error
  src/qt/CMakeLists.txt
Labels: Build System, Trivial

#1431 [GUI] Automatic wallet backup after upgrade to HD
  src/qt/pivx/topbar.cpp
Labels: GUI, Usability, Wallet

#1430 [Trivial][GUI] Fix capsLabel color (make it text-warning)
  src/qt/askpassphrasedialog.cpp
  src/qt/pivx/res/css/style_dark.css
  src/qt/pivx/res/css/style_light.css
Labels: GUI, Trivial

#1458 [Bug] Fix min depth requirement for stake inputs in AvailableCoins
  src/wallet/wallet.cpp
Labels: Block Generation, Bug

#1407 [Consensus] CheckColdStakeFreeOutput when mnsync not complete
  src/main.cpp
Labels: Bug, Cold Staking, Consensus, Masternode

#1457 [Bug] Fix g_best_block initialization in ABC
  src/init.cpp
Labels: Block Generation, Bug

#1460 netbase: Do not print an error on connection timeouts through proxy
  src/init.cpp
  src/net.cpp
  src/net.h
  src/netbase.cpp
Labels: Network, P2P

#1462 [PoS] Stake Modifier V3
  src/blocksignature.cpp
  src/chain.cpp
  src/chain.h
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/tx_verify.cpp
  src/consensus/tx_verify.h
  src/kernel.cpp
  src/main.cpp
  src/miner.cpp
  src/primitives/block.h
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/rpc/blockchain.cpp
  src/script/interpreter.cpp
  src/script/script.cpp
  src/script/script.h
  src/script/script_error.cpp
  src/script/script_error.h
  src/stakeinput.cpp
  src/stakeinput.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/zpiv/zpos.h
  test/functional/mining_pos_reorg.py
  test/functional/test_framework/test_framework.py
Labels: Block Generation, Protocol-Update, Validation

#1449 [Util] tinyformat / LogPrint backports
  src/tinyformat.h
  src/util.h
Labels: Upstream, Util / log / libs

#1461 [Cleanup] Remove old governancepage and proposalframe code
  src/Makefile.qt.include
  src/qt/CMakeLists.txt
  src/qt/forms/governancepage.ui
  src/qt/governancepage.cpp
  src/qt/governancepage.h
  src/qt/proposalframe.cpp
  src/qt/proposalframe.h
  src/qt/res/css/default.css
Labels: Cleanup

#1452 [Net] Add support for dnsseeds with option to filter by servicebits
  src/chainparams.cpp
  src/chainparams.h
  src/net.cpp
Labels: Network, P2P, Upstream

#1438 [Trivial] Remove spammy log in CheckSignature
  src/messagesigner.cpp
Labels: Trivial, Util / log / libs

#1453 [Net] Addrman offline attempts
  src/activemasternode.cpp
  src/addrman.cpp
  src/addrman.h
  src/net.cpp
  src/net.h
  src/obfuscation-relay.cpp
  src/rpc/masternode.cpp
  src/rpc/net.cpp
Labels: Network, P2P, Upstream

#1465 [Bug] Fix height_start_StakeModifierV3
  src/chainparams.cpp
Labels: Bug, Consensus, High Priority

#1463 [Net] Protocol update enforcement for 70919
  src/main.cpp
  src/version.h
  test/functional/test_framework/messages.py
Labels: Consensus, Network, Protocol-Update

#1454 [GUI] Settings widget, expand/collapse scroll area.
  src/qt/pivx/settings/forms/settingswidget.ui
  src/qt/pivx/settings/settingswidget.cpp
  src/qt/pivx/settings/settingswidget.h
Labels: GUI, Usability

#1424 [GUI] One-click export to file
  src/qt/pivx/settings/forms/settingsbackupwallet.ui
  src/qt/pivx/settings/forms/settingsexportcsv.ui
  src/qt/pivx/settings/settingsbackupwallet.cpp
  src/qt/pivx/settings/settingsbackupwallet.h
  src/qt/pivx/settings/settingsexportcsv.cpp
  src/qt/pivx/settings/settingsexportcsv.h
Labels: Feature Request, GUI, Usability

#1464 [GUI][Model] Fix staking address validation
  src/qt/pivx/sendmultirow.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: Bug, Cold Staking, GUI

#1467 [Cleanup] Remove redundant and unused code
  src/activemasternode.cpp
  src/masternode-payments.cpp
  src/masternode.cpp
  src/masternode.h
  src/masternodeman.cpp
  src/spork.cpp
  src/sporkid.h
Labels: Cleanup

#1468 [GUI] Less GUI locks, IBD state cached.
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/qt/pivx/dashboardwidget.cpp
Labels: GUI

#1433 [Scripts] Only fetch translations for high-completion locals
  .tx/config
  contrib/devtools/update-translations.py
Labels: Scripts and Tools

#1472 [Tests][Refactor] Remove connect_nodes_bi
  test/functional/feature_notifications.py
  test/functional/interface_rest.py
  test/functional/mining_pos_coldStaking.py
  test/functional/mining_pos_reorg.py
  test/functional/p2p_disconnect_ban.py
  test/functional/p2p_time_offset.py
  test/functional/rpc_fundrawtransaction.py
  test/functional/rpc_invalidateblock.py
  test/functional/rpc_net.py
  test/functional/rpc_rawtransaction.py
  test/functional/test_framework/test_framework.py
  test/functional/test_framework/util.py
  test/functional/test_runner.py
  test/functional/wallet_abandonconflict.py
  test/functional/wallet_basic.py
  test/functional/wallet_bumpfee.py
  test/functional/wallet_keypool_topup.py
  test/functional/wallet_listsinceblock.py
Labels: Refactoring, Tests, Upstream
