Repository PIVX-Project/PIVX, pull requests merged in 2021-01, with the labels that each got.

#2121 [GUI][Trivial] Save cold-staking address in contacts
  src/qt/pivx/addresseswidget.cpp
Labels: Cold Staking, GUI, Needs Backport, Trivial

#2122 [BUG][GUI] Fix double conf dialog for RPC commands that expose privkeys
  src/qt/pivx/settings/settingsconsolewidget.cpp
Labels: Bug, GUI, Needs Backport

#2119 [RPC] Fix inconsistencies in outputs
  src/rpc/blockchain.cpp
  src/rpc/masternode.cpp
  src/rpc/misc.cpp
  src/wallet/rpcdump.cpp
Labels: Cleanup, Needs Backport, Needs Release Notes, RPC

#2115 [GUI] Fixing tooltip balance amount cropped
  src/qt/pivx/balancebubble.cpp
  src/qt/pivx/forms/balancebubble.ui
  src/wallet/db.h
Labels: Bug, GUI, Needs Backport

#2120 [RPC] Update Sapling HD chain seed with sethdseed
  src/wallet/rpcwallet.cpp
  test/functional/test_runner.py
  test/functional/wallet_hd.py
Labels: Needs Backport, Sapling, Wallet

#2123 [Test] Attempt to fix the diversified address equal to default address test scenario
  src/test/librust/wallet_zkeys_tests.cpp
Labels: Needs Backport, Sapling, Tests

#2125 [GUI] Update Translations from Transifex
  .tx/config
  src/qt/locale/pivx_de.ts
  src/qt/locale/pivx_en.ts
  src/qt/locale/pivx_en_US.ts
  src/qt/locale/pivx_es.ts
  src/qt/locale/pivx_es_ES.ts
  src/qt/locale/pivx_fr_FR.ts
  src/qt/locale/pivx_hr_HR.ts
  src/qt/locale/pivx_it.ts
  src/qt/locale/pivx_ko_KR.ts
  src/qt/locale/pivx_nl.ts
  src/qt/locale/pivx_pl.ts
  src/qt/locale/pivx_ru.ts
  src/qt/locale/pivx_tr.ts
  src/qt/locale/pivx_zh_CN.ts
  src/qt/pivxstrings.cpp
Labels: GUI, Needs Backport

#2114 [Doc] v5 Release Notes
  doc/release-notes.md
Labels: Docs and Output, Needs Backport

#2124 [Backport] Final 5.0 backports
  .tx/config
  doc/release-notes.md
  src/chainparams.cpp
  src/qt/coincontroldialog.cpp
  src/qt/coincontroldialog.h
  src/qt/locale/pivx_de.ts
  src/qt/locale/pivx_en.ts
  src/qt/locale/pivx_en_US.ts
  src/qt/locale/pivx_es.ts
  src/qt/locale/pivx_es_ES.ts
  src/qt/locale/pivx_fr_FR.ts
  src/qt/locale/pivx_hr_HR.ts
  src/qt/locale/pivx_it.ts
  src/qt/locale/pivx_ko_KR.ts
  src/qt/locale/pivx_nl.ts
  src/qt/locale/pivx_pl.ts
  src/qt/locale/pivx_ru.ts
  src/qt/locale/pivx_tr.ts
  src/qt/locale/pivx_zh_CN.ts
  src/qt/pivx/addresseswidget.cpp
  src/qt/pivx/balancebubble.cpp
  src/qt/pivx/forms/balancebubble.ui
  src/qt/pivx/qtutils.cpp
  src/qt/pivx/settings/settingsconsolewidget.cpp
  src/qt/pivx/txrow.cpp
  src/qt/pivx/txviewholder.cpp
  src/qt/pivxstrings.cpp
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/rpc/blockchain.cpp
  src/rpc/budget.cpp
  src/rpc/masternode.cpp
  src/rpc/misc.cpp
  src/rpc/rawtransaction.cpp
  src/test/librust/wallet_zkeys_tests.cpp
  src/wallet/db.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.h
  test/functional/test_runner.py
  test/functional/wallet_hd.py
Labels: Backport

#2128 [GUI] Receive screen, fix missing "Add label" text.
  src/qt/pivx/receivewidget.cpp
Labels: GUI

#2133 [Net] Remove unused RecvLine function.
  src/net.cpp
  src/net.h
Labels: Cleanup, Trivial

#2130 [Backport][Net] Do not make it trivial for inbound peers to generate log entries
  src/net.cpp
  src/net_processing.cpp
  src/spork.cpp
Labels: Needs Backport, P2P, Upstream

#2134 [P2P][BUG] Incorrect name logged for inventory messages
  src/protocol.cpp
  src/protocol.h
Labels: Bug, Masternode, Needs Backport, P2P

#2129 [Backport] Check interruptNet during dnsseed lookups
  src/net.cpp
Labels: P2P, Upstream

#2136 [BUG][Masternodes] Prevent broadcast of pre-5.0 stale masternode data
  src/budget/budgetdb.cpp
  src/init.cpp
  src/masternode-payments.cpp
  src/masternode.cpp
  src/masternodeman.cpp
  src/version.h
Labels: Bug, Masternode

#2137 [Consensus] Fix superblock block value
  src/budget/budgetmanager.cpp
  src/budget/budgetmanager.h
  src/budget/finalizedbudget.h
  src/chainparams.cpp
  src/masternode-payments.cpp
  src/masternode-payments.h
  src/test/budget_tests.cpp
  src/version.h
Labels: Bug, Consensus, Needs Backport, Protocol-Update

#2138 [Backport] 5.0.1 backports
  src/budget/budgetdb.cpp
  src/budget/budgetmanager.cpp
  src/budget/budgetmanager.h
  src/budget/finalizedbudget.h
  src/chainparams.cpp
  src/init.cpp
  src/masternode-payments.cpp
  src/masternode-payments.h
  src/masternode.cpp
  src/masternodeman.cpp
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/protocol.cpp
  src/protocol.h
  src/qt/pivx/receivewidget.cpp
  src/spork.cpp
  src/test/budget_tests.cpp
  src/version.h
Labels: Backport

#2082 Generic event handler interface
  CMakeLists.txt
  src/Makefile.am
  src/init.cpp
  src/init.h
  src/interfaces/handler.cpp
  src/interfaces/handler.h
  src/interfaces/wallet.cpp
  src/interfaces/wallet.h
  src/miner.cpp
  src/net.cpp
  src/pivxd.cpp
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/qt/pivx.cpp
  src/qt/pivx/pivxgui.cpp
  src/qt/pivx/pivxgui.h
  src/qt/pivx/splash.cpp
  src/qt/pivx/splash.h
  src/qt/transactiontablemodel.cpp
  src/qt/transactiontablemodel.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/rpc/server.cpp
  src/scheduler.cpp
  src/scheduler.h
  src/test/reverselock_tests.cpp
  src/test/scheduler_tests.cpp
  src/test/transaction_tests.cpp
  src/torcontrol.cpp
  src/validationinterface.cpp
  src/validationinterface.h
  src/wallet/rpcwallet.cpp
  src/wallet/walletdb.cpp
Labels: Refactoring, Upstream

#2141 [RPC] Fix argument parsing and example for getbalance
  src/rpc/client.cpp
  src/wallet/rpcwallet.cpp
Labels: Bug, RPC, Trivial

#2142 [Build] Bump master to 5.0.99
  build-aux/snap/snapcraft.yaml
  configure.ac
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win.yml
  doc/release-notes.md
  doc/release-notes/release-notes-5.0.0.md
  doc/release-notes/release-notes-5.0.1.md
Labels: Build System, Docs and Output

#2144 [Tests][BUG] Fix random range in feature_blockhashcache
  test/functional/feature_blockhashcache.py
Labels: Bug, Tests

#2143 [BUG] Fix deadlock in GetNextMasternodeInQueueForPayment
  src/masternodeman.cpp
  src/masternodeman.h
  src/rpc/masternode.cpp
Labels: Bug, Masternode

#2147 [RPC] fix getbalance transparent watch-only amount.
  src/wallet/rpcwallet.cpp
Labels: Bug, RPC

#2089 [Refactor] Fix some -Wdeprecated-copy warnings
  src/masternode.h
  src/messagesigner.cpp
  src/messagesigner.h
  src/policy/feerate.h
  src/primitives/transaction.h
  src/txmempool.cpp
  src/txmempool.h
Labels: Refactoring

#2090 [Net] Fail instead of truncate command name in CMessageHeader
  src/protocol.cpp
  src/protocol.h
Labels: P2P, Upstream

#2092 [Core] Migrate uint160 (CKeyID/CScriptID) to opaque blobs
  src/blob_uint256.h
  src/qt/pivx/settings/settingsbittoolwidget.cpp
  src/test/uint256_tests.cpp
  src/uint256.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: Refactoring

#2118 [NET] Inv, mempool and validation improvements
  CMakeLists.txt
  doc/files.md
  src/Makefile.am
  src/indirectmap.h
  src/init.cpp
  src/memusage.h
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/net_processing.h
  src/qt/pivx.cpp
  src/rpc/blockchain.cpp
  src/test/mempool_tests.cpp
  src/test/policyestimator_tests.cpp
  src/txmempool.cpp
  src/txmempool.h
  src/validation.cpp
  src/validation.h
  test/functional/mempool_packages.py
  test/functional/mempool_persist.py
  test/functional/test_runner.py
  test/functional/wallet_hd.py
Labels: Mempool, P2P, TX fees and policy, Upstream

#2146 [Tests] Add checkblock benchmark test
  src/Makefile.bench.include
  src/Makefile.test.include
  src/bench/checkblock.cpp
  src/bench/data/block2680960.raw
Labels: Tests, Upstream

#2126 [Backport] Wallet database handling abstractions/simplifications
  src/qt/optionsmodel.cpp
  src/qt/pivx/settings/settingsmultisendwidget.cpp
  src/sapling/sapling_operation.cpp
  src/sapling/saplingscriptpubkeyman.cpp
  src/test/librust/wallet_zkeys_tests.cpp
  src/wallet/db.cpp
  src/wallet/db.h
  src/wallet/rpcwallet.cpp
  src/wallet/scriptpubkeyman.cpp
  src/wallet/test/wallet_test_fixture.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
Labels: Upstream, Wallet

#2148 [Core] Prevector Optimizations 2
  src/cuckoocache.h
  src/prevector.h
  src/serialize.h
  src/test/prevector_tests.cpp
Labels: Refactoring, Tests, Upstream

#2154 [RPC] `validateaddress` remove duplicate return address value.
  src/rpc/misc.cpp
Labels: Bug, RPC

#1974 [Refactoring] Use c++11 list initialization for maps/vectors
  src/chainparams.cpp
  src/chainparamsbase.cpp
  src/core_read.cpp
  src/core_write.cpp
  src/kernel.cpp
  src/pivx-tx.cpp
  src/qt/coincontroldialog.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/rawtransaction.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/test/crypto_tests.cpp
  src/test/netbase_tests.cpp
  src/test/transaction_tests.cpp
  src/wallet/rpcwallet.cpp
Labels: Refactoring

#2168 [Trivial][Tests] Fix tests order on test_runner --all
  test/functional/test_runner.py
Labels: Tests, Trivial

#2152 [CMake] Fix CMake builds on macOS Big Sur
  CMakeLists.txt
Labels: Build System, macOS

#2165 [Tests] Check for diversified address equal to default one in zkeys_test
  src/test/librust/wallet_zkeys_tests.cpp
Labels: Bug, Sapling, Tests

#2044 [Wallet] Making CWalletTx store TransactionRef.
  src/primitives/transaction.h
  src/qt/pivx/coldstakingmodel.cpp
  src/qt/pivx/masternodewizarddialog.cpp
  src/qt/pivx/sendconfirmdialog.cpp
  src/qt/transactionrecord.cpp
  src/qt/walletmodel.cpp
  src/sapling/sapling_operation.cpp
  src/sapling/saplingscriptpubkeyman.cpp
  src/test/librust/sapling_rpc_wallet_tests.cpp
  src/test/librust/sapling_wallet_tests.cpp
  src/test/librust/utiltest.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/wallet_shielded_balances_tests.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Wallet

#2117 [BUG][Wallet] Restore AddressBook when marking used keys in the keypool
  src/wallet/scriptpubkeyman.cpp
  test/functional/test_runner.py
  test/functional/wallet_hd.py
Labels: Bug, Wallet

#2105 [Build] Don't compile PoW mining RPC commands by default
  configure.ac
  doc/release-notes.md
  src/rpc/mining.cpp
Labels: Build System

#2150 Revamping block validation interface interaction with wallet
  src/init.cpp
  src/miner.cpp
  src/net.cpp
  src/net_processing.h
  src/sapling/saplingscriptpubkeyman.cpp
  src/sapling/saplingscriptpubkeyman.h
  src/scheduler.cpp
  src/scheduler.h
  src/test/mempool_tests.cpp
  src/txmempool.cpp
  src/txmempool.h
  src/validation.cpp
  src/validationinterface.cpp
  src/validationinterface.h
  src/wallet/test/wallet_shielded_balances_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
  src/zmq/zmqnotificationinterface.cpp
  src/zmq/zmqnotificationinterface.h
  test/functional/feature_notifications.py
Labels: Mempool, Upstream, Validation, Wallet

#2166 [BUG] Flush the chainstate after pruning invalid entries.
  src/init.cpp
Labels: Bug, UTXO DBs and Indexes

#2132 [Tests] Add more cases to sighash_tests for malleated txes
  src/test/sighash_tests.cpp
Labels: Sapling, Tests

#2170 Better pivx.conf Masternode data error notification
  src/init.cpp
Labels: Masternode, Startup

#2173 [GUI] Prevent invalid dashboard txs list filter value loaded from settings
  src/qt/pivx/dashboardwidget.cpp
Labels: Bug, GUI
