Repository PIVX-Project/PIVX, pull requests merged in 2021-07, with the labels that each got.

#2414 Finish address encoding cleanup
  src/Makefile.am
  src/attributes.h
  src/base58.cpp
  src/base58.h
  src/bech32.cpp
  src/bench/base58.cpp
  src/bip38.cpp
  src/core_write.cpp
  src/destination_io.cpp
  src/evo/deterministicmns.cpp
  src/evo/providertx.cpp
  src/httprpc.cpp
  src/key_io.cpp
  src/key_io.h
  src/masternode.h
  src/masternodeman.h
  src/messagesigner.cpp
  src/pivx-tx.cpp
  src/qt/addresstablemodel.cpp
  src/qt/bitcoinaddressvalidator.cpp
  src/qt/paymentserver.cpp
  src/qt/pivx/masternodewizarddialog.cpp
  src/qt/pivx/settings/settingsbittoolwidget.cpp
  src/qt/pivx/settings/settingssignmessagewidgets.cpp
  src/qt/transactionrecord.cpp
  src/qt/walletmodel.h
  src/rpc/blockchain.cpp
  src/rpc/budget.cpp
  src/rpc/masternode.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/rawtransaction.cpp
  src/rpc/rpcevo.cpp
  src/rpc/server.cpp
  src/spork.h
  src/test/base58_tests.cpp
  src/test/bloom_tests.cpp
  src/test/key_tests.cpp
  src/test/librust/sapling_rpc_wallet_tests.cpp
  src/test/librust/sapling_wallet_tests.cpp
  src/test/rpc_tests.cpp
  src/test/script_P2CS_tests.cpp
  src/test/util_tests.cpp
  src/txdb.cpp
  src/util/string.cpp
  src/util/string.h
  src/util/vector.h
  src/utilstrencodings.cpp
  src/utilstrencodings.h
  src/wallet/hdchain.cpp
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
Labels: Cleanup, Refactoring, Tests, Upstream, Util / log / libs

#2417 [net processing] Swap out signals for an interface class
  src/init.cpp
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/net_processing.h
  src/test/DoS_tests.cpp
  src/test/test_pivx.cpp
  src/test/test_pivx.h
Labels: Network, P2P, Upstream

#2444 [Test] Fix wallet_encryption.py race condition.
  test/functional/wallet_encryption.py
Labels: Tests

#2459 Fix install-params.sh "popd: directory stack empty".
  params/install-params.sh
Labels: Scripts and Tools

#2465 [Build] fix macOS depends deployment
  contrib/macdeploy/README.md
  depends/builders/darwin.mk
  depends/hosts/darwin.mk
  depends/packages/bdb.mk
Labels: Build System, Upstream

#2466 [Doc] Remove OpenSSL instructions in build-osx.md
  doc/build-osx.md
Labels: Docs and Output

#2380 [Cleanup] guiutils cleanup + fix memory mismanagement
  doc/release-notes.md
  src/compat/byteswap.h
  src/qt/guiutil.cpp
  src/qt/guiutil.h
  src/qt/pivx.cpp
  src/qt/pivx/settings/settingsmainoptionswidget.cpp
  src/util/system.cpp
Labels: GUI, Refactoring, Upstream, macOS

#2369 [Wallet] Clean wallet auto-backup "feature"
  src/wallet/init.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
Labels: Wallet

#2471 [Build] fix GA boost test random seed number overflow
  .github/workflows/build-and-test.yml
Labels: Build System, High Priority

#2363 [Validation][RPC] ProUpReg and ProUpRev special tx types
  src/evo/deterministicmns.cpp
  src/evo/deterministicmns.h
  src/evo/providertx.cpp
  src/evo/providertx.h
  src/evo/specialtx.cpp
  src/primitives/transaction.h
  src/random.h
  src/rpc/rawtransaction.cpp
  src/rpc/rpcevo.cpp
  src/test/evo_deterministicmns_tests.cpp
  src/test/evo_specialtx_tests.cpp
  src/test/test_pivx.h
  src/txmempool.cpp
  test/functional/test_framework/messages.py
  test/functional/test_framework/test_framework.py
  test/functional/test_framework/util.py
  test/functional/test_runner.py
  test/functional/tiertwo_deterministicmns.py
  test/functional/tiertwo_reorg_mempool.py
Labels: Masternode, RPC, Tests, Upstream Dash, Validation

#2425 [Cleanup] The zerocoin garbage collector is in town once more.
  CMakeLists.txt
  src/Makefile.am
  src/consensus/zerocoin_verify.cpp
  src/consensus/zerocoin_verify.h
  src/txdb.cpp
  src/txdb.h
  src/validation.cpp
  src/zpiv/mintpool.cpp
  src/zpiv/mintpool.h
  src/zpiv/zerocoin.cpp
  src/zpiv/zerocoin.h
  src/zpiv/zpivmodule.h
Labels: Cleanup

#2378 [Policy] Child-pays-for-parent Implementation + CoinAge priority removal
  contrib/devtools/check-doc.py
  doc/release-notes.md
  src/blockassembler.cpp
  src/blockassembler.h
  src/coins.cpp
  src/coins.h
  src/init.cpp
  src/net_processing.cpp
  src/policy/fees.cpp
  src/policy/fees.h
  src/policy/policy.h
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/qt/coincontroldialog.cpp
  src/qt/pivx/send.cpp
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/net.cpp
  src/rpc/rawtransaction.cpp
  src/sapling/sapling_operation.cpp
  src/test/mempool_tests.cpp
  src/test/miner_tests.cpp
  src/test/policyestimator_tests.cpp
  src/test/test_pivx.cpp
  src/test/test_pivx.h
  src/txmempool.cpp
  src/txmempool.h
  src/validation.cpp
  src/validation.h
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  test/functional/feature_nulldummy.py
  test/functional/mempool_packages.py
  test/functional/mining_prioritisetransaction.py
  test/functional/sapling_wallet.py
  test/functional/wallet_abandonconflict.py
Labels: Block Generation, Mempool, TX fees and policy, Upstream, Wallet

#2422 [Net] Mockable PoissonNextSend helper and tests mempool sync fixes
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/net_processing.h
  src/test/DoS_tests.cpp
  src/test/net_tests.cpp
  test/functional/mining_pos_coldStaking.py
  test/functional/mining_pos_fakestake.py
  test/functional/mining_pos_reorg.py
  test/functional/test_framework/test_framework.py
  test/functional/tiertwo_mn_compatibility.py
  test/functional/wallet_listtransactions.py
Labels: Network, P2P, Refactoring, Upstream

#2426 [Build] Update crc32c subtree
  src/Makefile.crc32c.include
  src/crc32c/.appveyor.yml
  src/crc32c/AUTHORS
  src/crc32c/CMakeLists.txt
  src/crc32c/Crc32cConfig.cmake.in
  src/crc32c/src/crc32c.cc
  src/crc32c/src/crc32c_arm64.cc
  src/crc32c/src/crc32c_arm64.h
  src/crc32c/src/crc32c_arm64_check.h
  src/crc32c/src/crc32c_benchmark.cc
  src/crc32c/src/crc32c_read_le.h
Labels: Build System

#2267 [Doc] Introducing Deterministic Masternodes
  doc/release-notes.md
Labels: Docs and Output, Masternode

#2347 [GUI] Add GUI controls for subtract-fee-from-amount
  src/Makefile.qt.include
  src/qt/pivx.qrc
  src/qt/pivx/forms/sendmultirow.ui
  src/qt/pivx/res/css/style_dark.css
  src/qt/pivx/res/css/style_light.css
  src/qt/pivx/res/img/ic-check-box-light.svg
  src/qt/pivx/send.cpp
  src/qt/pivx/send.h
  src/qt/pivx/sendconfirmdialog.cpp
  src/qt/pivx/sendmultirow.cpp
  src/qt/pivx/sendmultirow.h
  src/qt/pivx/tooltipmenu.cpp
  src/qt/pivx/tooltipmenu.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/qt/walletmodeltransaction.cpp
  src/qt/walletmodeltransaction.h
Labels: Feature Request, GUI, Needs Release Notes

#2476 [RPC] correct non PIVXified help commands texts and add missing "ischange" result.
  src/rpc/misc.cpp
  src/wallet/rpcwallet.cpp
Labels: Needs Release Notes, RPC

#2447 [Build][Cleanup] Tidy up the gitian build descriptors
  Makefile.am
  configure.ac
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win.yml
  share/setup.nsi.in
Labels: Build System, Cleanup, Upstream

#2460 Reorder C{,Mutable}Transaction for better packing
  src/primitives/transaction.cpp
  src/primitives/transaction.h
Labels: Refactoring, Upstream

#2478 [Refactor][Cleanup] remove g_newP2CSRules flag
  src/script/interpreter.cpp
  src/script/script.cpp
  src/script/script.h
  src/test/script_P2CS_tests.cpp
  src/validation.cpp
Labels: Cleanup, Cold Staking, Refactoring

#2479 [Build] bench build, raw generated file improvement and fixes.
  src/Makefile.bench.include
  src/bench/checkblock.cpp
  src/bench/data.cpp
  src/bench/data.h
Labels: Build System, Tests, Upstream

#2470 Span sources updates, up-to-date with current upstream.
  doc/developer-notes.md
  src/attributes.h
  src/messagesigner.cpp
  src/qt/pivx/settings/settingssignmessagewidgets.cpp
  src/span.h
  src/uint256.h
  src/utilstrencodings.cpp
  src/utilstrencodings.h
  src/wallet/rpcwallet.cpp
Labels: Docs and Output, Refactoring, Upstream

#2473 [Backport] git-subtree-check.sh updated to latest upstream
  test/lint/git-subtree-check.sh
Labels: Scripts and Tools, Upstream

#2423 [Wallet] Introduce wallets directory configuration and external wallet files capabilities
  CMakeLists.txt
  doc/release-notes.md
  src/Makefile.am
  src/coins.h
  src/init.cpp
  src/net.h
  src/pivx-cli.cpp
  src/pivxd.cpp
  src/qt/forms/rpcconsole.ui
  src/qt/intro.cpp
  src/qt/pivx.cpp
  src/qt/pivx/settings/settingsinformationwidget.cpp
  src/qt/pivx/settings/settingswidget.cpp
  src/qt/rpcconsole.cpp
  src/qt/rpcconsole.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/streams.h
  src/support/lockedpool.h
  src/test/librust/sapling_rpc_wallet_tests.cpp
  src/test/librust/sapling_wallet_tests.cpp
  src/test/librust/wallet_zkeys_tests.cpp
  src/test/miner_tests.cpp
  src/test/script_P2CS_tests.cpp
  src/test/util_tests.cpp
  src/test/validation_tests.cpp
  src/txdb.h
  src/util/system.cpp
  src/util/system.h
  src/wallet/db.cpp
  src/wallet/db.h
  src/wallet/init.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/wallet_sapling_transactions_validations_tests.cpp
  src/wallet/test/wallet_shielded_balances_tests.cpp
  src/wallet/test/wallet_test_fixture.cpp
  src/wallet/test/wallet_test_fixture.h
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
  src/wallet/walletutil.cpp
  src/wallet/walletutil.h
  test/functional/feature_config_args.py
  test/functional/test_framework/test_framework.py
  test/functional/wallet_backup.py
  test/functional/wallet_hd.py
  test/functional/wallet_keypool_topup.py
  test/functional/wallet_multiwallet.py
  test/functional/wallet_reorgsrestore.py
Labels: Needs Release Notes, Refactoring, Upstream, Wallet

#2438 [Test] Extended test coverage for chain reorg during superblock and payments order.
  src/blockassembler.cpp
  src/blockassembler.h
  src/budget/budgetmanager.cpp
  src/budget/budgetmanager.h
  src/rpc/budget.cpp
  src/rpc/client.cpp
  src/test/budget_tests.cpp
  src/test/test_pivx.cpp
  src/test/test_pivx.h
  test/functional/test_runner.py
  test/functional/tiertwo_governance_invalid_budget.py
Labels: Budget/Proposal System, Tests

#2468 [Refactor] remove std::string DecodeBase58(const char*, int)
  src/base58.cpp
  src/base58.h
  src/bip38.cpp
Labels: Refactoring

#2464 Decouple peer-processing-logic from block-connection-logic + BIP61 removal.
  CMakeLists.txt
  doc/release-notes.md
  src/Makefile.am
  src/blockassembler.cpp
  src/miner.cpp
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/protocol.cpp
  src/protocol.h
  src/rpc/mining.cpp
  src/test/evo_deterministicmns_tests.cpp
  src/test/miner_tests.cpp
  src/test/test_pivx.cpp
  src/test/util/blocksutil.cpp
  src/test/validation_block_tests.cpp
  src/test/validation_tests.cpp
  src/util/blockstatecatcher.h
  src/validation.cpp
  src/validation.h
  src/wallet/rpcwallet.cpp
  src/zpivchain.cpp
  test/functional/p2p_leak.py
  test/functional/test_framework/messages.py
  test/functional/test_framework/mininode.py
Labels: Network, Validation

#2485 [Tests] fixing python lint, W292 no newline at end of file
  test/functional/tiertwo_governance_invalid_budget.py
Labels: NoFunctionalChanges, Tests, Trivial

#2486 [Tests] Fix ProcessNewBlock signature in budget_tests.cpp
  src/test/budget_tests.cpp
Labels: Bug, Tests

#2467 [Refactor] Replace MakeUnique with std::make_unique (C++14)
  src/Makefile.am
  src/httprpc.cpp
  src/init.cpp
  src/interfaces/handler.cpp
  src/net.cpp
  src/qt/pivx/masternodeswidget.cpp
  src/qt/pivx/send.cpp
  src/qt/pivx/topbar.cpp
  src/rpc/mining.cpp
  src/test/fuzz/fuzz.cpp
  src/test/net_tests.cpp
  src/test/test_pivx.cpp
  src/util/memory.h
  src/wallet/db.cpp
  src/wallet/db.h
  src/wallet/test/wallet_sapling_transactions_validations_tests.cpp
  src/wallet/wallet.h
Labels: Cleanup, Refactoring

#2483 [BUG][GUI] Fix broken tutorial screen
  src/qt/pivx.cpp
Labels: Bug, GUI, Startup, Wallet

#2488 [Trivial][Doc] Add missing codeblock triple backtick in relnotes file
  doc/release-notes.md
Labels: Docs and Output, NoFunctionalChanges, Trivial

#2487 [BUG][Tests] Delay POS activation in feature_blockhashcache test
  test/functional/feature_blockhashcache.py
Labels: Bug, Tests

#2484 [BUG] Zerocoin: fix spend validation and remove obsolete sporks
  src/coins.cpp
  src/consensus/tx_verify.cpp
  src/consensus/zerocoin_verify.cpp
  src/consensus/zerocoin_verify.h
  src/masternode-payments.cpp
  src/net_processing.cpp
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/spork.cpp
  src/sporkid.h
  src/test/budget_tests.cpp
  src/test/validation_tests.cpp
  src/validation.cpp
Labels: Bug, High Priority, Validation, zPiv

#2480 [Net] asmap to improve IP bucketing in addrman - backports
  CMakeLists.txt
  contrib/devtools/hexdump_util.sh
  src/Makefile.am
  src/Makefile.test.include
  src/addrdb.cpp
  src/addrman.cpp
  src/addrman.h
  src/init.cpp
  src/net.cpp
  src/net.h
  src/netaddress.cpp
  src/netaddress.h
  src/netbase.cpp
  src/qt/optionsmodel.h
  src/rpc/net.cpp
  src/serialize.h
  src/test/CMakeLists.txt
  src/test/addrman_tests.cpp
  src/test/data/asmap.raw
  src/test/net_tests.cpp
  src/test/netbase_tests.cpp
  src/torcontrol.cpp
  src/util/asmap.cpp
  src/util/asmap.h
  test/functional/feature_asmap.py
  test/functional/test_runner.py
Labels: Needs Release Notes, Network, P2P, RPC, Refactoring, Tests, Upstream

#2490 [BugFix] fix app always triggering the tutorial dialog if no manual '-wallet' arg is provided.
  src/qt/pivx.cpp
  src/util/system.cpp
Labels: Bug, GUI

#2448 [GUI] Periodic make translate
  src/qt/locale/pivx_en.ts
  src/qt/pivxstrings.cpp
Labels: GUI

#2404 [Refactoring] Improve pos checks in AcceptBlock
  src/Makefile.test.include
  src/init.cpp
  src/kernel.cpp
  src/legacy/validation_zerocoin_legacy.cpp
  src/legacy/validation_zerocoin_legacy.h
  src/stakeinput.cpp
  src/stakeinput.h
  src/test/CMakeLists.txt
  src/test/zerocoindb_tests.cpp
  src/txdb.cpp
  src/txdb.h
  src/validation.cpp
  src/validation.h
  src/zpiv/zpos.cpp
  src/zpiv/zpos.h
  test/functional/mining_pos_fakestake.py
Labels: Refactoring, Tests, Validation
