Repository PIVX-Project/PIVX, pull requests merged in 2021-12, with the labels that each got.

#2644 [Refactoring] remove circular dependency primitives/transaction <-> script/standard
  src/blocksignature.cpp
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  test/lint/lint-circular-dependencies.sh
Labels: Refactoring

#2631 [Validation] Synchronous update for CDeterministicMNManager::tipIndex
  src/activemasternode.cpp
  src/activemasternode.h
  src/evo/deterministicmns.cpp
  src/evo/deterministicmns.h
  src/evo/evonotificationinterface.cpp
  src/init.cpp
  src/rpc/masternode.cpp
  src/test/evo_deterministicmns_tests.cpp
  src/validation.cpp
  src/validationinterface.h
Labels: Bug, Validation, Refactoring, Tests, Masternode

#2661 [BUG] GUI: invalid locking of shield notes in coin control
  src/qt/coincontroldialog.cpp
Labels: GUI, Bug, Needs Backport

#2655 [GUI] Clean not longer used addnewaddressdialog.
  src/Makefile.qt.include
  src/qt/CMakeLists.txt
  src/qt/pivx/addnewaddressdialog.cpp
  src/qt/pivx/addnewaddressdialog.h
  src/qt/pivx/forms/addnewaddressdialog.ui
Labels: GUI, Cleanup

#2649 [Refactoring] Break deterministic mns circular dependencies
  CMakeLists.txt
  src/Makefile.am
  src/coins.cpp
  src/coins.h
  src/consensus/tx_verify.cpp
  src/evo/deterministicmns.cpp
  src/evo/providertx.cpp
  src/evo/providertx.h
  src/evo/specialtx.cpp
  src/evo/specialtx_validation.cpp
  src/evo/specialtx_validation.h
  src/primitives/transaction.h
  src/rpc/masternode.cpp
  src/rpc/rawtransaction.cpp
  src/rpc/rpcevo.cpp
  src/test/evo_deterministicmns_tests.cpp
  src/test/evo_specialtx_tests.cpp
  src/txmempool.cpp
  src/validation.cpp
  src/validation.h
  test/lint/lint-circular-dependencies.sh
Labels: Refactoring, Tests, Cleanup, Masternode

#2656 [Doc] Remove assets-attribution.md file.
  doc/README.md
  doc/assets-attribution.md
Labels: Docs and Output, Cleanup

#2662 [GUI] Don't show UTXO locking options for shield notes
  src/qt/coincontroldialog.cpp
Labels: GUI, Needs Backport

#2632 [net] Connman options encapsulation
  src/activemasternode.cpp
  src/init.cpp
  src/net.cpp
  src/net.h
  src/net_processing.cpp
Labels: P2P, Upstream

#2663 [Build] Sanitize governance UIs item naming
  src/qt/pivx/forms/governancewidget.ui
  src/qt/pivx/forms/proposalcard.ui
  src/qt/pivx/forms/proposalinfodialog.ui
  src/qt/pivx/forms/votedialog.ui
  src/qt/pivx/proposalinfodialog.cpp
Labels: Build System, GUI, NoFunctionalChanges, Cleanup, Needs Backport

#2671 [GUI] Differentiate Budget payment output records from MNs block reward records.
  src/chainparams.cpp
  src/consensus/params.h
  src/qt/pivx/qtutils.cpp
  src/qt/pivx/txrow.cpp
  src/qt/transactionfilterproxy.cpp
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/validation.cpp
Labels: GUI, Needs Backport

#2664 [GUI] Fix proposal tooltip menu location skewing
  src/qt/pivx/governancewidget.cpp
Labels: GUI, Bug, Needs Backport

#2670 [GUI] Governance, do not open the proposal creation wizard if node is in IBD.
  src/qt/pivx/governancewidget.cpp
Labels: GUI, Needs Backport

#2665 [GUI] Fix governance nav button hover css
  src/qt/pivx/res/css/style_dark.css
  src/qt/pivx/res/css/style_light.css
Labels: GUI, Bug, Needs Backport, Trivial

#2672 [GUI] Fix proposal name and URL size limit validation
  src/budget/budgetproposal.h
  src/qt/pivx/createproposaldialog.cpp
  src/qt/pivx/governancemodel.cpp
  src/qt/pivx/governancemodel.h
Labels: GUI, Bug

#2677 [net_processing] Fix ignoring get data requests when fPauseSend is set on a peer
  src/net_processing.cpp
Labels: Bug, Network

#2676 [Net_processing] Do not log "notfound" msg as unknown.
  src/net_processing.cpp
  src/protocol.h
  src/validation.cpp
Labels: Network

#2675 [Wallet] Clear Shield notes witness cache before a full rescan
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Wallet, Sapling

#2659 [TierTwo] Fix and improve several synchronization problems
  src/budget/budgetmanager.cpp
  src/budget/budgetmanager.h
  src/budget/budgetproposal.cpp
  src/budget/finalizedbudget.cpp
  src/init.cpp
  src/masternode-sync.cpp
  src/masternode-sync.h
  src/net_processing.cpp
  src/tiertwo_networksync.cpp
  test/functional/tiertwo_governance_sync_basic.py
Labels: P2P, Budget/Proposal System, Masternode

#2679 [Wallet] Avoid second mapWallet lookup
  src/rpc/budget.cpp
  src/sapling/saplingscriptpubkeyman.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: Refactoring, Wallet

#2674 [Refactor] Prevent multiple calls to ExtractDestination
  src/wallet/rpcwallet.cpp
Labels: RPC, Upstream, Refactoring, Wallet

#2658 [budget] Do not count votes twice after calling GetBudgetWithHighestVoteCount.
  src/budget/budgetmanager.cpp
  src/budget/budgetmanager.h
  src/budget/budgetproposal.cpp
  src/budget/budgetproposal.h
Labels: Budget/Proposal System

#2673 [Cleanup] Remove unused `RecentRequestsTableModel` and `PlatformStyle`
  src/Makefile.qt.include
  src/qt/CMakeLists.txt
  src/qt/pivx/topbar.cpp
  src/qt/platformstyle.cpp
  src/qt/platformstyle.h
  src/qt/recentrequeststablemodel.cpp
  src/qt/recentrequeststablemodel.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: GUI, Cleanup, Trivial

#2681 [BUG] Fix possible crashes at shutdown
  src/init.cpp
  src/validation.cpp
Labels: Upstream

#2682 [net] Remove assert(nMaxInbound > 0)
  src/net.cpp
Labels: Upstream, Network

#2657 [TierTwo] Fix more circular dependencies.
  src/budget/budgetmanager.cpp
  src/budget/budgetmanager.h
  src/masternode-payments.cpp
  src/masternode-payments.h
  src/masternodeman.cpp
  src/masternodeman.h
  src/net_processing.cpp
  src/qt/walletmodel.cpp
  src/rpc/budget.cpp
  src/spork.cpp
  src/spork.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  test/lint/lint-circular-dependencies.sh
Labels: P2P, Refactoring

#2680 [Refactor] Avoid double lookups in sapling maps
  src/sapling/saplingscriptpubkeyman.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: Refactoring, Wallet, Sapling

#2639 [net] disallow sending messages before receiving verack + enable p2p_leak.py test
  src/net_processing.cpp
  test/functional/p2p_leak.py
  test/functional/test_runner.py
Labels: Upstream, Network

#2685 [QA] Use single node in sapling_changeaddresses
  test/functional/sapling_changeaddresses.py
  test/functional/test_runner.py
Labels: Tests, Sapling

#2394 [budget] Clean pre-v5 consensus guards for proposal start block and max payment amount
  src/budget/budgetproposal.cpp
  src/budget/budgetproposal.h
Labels: Cleanup

#2687 [Doc] v5.4.0 release notes
  doc/release-notes/release-notes-5.4.0.md
Labels: Documentation

#2683 [RPC] listunspent: pre-filter coins by destination in AvailableCoins
  src/wallet/rpcwallet.cpp
Labels: RPC, Wallet

#2691 [GUI] Update translations for 5.4.0 release
  .tx/config
  src/Makefile.qt_locale.include
  src/qt/locale/pivx_de.ts
  src/qt/locale/pivx_en_US.ts
  src/qt/locale/pivx_es.ts
  src/qt/locale/pivx_es_ES.ts
  src/qt/locale/pivx_fr_FR.ts
  src/qt/locale/pivx_hr_HR.ts
  src/qt/locale/pivx_it.ts
  src/qt/locale/pivx_ko_KR.ts
  src/qt/locale/pivx_nl.ts
  src/qt/locale/pivx_pl.ts
  src/qt/locale/pivx_ru.ts
  src/qt/locale/pivx_tr.ts
  src/qt/locale/pivx_zh_CN.ts
  src/qt/pivx_locale.qrc
Labels: GUI

#2693 [Doc] Add v5.4.0 historical release notes
  doc/release-notes/release-notes-5.4.0.md
Labels: Documentation

#2607 [TierTwo] Long Living Masternode Quorums - Part 1
  CMakeLists.txt
  src/Makefile.am
  src/blockassembler.cpp
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/tx_verify.cpp
  src/evo/deterministicmns.cpp
  src/evo/deterministicmns.h
  src/evo/specialtx_validation.cpp
  src/init.cpp
  src/llmq/quorums_blockprocessor.cpp
  src/llmq/quorums_blockprocessor.h
  src/llmq/quorums_commitment.cpp
  src/llmq/quorums_commitment.h
  src/llmq/quorums_init.cpp
  src/llmq/quorums_init.h
  src/llmq/quorums_utils.cpp
  src/llmq/quorums_utils.h
  src/logging.cpp
  src/logging.h
  src/net_processing.cpp
  src/primitives/transaction.h
  src/protocol.cpp
  src/protocol.h
  src/serialize.h
  src/test/evo_deterministicmns_tests.cpp
  src/test/evo_specialtx_tests.cpp
  src/test/test_pivx.cpp
  src/tiertwo_networksync.cpp
  test/lint/lint-circular-dependencies.sh
Labels: Refactoring, Masternode, Consensus

#2695 [CLI][Build] Guard libevent error messages
  src/pivx-cli.cpp
Labels: Build System, Bug

#2694 [Build] Bump master to 5.4.99
  build-aux/snap/snapcraft.yaml
  configure.ac
Labels: Build System

#2684 [Refactor] Move tier two managers initialization from init.cpp to tiertwo/init.cpp
  CMakeLists.txt
  src/Makefile.am
  src/budget/budgetmanager.cpp
  src/init.cpp
  src/masternode-payments.cpp
  src/masternodeman.cpp
  src/spork.cpp
  src/tiertwo/init.cpp
  src/tiertwo/init.h
  src/util/system.cpp
  src/util/system.h
  src/validation.cpp
  src/wallet/wallet.cpp
Labels: Refactoring

#2606 [Net][GUI][RPC] Add enable/disable network activity feature
  src/guiinterface.h
  src/net.cpp
  src/net.h
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/qt/pivx/settings/forms/settingswalletoptionswidget.ui
  src/qt/pivx/settings/settingsinformationwidget.cpp
  src/qt/pivx/settings/settingsinformationwidget.h
  src/qt/pivx/settings/settingswalletoptionswidget.cpp
  src/qt/pivx/settings/settingswalletoptionswidget.h
  src/qt/pivx/topbar.cpp
  src/qt/pivx/topbar.h
  src/qt/rpcconsole.cpp
  src/qt/rpcconsole.h
  src/rpc/client.cpp
  src/rpc/misc.cpp
  src/rpc/net.cpp
  src/test/rpc_tests.cpp
Labels: RPC, GUI, Needs Release Notes, Network

#2698 [QA] Reject in-mempool llmqcomm transactions
  src/blockassembler.cpp
  src/blockassembler.h
  src/test/evo_deterministicmns_tests.cpp
  src/test/test_pivx.cpp
  src/test/test_pivx.h
  src/validation.cpp
Labels: Tests, Masternode

#2703 [Trivial] Add BLSVerify_LargeBlock10000 to bench/bls.cpp
  src/bench/bls.cpp
Labels: Tests, Trivial
