Repository PIVX-Project/PIVX, pull requests merged in 2021-11, with the labels that each got.

#2603 [Cleanup] Remove unused chain params
  src/chainparams.cpp
  src/consensus/params.h
Labels: Cleanup

#2622 [TierTwo] Do not ask for single MN items if the node is in initial sync state
  src/budget/budgetmanager.cpp
  src/masternode.cpp
Labels: Budget/Proposal System, Masternode

#2539 [Wallet] Sapling, restructure increment witnesses workflow
  src/Makefile.bench.include
  src/bench/CMakeLists.txt
  src/bench/checkblock.cpp
  src/bench/walletprocessblock.cpp
  src/evo/evonotificationinterface.h
  src/init.cpp
  src/sapling/saplingscriptpubkeyman.cpp
  src/test/test_pivx.cpp
Labels: Refactoring, Wallet, Sapling

#2626 [GUI][BugFix] Schedule proposal broadcast only if the block has not passed yet
  src/qt/pivx/governancemodel.cpp
Labels: GUI, Bug

#2627 [GUI] Correct proposal large title for being cut when the app window width isn't big enough
  src/qt/pivx/forms/proposalcard.ui
  src/qt/pivx/proposalcard.cpp
Labels: GUI

#2584 [Refactor] Reorder mnw processing and validation
  src/masternode-payments.cpp
  src/masternode-payments.h
  src/test/mnpayments_tests.cpp
Labels: Refactoring, Cleanup, Masternode

#2585 [Test] Secondary chains acceptance test coverage
  src/blockassembler.cpp
  src/blockassembler.h
  src/chainparams.cpp
  src/wallet/test/pos_validations_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  test/functional/mining_pos_coldStaking.py
Labels: Tests

#2628 [GUI] Periodic make translate
  src/qt/locale/pivx_en.ts
  src/qt/pivxstrings.cpp
Labels: GUI

#2590 [CI] Enable shellcheck linting
  .github/workflows/build-and-test.yml
  autogen.sh
  contrib/devtools/gen-manpages.sh
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx-signer.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win-signer.yml
  contrib/gitian-descriptors/gitian-win.yml
  contrib/install_db4.sh
  contrib/macdeploy/detached-sig-apply.sh
  contrib/macdeploy/detached-sig-create.sh
  contrib/qos/tc.sh
  contrib/tidy_datadir.sh
  contrib/verifysfbinaries/verify.sh
  contrib/windeploy/detached-sig-create.sh
  share/genbuild.sh
  test/README.md
  test/lint/lint-shell.sh
  util/fetch-params.sh
Labels: Scripts and Tools, Upstream

#2625 [wallet] Fix "null" backup file name.
  src/wallet/wallet.cpp
  src/wallet/walletdb.cpp
Labels: Bug, Wallet

#2620 [Refactor] Remove finalized budgets earlier
  src/budget/finalizedbudget.cpp
  src/budget/finalizedbudget.h
  test/functional/tiertwo_governance_sync_basic.py
Labels: Budget/Proposal System, Refactoring

#2633 [test] sapling_wallet_nullifiers.py whitelist peers to speed up tx relay.
  test/functional/sapling_wallet_nullifiers.py
Labels: Tests

#2630 [Cleanup] Remove unused variables and private fields
  src/bench/bls_dkg.cpp
  src/bench/walletprocessblock.cpp
  src/evo/evonotificationinterface.h
  src/masternodeman.cpp
  src/qt/walletmodel.cpp
  src/sapling/sapling_operation.cpp
  src/sapling/sapling_operation.h
  src/sapling/transaction_builder.cpp
  src/sapling/transaction_builder.h
  src/support/allocators/mt_pooled_secure.h
  src/test/librust/sapling_rpc_wallet_tests.cpp
  src/test/librust/sapling_wallet_tests.cpp
  src/test/librust/transaction_builder_tests.cpp
  src/test/librust/utiltest.cpp
  src/test/test_pivx.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/wallet_sapling_transactions_validations_tests.cpp
  src/wallet/test/wallet_shielded_balances_tests.cpp
Labels: Cleanup

#2629 [Util] Support serialization of std::vector<bool>
  src/serialize.h
  src/test/serialize_tests.cpp
Labels: Upstream, Util / log / libs

#2621 [GUI] Show disk space requirement per-network
  doc/release-process.md
  src/qt/intro.cpp
Labels: GUI

#2635 [GUI][Cleanup] Stop translating placeholder strings
  src/qt/forms/askpassphrasedialog.ui
  src/qt/forms/coincontroldialog.ui
  src/qt/forms/rpcconsole.ui
  src/qt/locale/pivx_en.ts
  src/qt/pivx/forms/addnewaddressdialog.ui
  src/qt/pivx/forms/addnewcontactdialog.ui
  src/qt/pivx/forms/addresseswidget.ui
  src/qt/pivx/forms/addresslabelrow.ui
  src/qt/pivx/forms/balancebubble.ui
  src/qt/pivx/forms/coldstakingwidget.ui
  src/qt/pivx/forms/contactdropdownrow.ui
  src/qt/pivx/forms/createproposaldialog.ui
  src/qt/pivx/forms/csrow.ui
  src/qt/pivx/forms/dashboardwidget.ui
  src/qt/pivx/forms/defaultdialog.ui
  src/qt/pivx/forms/expandablebutton.ui
  src/qt/pivx/forms/governancewidget.ui
  src/qt/pivx/forms/loadingdialog.ui
  src/qt/pivx/forms/lockunlock.ui
  src/qt/pivx/forms/masternodeswidget.ui
  src/qt/pivx/forms/masternodewizarddialog.ui
  src/qt/pivx/forms/mninfodialog.ui
  src/qt/pivx/forms/mnrow.ui
  src/qt/pivx/forms/mnselectiondialog.ui
  src/qt/pivx/forms/myaddressrow.ui
  src/qt/pivx/forms/navmenuwidget.ui
  src/qt/pivx/forms/optionbutton.ui
  src/qt/pivx/forms/proposalcard.ui
  src/qt/pivx/forms/proposalinfodialog.ui
  src/qt/pivx/forms/receivedialog.ui
  src/qt/pivx/forms/receivewidget.ui
  src/qt/pivx/forms/requestdialog.ui
  src/qt/pivx/forms/send.ui
  src/qt/pivx/forms/sendchangeaddressdialog.ui
  src/qt/pivx/forms/sendconfirmdialog.ui
  src/qt/pivx/forms/sendcustomfeedialog.ui
  src/qt/pivx/forms/sendmemodialog.ui
  src/qt/pivx/forms/sendmultirow.ui
  src/qt/pivx/forms/snackbar.ui
  src/qt/pivx/forms/splash.ui
  src/qt/pivx/forms/tooltipmenu.ui
  src/qt/pivx/forms/topbar.ui
  src/qt/pivx/forms/txrow.ui
  src/qt/pivx/forms/welcomecontentwidget.ui
  src/qt/pivx/requestdialog.cpp
  src/qt/pivx/sendcustomfeedialog.cpp
  src/qt/pivx/settings/forms/settingsbackupwallet.ui
  src/qt/pivx/settings/forms/settingsbittoolwidget.ui
  src/qt/pivx/settings/forms/settingsconsolewidget.ui
  src/qt/pivx/settings/forms/settingsdisplayoptionswidget.ui
  src/qt/pivx/settings/forms/settingsexportcsv.ui
  src/qt/pivx/settings/forms/settingsfaqwidget.ui
  src/qt/pivx/settings/forms/settingsinformationwidget.ui
  src/qt/pivx/settings/forms/settingsmainoptionswidget.ui
  src/qt/pivx/settings/forms/settingssignmessagewidgets.ui
  src/qt/pivx/settings/forms/settingswalletoptionswidget.ui
  src/qt/pivx/settings/forms/settingswalletrepairwidget.ui
  src/qt/pivx/settings/forms/settingswidget.ui
  src/qt/pivx/settings/settingsexportcsv.cpp
Labels: GUI, Cleanup

#2634 [test] fix coinstake input selection on secondary chains.
  src/wallet/test/pos_validations_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Tests

#2638 [QA] Fix intermittent mempool sync failures in sapling_wallet_nullifiers
  test/functional/sapling_wallet_nullifiers.py
Labels: Tests

#2609 [RPC] Shield address setlabel/getaddressesbylabel
  doc/release-notes.md
  src/wallet/rpcwallet.cpp
  test/functional/wallet_labels.py
Labels: RPC

#2586 [Cleanup] Remove fNetworkNode and pnodeLocalHost, and encapsulate CNode id.
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/tiertwo_networksync.cpp
  test/functional/p2p_addr_relay.py
  test/functional/p2p_addrv2_relay.py
  test/functional/p2p_invalid_messages.py
Labels: Upstream, Network

#2579 pivx-cli better error handling + libevent RAII upstream backports
  CMakeLists.txt
  src/Makefile.am
  src/Makefile.test.include
  src/httpserver.cpp
  src/pivx-cli.cpp
  src/support/events.h
  src/test/CMakeLists.txt
  src/test/raii_event_tests.cpp
Labels: Upstream

#2587 [Net] Split resolve out of connect and add addnode parallel outbound connections limit
  doc/release-notes.md
  src/activemasternode.cpp
  src/init.cpp
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/netbase.cpp
  src/netbase.h
  src/rpc/net.cpp
  test/functional/p2p_disconnect_ban.py
Labels: Upstream, Network

#2601 [Wallet] Prefer coins that have fewer ancestors, sanity check txn before ATMP and rebroadcast functional test
  src/txmempool.cpp
  src/txmempool.h
  src/wallet/init.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  test/functional/test_runner.py
  test/functional/wallet_basic.py
  test/functional/wallet_resendwallettransactions.py
Labels: Upstream, Wallet

#2577 [GUI] Include MN Rewards in the dashboard chart
  src/qt/pivx/coldstakingwidget.cpp
  src/qt/pivx/coldstakingwidget.h
  src/qt/pivx/dashboardwidget.cpp
  src/qt/pivx/dashboardwidget.h
  src/qt/pivx/forms/dashboardwidget.ui
  src/qt/pivx/res/css/style_dark.css
  src/qt/pivx/res/css/style_light.css
  src/qt/transactionfilterproxy.cpp
  src/qt/transactionfilterproxy.h
  src/qt/transactionrecord.cpp
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/qt/transactiontablemodel.h
Labels: GUI

#2619 [Test] Add test case for node with a full "ask for" inv set.
  src/masternodeman.cpp
  test/functional/p2p_invalid_messages.py
  test/functional/test_framework/messages.py
Labels: Tests

#2641 [Tests] Add linter for circular dependencies and start fixing them
  contrib/devtools/circular-dependencies.py
  src/chain.h
  src/evo/deterministicmns.cpp
  src/keystore.cpp
  src/masternode.cpp
  src/netmessagemaker.h
  src/primitives/block.cpp
  src/sapling/noteencryption.h
  src/test/test_pivx.cpp
  test/lint/lint-circular-dependencies.sh
Labels: Scripts and Tools, Upstream, Tests, Cleanup

#2564 [GUI] Clean restart process
  src/init.cpp
  src/init.h
  src/qt/pivx.cpp
Labels: GUI, Refactoring, Cleanup, Startup

#2645 [Tiertwo] Clean inactive MNs from the fin count.
  src/budget/finalizedbudget.cpp
  src/budget/finalizedbudget.h
  test/functional/tiertwo_governance_sync_basic.py
Labels: Budget/Proposal System

#2642 scripted-diff: replace boost::optional with Optional<> wrapper
  src/sapling/address.cpp
  src/sapling/address.h
  src/sapling/incrementalmerkletree.cpp
  src/sapling/note.cpp
  src/sapling/note.h
  src/sapling/noteencryption.cpp
  src/sapling/noteencryption.h
  src/sapling/sapling_operation.cpp
  src/sapling/saplingscriptpubkeyman.cpp
  src/sapling/zip32.cpp
  src/sapling/zip32.h
  src/util/system.h
  src/wallet/test/wallet_shielded_balances_tests.cpp
Labels: Refactoring, Cleanup

#2646 [Refactoring] Break circ dependency init -> * -> init by extracting shutdown.h
  CMakeLists.txt
  src/Makefile.am
  src/crypter.cpp
  src/init.cpp
  src/init.h
  src/masternodeman.cpp
  src/pivxd.cpp
  src/qt/coincontroldialog.cpp
  src/qt/guiutil.cpp
  src/qt/optionsmodel.cpp
  src/qt/pivx.cpp
  src/qt/pivx/masternodeswidget.cpp
  src/qt/pivx/pivxgui.cpp
  src/qt/pivx/pivxgui.h
  src/qt/pivx/settings/settingsbittoolwidget.cpp
  src/qt/pivx/splash.cpp
  src/qt/walletmodel.cpp
  src/qt/winshutdownmonitor.cpp
  src/rpc/budget.cpp
  src/rpc/masternode.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/rawtransaction.cpp
  src/rpc/server.cpp
  src/shutdown.cpp
  src/shutdown.h
  src/test/miner_tests.cpp
  src/validation.cpp
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  test/lint/lint-circular-dependencies.sh
Labels: Upstream, Refactoring

#2643 [Refactoring] Remove checkpoints circular dependencies
  src/chainparams.cpp
  src/chainparams.h
  src/checkpoints.cpp
  src/checkpoints.h
  src/test/miner_tests.cpp
  src/validation.cpp
  src/wallet/wallet.cpp
  test/lint/lint-circular-dependencies.sh
Labels: Refactoring, Needs Backport
