Repository PIVX-Project/PIVX, pull requests merged in 2021-06, with the labels that each got.

#2386 [RPC] Support for JSON-RPC named arguments
  doc/release-notes.md
  src/pivx-cli.cpp
  src/rpc/blockchain.cpp
  src/rpc/budget.cpp
  src/rpc/client.cpp
  src/rpc/client.h
  src/rpc/masternode.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/net.cpp
  src/rpc/rawtransaction.cpp
  src/rpc/rpcevo.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  test/functional/rpc_named_arguments.py
  test/functional/test_framework/authproxy.py
  test/functional/test_runner.py
Labels: RPC, Upstream

#2407 [Cleanup] Housekeeping: remove unneeded CLegacyBlockIndex, proof.h/cpp and txdb zc functions
  CMakeLists.txt
  src/Makefile.am
  src/chain.h
  src/rpc/misc.cpp
  src/sapling/proof.cpp
  src/sapling/proof.h
  src/sapling/sapling_transaction.h
  src/txdb.cpp
  src/txdb.h
Labels: Cleanup

#2351 [Wallet] Laggard wallet-related backports from btc 0.15
  CMakeLists.txt
  doc/release-notes.md
  src/Makefile.am
  src/Makefile.test.include
  src/guiinterfaceutil.h
  src/httprpc.cpp
  src/httpserver.cpp
  src/httpserver.h
  src/init.cpp
  src/miner.cpp
  src/miner.h
  src/netaddress.cpp
  src/netaddress.h
  src/pivx-cli.cpp
  src/policy/policy.cpp
  src/policy/policy.h
  src/qt/coincontroldialog.cpp
  src/qt/guiutil.cpp
  src/qt/pivx/sendcustomfeedialog.cpp
  src/qt/rpcexecutor.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/rpc/blockchain.cpp
  src/rpc/client.cpp
  src/rpc/mining.cpp
  src/rpc/net.cpp
  src/rpc/protocol.h
  src/sapling/sapling_operation.cpp
  src/sapling/saplingscriptpubkeyman.cpp
  src/sapling/saplingscriptpubkeyman.h
  src/sapling/transaction_builder.cpp
  src/script/interpreter.cpp
  src/test/transaction_tests.cpp
  src/wallet/db.cpp
  src/wallet/db.h
  src/wallet/fees.cpp
  src/wallet/fees.h
  src/wallet/init.cpp
  src/wallet/init.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  test/functional/rpc_blockchain.py
  test/functional/rpc_fundrawtransaction.py
  test/functional/test_runner.py
  test/functional/wallet_basic.py
  test/functional/wallet_multiwallet.py
Labels: RPC, Refactoring, Upstream, Wallet

#2359 Net code updates [Step 2]
  src/base58.cpp
  src/base58.h
  src/chainparams.cpp
  src/chainparams.h
  src/compressor.cpp
  src/hash.cpp
  src/key.cpp
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/netaddress.cpp
  src/netaddress.h
  src/netbase.cpp
  src/rpc/net.cpp
  src/serialize.h
  src/streams.h
  src/test/net_tests.cpp
  src/test/netbase_tests.cpp
  src/torcontrol.cpp
  src/utilstrencodings.cpp
Labels: Network, Upstream

#2403 [GUI] transaction model, cleanup unused hasZcTxes flag
  src/qt/transactiontablemodel.cpp
  src/qt/transactiontablemodel.h
Labels: Cleanup, GUI

#2400 [Build] [Depends] Unify macOS deploy target
  Makefile.am
  configure.ac
  contrib/macdeploy/README.md
  contrib/macdeploy/fancy.plist
  contrib/macdeploy/macdeployqtplus
  depends/packages/native_mac_alias.mk
  doc/build-osx.md
Labels: Build System, Upstream, macOS

#2341 [Wallet][RPC] Add subtract-fee-from-amount option in Create[Fund]Transaction
  doc/release-notes.md
  src/qt/walletmodel.cpp
  src/rpc/client.cpp
  src/rpc/rawtransaction.cpp
  src/rpc/rpcevo.cpp
  src/sapling/sapling_operation.cpp
  src/sapling/sapling_operation.h
  src/test/librust/sapling_rpc_wallet_tests.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/wallet_sapling_transactions_validations_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  test/functional/rpc_fundrawtransaction.py
  test/functional/sapling_wallet_send.py
  test/functional/test_runner.py
  test/functional/wallet_basic.py
  test/functional/wallet_listtransactions.py
Labels: RPC, Tests, Upstream, Wallet

#2418 [GA] Add native macOS build job
  .github/workflows/build-and-test.yml
  configure.ac
Labels: Build System

#2349 [Validation][RPC] Provider-Update-Service special tx type
  src/evo/deterministicmns.cpp
  src/evo/providertx.cpp
  src/evo/providertx.h
  src/evo/specialtx.cpp
  src/primitives/transaction.h
  src/rpc/rawtransaction.cpp
  src/rpc/rpcevo.cpp
  src/test/evo_deterministicmns_tests.cpp
  src/test/evo_specialtx_tests.cpp
  src/txmempool.cpp
  src/txmempool.h
  src/validation.cpp
  test/functional/tiertwo_deterministicmns.py
  test/functional/tiertwo_reorg_mempool.py
Labels: Masternode, RPC, Tests, Upstream Dash, Validation

#2428 [Consensus] Introduce 5.2 nuparams and use them to guard new P2CS rules
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/upgrades.cpp
  src/script/interpreter.cpp
  src/script/script.cpp
  src/script/script.h
  src/test/script_P2CS_tests.cpp
  src/validation.cpp
Labels: Consensus

#2429 [Backport] 5.2.0 backports
  .github/workflows/build-and-test.yml
  contrib/gitian-keys/keys.txt
  depends/builders/darwin.mk
  depends/packages/qt.mk
  src/budget/budgetmanager.cpp
  src/qt/guiutil.cpp
  src/qt/pivx/dashboardwidget.cpp
  src/qt/pivx/forms/receivewidget.ui
  src/qt/pivx/pivxgui.cpp
  src/qt/pivx/qtutils.cpp
  src/qt/pivx/qtutils.h
  src/qt/pivx/receivewidget.cpp
  src/qt/pivx/receivewidget.h
  src/qt/pivx/res/css/style_dark.css
  src/qt/pivx/res/css/style_light.css
  src/qt/pivx/settings/forms/settingsfaqwidget.ui
  src/qt/pivx/settings/settingsfaqwidget.cpp
  src/qt/pivx/settings/settingsfaqwidget.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: Backport

#2431 [Consensus] Bump active protocol version to 70922
  src/validation.cpp
  src/version.h
  test/functional/test_framework/messages.py
Labels: Consensus, Protocol-Update

#2432 [Backport] Bump active protocol version to 70922
  src/validation.cpp
  src/version.h
  test/functional/test_framework/messages.py
Labels: Backport

#2430 [Backport] 5.2.0 cs backports
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/upgrades.cpp
  src/script/interpreter.cpp
  src/script/interpreter.h
  src/script/script.cpp
  src/script/script.h
  src/test/script_P2CS_tests.cpp
  src/validation.cpp
Labels: Backport

#2433 [Build] Bump gitian descriptor version to 5.2
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win.yml
Labels: Build System

#2435 [Backport] Bump default block version to 10 (no enforcement)
  src/blockassembler.cpp
  src/primitives/block.h
  test/functional/test_framework/messages.py
Labels: Backport

#2437 [Backport] Add tiertwo_governance_reorg functional test
  src/validation.cpp
  test/functional/test_framework/test_framework.py
  test/functional/test_runner.py
  test/functional/tiertwo_governance_reorg.py
Labels: Backport

#2436 [QA] Add tiertwo_governance_reorg functional test
  test/functional/test_runner.py
  test/functional/tiertwo_governance_reorg.py
Labels: Tests

#2427 [Test] Add test coverage for invalid block budget payee script
  src/Makefile.test.include
  src/miner.cpp
  src/net_processing.cpp
  src/rpc/mining.cpp
  src/test/CMakeLists.txt
  src/test/budget_tests.cpp
  src/test/evo_deterministicmns_tests.cpp
  src/test/miner_tests.cpp
  src/test/test_pivx.cpp
  src/test/test_pivx.h
  src/test/util/blocksutil.cpp
  src/test/util/blocksutil.h
  src/test/validation_block_tests.cpp
  src/test/validation_tests.cpp
  src/validation.cpp
  src/validation.h
Labels: Tests

#2441 [Consensus] v5.2 upgrade enforcement height.
  src/chainparams.cpp
Labels: Consensus

#2443 [Backport] v5.2 upgrade enforcement height.
  src/chainparams.cpp
Labels: Backport, Consensus

#2440 [Backport] Align budget payee validity to highest voted budget check.
  src/budget/budgetmanager.cpp
  src/budget/budgetmanager.h
  src/rpc/budget.cpp
  test/functional/test_runner.py
  test/functional/tiertwo_governance_invalid_budget.py
Labels: Backport

#2434 [Refactor] Decouple enforcement of cbase payment from block version
  src/blockassembler.cpp
  src/budget/budgetmanager.cpp
  src/masternode-payments.cpp
  src/masternode-payments.h
  src/primitives/block.h
  src/validation.cpp
  test/functional/test_framework/messages.py
  test/functional/tiertwo_mn_compatibility.py
Labels: Refactoring, Validation

#2338 [Net] Add NAT-PMP port forwarding support
  .github/workflows/build-and-test.yml
  CMakeLists.txt
  build-aux/snap/snapcraft.yaml
  configure.ac
  contrib/cmake/FindNAT-PMP.cmake
  depends/Makefile
  depends/README.md
  depends/config.site.in
  depends/packages/libnatpmp.mk
  depends/packages/packages.mk
  doc/build-osx.md
  doc/build-unix.md
  doc/dependencies.md
  doc/release-notes.md
  doc/tor.md
  src/Makefile.am
  src/Makefile.bench.include
  src/Makefile.qt.include
  src/Makefile.qttest.include
  src/Makefile.test.include
  src/init.cpp
  src/mapport.cpp
  src/mapport.h
  src/net.cpp
  src/net.h
  src/qt/CMakeLists.txt
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/qt/optionsmodel.cpp
  src/qt/optionsmodel.h
  src/qt/pivx/settings/forms/settingswalletoptionswidget.ui
  src/qt/pivx/settings/settingswalletoptionswidget.cpp
  src/qt/pivx/settings/settingswalletoptionswidget.h
  src/qt/pivx/settings/settingswidget.cpp
  src/test/CMakeLists.txt
  test/functional/test_framework/util.py
Labels: Build System, Network, P2P, Upstream

#2402 Fix MN activation when the node received the mnb before initialize the MN.
  src/activemasternode.cpp
  src/activemasternode.h
Labels: Bug, Masternode

#2446 [GUI] Update translations from Transifex for 5.2.0
  .tx/config
  src/Makefile.qt_locale.include
  src/qt/locale/pivx_de.ts
  src/qt/locale/pivx_en.ts
  src/qt/locale/pivx_en_US.ts
  src/qt/locale/pivx_es.ts
  src/qt/locale/pivx_es_ES.ts
  src/qt/locale/pivx_fr_FR.ts
  src/qt/locale/pivx_hr_HR.ts
  src/qt/locale/pivx_it.ts
  src/qt/locale/pivx_nl.ts
  src/qt/locale/pivx_pl.ts
  src/qt/locale/pivx_ru.ts
  src/qt/locale/pivx_tr.ts
  src/qt/locale/pivx_zh_CN.ts
  src/qt/pivx_locale.qrc
Labels: GUI

#2450 [wallet] fix segfault for P2CS inputs in CreateTransaction
  src/wallet/wallet.cpp
Labels: Bug, Wallet

#2451 [Backport] wallet fix segfault for P2CS inputs in CreateTransaction
  src/wallet/wallet.cpp
Labels: Backport, Bug

#2442 [Doc] v5.2.0 Release Notes
  doc/release-notes.md
Labels: Docs and Output

#2391 [Core] Add reindex-chainstate startup option
  doc/release-notes.md
  src/consensus/zerocoin_verify.cpp
  src/init.cpp
  src/qt/optionsmodel.cpp
  src/rpc/blockchain.cpp
  src/txdb.h
  src/validation.cpp
  src/validation.h
  src/wallet/wallet.cpp
  test/functional/feature_reindex.py
  test/functional/test_runner.py
Labels: Startup, UTXO DBs and Indexes, Upstream

#2410 [Test] Add p2p invalid messages functional test (and test framework update)
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  test/functional/example_test.py
  test/functional/feature_block.py
  test/functional/feature_cltv.py
  test/functional/feature_nulldummy.py
  test/functional/mining_pos_coldStaking.py
  test/functional/p2p_feefilter.py
  test/functional/p2p_fingerprint.py
  test/functional/p2p_invalid_block.py
  test/functional/p2p_invalid_messages.py
  test/functional/p2p_invalid_tx.py
  test/functional/p2p_leak.py
  test/functional/p2p_mempool.py
  test/functional/p2p_timeouts.py
  test/functional/p2p_unrequested_blocks.py
  test/functional/test_framework/messages.py
  test/functional/test_framework/mininode.py
  test/functional/test_framework/test_framework.py
  test/functional/test_framework/test_node.py
  test/functional/test_runner.py
Labels: Tests, Upstream

#2397 [GUI] Fix invalid MN collateral amount and align every static 10k PIV strings.
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/qt/pivx/forms/masternodewizarddialog.ui
  src/qt/pivx/masternodeswidget.cpp
  src/qt/pivx/masternodewizarddialog.cpp
  src/qt/pivx/masternodewizarddialog.h
  src/qt/pivx/pivxgui.cpp
  src/qt/pivx/settings/settingsfaqwidget.cpp
  src/qt/pivx/settings/settingsfaqwidget.h
  src/wallet/wallet.cpp
Labels: Bug, GUI

#2461 [Build] Bump master to 5.2.99 and save historical release notes
  build-aux/snap/snapcraft.yaml
  configure.ac
  doc/release-notes/release-notes-5.2.0.md
Labels: Build System, Docs and Output, NoFunctionalChanges, Trivial
