Repository PIVX-Project/PIVX, pull requests merged in 2021-02, with the labels that each got.

#2172 [Net] Improve and document SOCKS code
  src/netbase.cpp
Labels: P2P, Refactoring, Upstream

#2153 [Tests] Don't create dust outputs in small_txpuzzle_randfee
  test/functional/feature_fee_estimation.py
Labels: Bug, Tests

#2167 [Logs] Add new "sporks" debug logging category
  src/logging.cpp
  src/logging.h
  src/spork.cpp
Labels: Docs and Output

#2178 [BUG][GUI] Fix CWalletTx* casts to CTransaction*
  src/qt/walletmodel.cpp
  src/qt/walletmodeltransaction.cpp
Labels: Bug, GUI

#2135 [Masternode] Manage status cleanup
  src/activemasternode.cpp
  src/net.cpp
  src/net.h
Labels: Masternode, Refactoring

#2155 [Miner] Rewrite miner code with proper encapsulation + test coverage
  CMakeLists.txt
  src/Makefile.am
  src/Makefile.test.include
  src/blockassembler.cpp
  src/blockassembler.h
  src/miner.cpp
  src/miner.h
  src/rpc/mining.cpp
  src/test/CMakeLists.txt
  src/test/miner_tests.cpp
  src/validation.h
Labels: Block Generation, Upstream

#2169 [Tests] Introduce TestChainSetup fixture, pre-creating a N-blocks chain
  src/test/test_pivx.cpp
  src/test/test_pivx.h
Labels: Tests

#2157 [RPC] mnbudgetvote generalized, duplicated code cleaned.
  src/rpc/budget.cpp
Labels: Masternode, RPC, Refactoring

#2184 [Refactor] Grouping misbehaving / cs_main lock calls into a single place
  src/budget/budgetmanager.cpp
  src/budget/budgetmanager.h
Labels: P2P, Refactoring

#2161 [GUI] send widget, hide contacts menu when clear event is triggered.
  src/qt/pivx/send.cpp
  src/qt/pivx/send.h
Labels: Bug, GUI

#2162 [Refactoring] Avoid dereference-of-casted-pointer
  src/primitives/transaction.h
  src/rpc/blockchain.cpp
  src/script/interpreter.cpp
  src/script/script.h
  src/test/dbwrapper_tests.cpp
  src/txdb.cpp
  src/wallet/walletdb.cpp
Labels: Refactoring, Upstream

#2174 [GUI] Use wchar_t API explicitly on Windows
  src/qt/guiutil.cpp
  src/util.cpp
Labels: GUI, Upstream, Windows

#2177 [RPC][BUG] Fix getblockindexstats-getfeeinfo with shield txes
  src/rpc/blockchain.cpp
  test/functional/feature_blockindexstats.py
  test/functional/test_runner.py
Labels: Bug, RPC

#2190 [Tests] Fix and enable zmq functional test in the test suite
  test/functional/interface_zmq.py
  test/functional/test_runner.py
Labels: Tests

#2175 [Refactoring] Remove g_IsSapling active flag
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/test/data/sighash.json
  src/test/librust/utiltest.cpp
  src/validation.cpp
  src/wallet/wallet.cpp
Labels: Refactoring

#2164 [Refactor] Several updates to the base chain params structure
  src/budget/budgetmanager.cpp
  src/chainparams.cpp
  src/chainparams.h
  src/chainparamsbase.cpp
  src/chainparamsbase.h
  src/consensus/zerocoin_verify.cpp
  src/dbwrapper.h
  src/init.cpp
  src/masternode-payments.cpp
  src/masternode.cpp
  src/masternodeman.cpp
  src/pivx-cli.cpp
  src/pivx-tx.cpp
  src/pivxd.cpp
  src/qt/bitcoinunits.cpp
  src/qt/paymentserver.cpp
  src/qt/pivx.cpp
  src/qt/walletmodel.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/validation.cpp
  src/zpiv/zerocoin.cpp
  src/zpiv/zerocoin.h
  src/zpivchain.cpp
  src/zpivchain.h
Labels: Cleanup, Refactoring, Upstream

#2176 [Test] Double spend inputs and notes unit tests coverage
  src/Makefile.test.include
  src/blockassembler.cpp
  src/blockassembler.h
  src/test/CMakeLists.txt
  src/test/txvalidationcache_tests.cpp
  src/wallet/test/wallet_sapling_transactions_validations_tests.cpp
Labels: Tests

#2200 [GUI][Trivial] Minor content change for more precise description
  src/qt/pivx/forms/dashboardwidget.ui
Labels: GUI

#2187 [Doc] WSL Depends builds need --disable-online-rust
  doc/build-windows.md
Labels: Docs and Output, NoFunctionalChanges, Trivial

#2198 [GA] Enable CMake macOS Build
  .github/workflows/build-and-test.yml
  CMakeLists.txt
Labels: Build System

#2191 [BugFix] Shutdown, stop threadGroup before dump data to disk.
  src/init.cpp
Labels: Bug

#2179 [Backport] Make CTransaction actually immutable
  src/budget/budgetmanager.cpp
  src/core_io.h
  src/core_read.cpp
  src/masternode.cpp
  src/net_processing.cpp
  src/pivx-tx.cpp
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/rest.cpp
  src/rpc/blockchain.cpp
  src/rpc/rawtransaction.cpp
  src/sapling/sapling_operation.cpp
  src/sapling/sapling_operation.h
  src/script/bitcoinconsensus.cpp
  src/script/sign.h
  src/stakeinput.cpp
  src/test/bloom_tests.cpp
  src/test/coins_tests.cpp
  src/test/librust/sapling_rpc_wallet_tests.cpp
  src/test/script_tests.cpp
  src/test/serialize_tests.cpp
  src/test/sighash_tests.cpp
  src/test/transaction_tests.cpp
  src/validation.cpp
  src/validation.h
Labels: Backport, Refactoring, Security, Upstream

#2197 [Wallet] Close DB on error
  src/wallet/db.cpp
Labels: Upstream, Wallet

#2181 [Refactoring] Sapling classes - initialize fields and pass parameters by reference
  .gitignore
  src/sapling/address.h
  src/sapling/note.cpp
  src/sapling/note.h
  src/sapling/sapling_transaction.h
  src/sapling/saplingscriptpubkeyman.cpp
  src/sapling/transaction_builder.cpp
  src/sapling/transaction_builder.h
  src/wallet/wallet.cpp
Labels: Refactoring, Sapling

#2185 [Backport] Use static_cast instead of C-style casts for non-fundamental types
  src/addrman.h
  src/core_read.cpp
  src/httpserver.cpp
  src/net.cpp
  src/net_processing.cpp
  src/netaddress.cpp
  src/netbase.cpp
  src/primitives/block.h
  src/protocol.h
  src/qt/coincontroldialog.cpp
  src/qt/coincontroltreewidget.cpp
  src/qt/pivx.cpp
  src/qt/pivx/pivxgui.cpp
  src/script/script.h
  src/torcontrol.cpp
  src/txdb.h
  src/wallet/wallet.h
Labels: Refactoring, Upstream

#2182 [GUI][Trivial] Default initialization for scalar and pointer fields
  src/qt/addressbookpage.h
  src/qt/addresstablemodel.cpp
  src/qt/addresstablemodel.h
  src/qt/coincontroldialog.h
  src/qt/notificator.cpp
  src/qt/pivx.cpp
  src/qt/pivx/coldstakingmodel.h
  src/qt/pivx/coldstakingwidget.h
  src/qt/pivx/dashboardwidget.h
  src/qt/pivx/receivewidget.h
  src/qt/pivx/requestdialog.h
  src/qt/pivx/sendmultirow.h
  src/qt/pivx/settings/settingswidget.h
  src/qt/pivx/txviewholder.h
  src/qt/transactionrecord.h
  src/qt/transactiontablemodel.cpp
  src/qt/transactiontablemodel.h
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
Labels: GUI, Trivial

#2194 [Backport] Disable the mempool P2P command when bloom filters disabled
  src/net_processing.cpp
  test/functional/test_runner.py
Labels: Network, Tests, Upstream

#2186 Improving masternode check inputs and add process
  src/masternode.cpp
  src/masternode.h
  src/masternodeman.cpp
Labels: Masternode

#2195 Solve an incorrect MakeTransactionRef usage for ATMP call inside the wallet and unit tests
  src/chain.cpp
  src/test/librust/sapling_rpc_wallet_tests.cpp
  src/test/librust/sapling_wallet_tests.cpp
  src/validation.cpp
  src/wallet/test/wallet_shielded_balances_tests.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Bug, Wallet

#2188 [Core] More efficient rolling Bloom filter
  src/bloom.cpp
  src/bloom.h
  src/net_processing.cpp
Labels: Refactoring, Upstream

#2189 [Bug][Refactoring] Miscellaneous fixes
  src/activemasternode.cpp
  src/blockassembler.cpp
  src/blockassembler.h
  src/budget/budgetmanager.cpp
  src/fs.cpp
  src/fs.h
  src/httpserver.cpp
  src/libzerocoin/CoinSpend.h
  src/logging.cpp
  src/masternodeman.cpp
  src/masternodeman.h
  src/net.h
  src/netaddress.h
  src/policy/fees.cpp
  src/policy/fees.h
  src/qt/guiutil.cpp
  src/qt/paymentserver.cpp
  src/qt/paymentserver.h
  src/qt/pivx/masternodeswidget.cpp
  src/qt/pivx/masternodeswidget.h
  src/qt/pivx/mnmodel.cpp
  src/qt/pivx/receivedialog.h
  src/qt/pivx/send.cpp
  src/qt/pivx/sendmultirow.h
  src/qt/test/paymentservertests.cpp
  src/qt/test/paymentservertests.h
  src/qt/walletmodel.h
  src/random.h
  src/rpc/blockchain.cpp
  src/rpc/server.cpp
  src/rpc/server.h
  src/script/script.cpp
  src/script/script.h
  src/test/miner_tests.cpp
  src/test/multisig_tests.cpp
  src/test/net_tests.cpp
  src/test/pmt_tests.cpp
  src/test/script_tests.cpp
  src/test/serialize_tests.cpp
  src/txmempool.cpp
  src/validation.cpp
  src/validation.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/crypto_tests.cpp
  src/wallet/test/wallet_shielded_balances_tests.cpp
  src/wallet/wallet.cpp
  src/zmq/zmqpublishnotifier.h
  src/zpiv/zpos.h
  test/functional/feature_blockindexstats.py
Labels: Bug, Refactoring, Tests

#2192 Support for validation interface signals in background thread
  src/init.cpp
  src/scheduler.cpp
  src/scheduler.h
  src/test/test_pivx.cpp
  src/test/test_pivx.h
  src/validation.cpp
  src/validation.h
  src/validationinterface.cpp
  src/validationinterface.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/zmq/zmqabstractnotifier.cpp
  src/zmq/zmqabstractnotifier.h
  src/zmq/zmqnotificationinterface.cpp
  src/zmq/zmqnotificationinterface.h
  src/zmq/zmqpublishnotifier.cpp
  src/zmq/zmqpublishnotifier.h
Labels: Upstream, Validation

#2180 [Refactoring] Remove BaseOutPoint::GetHash
  src/budget/budgetproposal.cpp
  src/budget/budgetproposal.h
  src/budget/budgetvote.cpp
  src/budget/finalizedbudget.cpp
  src/budget/finalizedbudget.h
  src/budget/finalizedbudgetvote.cpp
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/rpc/budget.cpp
  test/functional/tiertwo_governance_sync_basic.py
Labels: Budget/Proposal System, Bug, Needs Release Notes, Refactoring

#2201 [Wallet] CTransactionRef migration + CWalletTx/CMerkleTx refactor
  src/blockassembler.cpp
  src/budget/budgetmanager.cpp
  src/consensus/tx_verify.cpp
  src/consensus/tx_verify.h
  src/policy/policy.cpp
  src/policy/policy.h
  src/qt/pivx/masternodewizarddialog.cpp
  src/qt/pivx/send.cpp
  src/qt/pivx/sendconfirmdialog.cpp
  src/qt/pivx/sendconfirmdialog.h
  src/qt/transactionrecord.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/qt/walletmodeltransaction.cpp
  src/qt/walletmodeltransaction.h
  src/rpc/budget.cpp
  src/sapling/sapling_operation.cpp
  src/sapling/sapling_validation.cpp
  src/sapling/saplingscriptpubkeyman.cpp
  src/sapling/saplingscriptpubkeyman.h
  src/test/librust/sapling_rpc_wallet_tests.cpp
  src/test/librust/sapling_wallet_tests.cpp
  src/test/miner_tests.cpp
  src/test/script_P2SH_tests.cpp
  src/test/transaction_tests.cpp
  src/txmempool.cpp
  src/validation.cpp
  src/validation.h
  src/wallet/rpcwallet.cpp
  src/wallet/test/wallet_shielded_balances_tests.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  src/wallet/walletdb.cpp
Labels: Wallet

#2207 Use non-atomic flushing with block replay
  contrib/devtools/check-doc.py
  src/chain.cpp
  src/chain.h
  src/coins.cpp
  src/coins.h
  src/httpserver.cpp
  src/init.cpp
  src/legacy/validation_zerocoin_legacy.cpp
  src/legacy/validation_zerocoin_legacy.h
  src/net_processing.cpp
  src/txdb.cpp
  src/txdb.h
  src/validation.cpp
  src/validation.h
  test/functional/feature_dbcrash.py
  test/functional/test_framework/test_framework.py
  test/functional/test_framework/test_node.py
  test/functional/test_runner.py
  test/functional/wallet_dump.py
Labels: Bug, UTXO DBs and Indexes, Upstream

#2205 [Logging] remove unused return value from LogPrintStr
  src/logging.cpp
  src/logging.h
Labels: Bug, Upstream, Util / log / libs

#2204 [Refactoring] Verify MessageSigner signatures with keyIDs
  src/activemasternode.cpp
  src/budget/budgetmanager.cpp
  src/budget/budgetmanager.h
  src/budget/budgetproposal.cpp
  src/budget/budgetproposal.h
  src/budget/budgetvote.h
  src/budget/finalizedbudget.cpp
  src/budget/finalizedbudget.h
  src/budget/finalizedbudgetvote.h
  src/masternode-payments.cpp
  src/masternode-payments.h
  src/masternode.cpp
  src/masternode.h
  src/messagesigner.cpp
  src/messagesigner.h
  src/qt/pivx/masternodewizarddialog.cpp
  src/rpc/budget.cpp
  src/rpc/masternode.cpp
  src/spork.cpp
  src/spork.h
  src/test/validation_tests.cpp
  src/tiertwo/specialtx_validation.cpp
  src/validation.cpp
  src/validation.h
  src/wallet/wallet.cpp
  test/functional/feature_blockindexstats.py
Labels: Budget/Proposal System, Masternode, Refactoring

#2206 [Test] script standard tests back ported
  src/Makefile.test.include
  src/test/CMakeLists.txt
  src/test/script_standard_tests.cpp
Labels: Backport

#2203 Call wallet/validation notify callbacks in scheduler thread (without cs_main)
  doc/developer-notes.md
  src/blockassembler.cpp
  src/init.cpp
  src/miner.cpp
  src/miner.h
  src/net_processing.cpp
  src/rpc/blockchain.cpp
  src/rpc/mining.cpp
  src/rpc/rawtransaction.cpp
  src/sapling/saplingscriptpubkeyman.cpp
  src/scheduler.cpp
  src/scheduler.h
  src/test/librust/sapling_rpc_wallet_tests.cpp
  src/test/test_pivx.cpp
  src/txmempool.h
  src/validation.cpp
  src/validationinterface.cpp
  src/validationinterface.h
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/wallet_sapling_transactions_validations_tests.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  test/functional/feature_dbcrash.py
  test/functional/mempool_persist.py
  test/functional/sapling_fillblock.py
  test/functional/test_framework/util.py
  test/functional/wallet_dump.py
  test/functional/wallet_labels.py
  test/functional/wallet_upgrade.py
Labels: P2P, Tests, Upstream, Validation, Wallet

#2210 [Refactor] Implement CheckColdStake in TransactionSignatureChecker
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/script/interpreter.cpp
  src/script/interpreter.h
  src/test/script_P2CS_tests.cpp
Labels: Cold Staking, Refactoring, Tests

#2212 [Misc] Init fixes + DisconnectBlock cleanup + zerocoin dead code removal.
  CMakeLists.txt
  src/Makefile.am
  src/init.cpp
  src/legacy/validation_zerocoin_legacy.cpp
  src/legacy/validation_zerocoin_legacy.h
  src/stakeinput.cpp
  src/util.cpp
  src/util.h
  src/validation.cpp
  src/validation.h
  src/wallet/rpcwallet.cpp
  src/wallet/walletdb.cpp
  src/wallet/walletdb.h
  src/zpiv/deterministicmint.cpp
  src/zpiv/deterministicmint.h
Labels: Cleanup, Refactoring

#2219 [GUI] FAQ remove freshdesk and SwiftX mention.
  src/qt/pivx/settings/forms/settingsfaqwidget.ui
Labels: GUI, Trivial

#2211 Qt: Reduce whitespace around qr code fixes #1562
  src/qt/pivx/qtutils.cpp
Labels: Feature Request, GUI

#2213 [Validation] Remove dead zc checks from ATMP
  src/legacy/validation_zerocoin_legacy.cpp
  src/legacy/validation_zerocoin_legacy.h
  src/validation.cpp
Labels: Cleanup, zPiv

#2218 Guarding wallet access from init and print error for unknown MN collaterals
  src/init.cpp
Labels: Startup, Wallet
