Repository PIVX-Project/PIVX, pull requests merged in 2021-08, with the labels that each got.

#2489 [Tests] Require exact match in assert_raises_init_error
  contrib/devtools/clang-format-diff.py
  contrib/devtools/copyright_header.py
  contrib/devtools/symbol-check.py
  src/init.cpp
  test/functional/combine_logs.py
  test/functional/feature_abortnode.py
  test/functional/feature_asmap.py
  test/functional/feature_blocksdir.py
  test/functional/feature_config_args.py
  test/functional/feature_logging.py
  test/functional/feature_notifications.py
  test/functional/feature_proxy.py
  test/functional/feature_reindex.py
  test/functional/feature_uacomment.py
  test/functional/mempool_persist.py
  test/functional/p2p_leak.py
  test/functional/rpc_bind.py
  test/functional/test_framework/messages.py
  test/functional/test_framework/test_framework.py
  test/functional/test_framework/test_node.py
  test/functional/test_runner.py
  test/functional/wallet_multiwallet.py
Labels: Tests, Upstream

#2481 [BUG][GUI] Fix P2CS grouping in coin control
  src/qt/coincontroldialog.cpp
  src/qt/walletmodel.h
Labels: Bug, GUI

#2453 [Refactor] Create generic CallResult and connect it to getNewAddress* functions.
  src/Makefile.am
  src/destination_io.cpp
  src/destination_io.h
  src/key_io.h
  src/operationresult.h
  src/pairresult.h
  src/qt/addresstablemodel.cpp
  src/qt/pivx/masternodewizarddialog.cpp
  src/qt/pivx/receivewidget.cpp
  src/qt/pivx/requestdialog.cpp
  src/qt/pivx/send.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/test/librust/sapling_rpc_wallet_tests.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/wallet_sapling_transactions_validations_tests.cpp
  src/wallet/test/wallet_tests.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Refactoring

#2449 Solve filename and command line encoding issues on Windows
  src/Makefile.test.include
  src/fs.cpp
  src/fs.h
  src/init.cpp
  src/logging.h
  src/masternodeconfig.cpp
  src/netbase.cpp
  src/pivx-cli.cpp
  src/pivxd.cpp
  src/qt/guiutil.cpp
  src/qt/pivx.cpp
  src/qt/pivx/masternodeswidget.cpp
  src/qt/pivx/masternodewizarddialog.cpp
  src/rpc/protocol.cpp
  src/test/CMakeLists.txt
  src/test/fs_tests.cpp
  src/test/util_tests.cpp
  src/util/system.cpp
  src/util/system.h
  src/wallet/db.cpp
  src/wallet/rpcdump.cpp
  test/functional/feature_filelock.py
  test/functional/feature_uacomment.py
  test/functional/test_runner.py
Labels: Windows

#2495 [Core] Update LevelDB to latest upstream
  src/leveldb/db/db_impl.cc
  src/leveldb/db/db_test.cc
  src/leveldb/db/fault_injection_test.cc
  src/leveldb/db/leveldbutil.cc
  src/leveldb/db/log_reader.cc
  src/leveldb/db/log_test.cc
  src/leveldb/db/repair.cc
  src/leveldb/helpers/memenv/memenv.cc
  src/leveldb/include/leveldb/env.h
  src/leveldb/table/format.cc
  src/leveldb/table/table_test.cc
  src/leveldb/util/env_posix.cc
  src/leveldb/util/env_windows.cc
Labels: Upstream

#2497 [Bug] Fix improper locking on Windows WSL1 environments
  src/fs.cpp
Labels: Bug, Upstream, Util / log / libs

#2492 [Consensus] v5.3 network upgrade.
  src/Makefile.test.include
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/upgrades.cpp
  src/masternode-payments.cpp
  src/masternode-payments.h
  src/masternode.cpp
  src/masternode.h
  src/masternodeman.cpp
  src/test/CMakeLists.txt
  src/test/budget_tests.cpp
  src/validation.cpp
  src/wallet/test/pos_test_fixture.cpp
  src/wallet/test/pos_test_fixture.h
  src/wallet/test/pos_validations_tests.cpp
Labels: Tests, Consensus

#2496 [Scripts] Ensure UTF8 encoding for ASCII file operations in python scripts
  contrib/devtools/update-translations.py
  contrib/gitian-build.py
  contrib/linearize/linearize-data.py
  contrib/linearize/linearize-hashes.py
  share/qt/extract_strings_qt.py
  test/functional/combine_logs.py
  test/functional/test_framework/test_framework.py
  test/functional/test_framework/util.py
  test/functional/test_runner.py
  test/functional/tiertwo_masternode_ping.py
  test/functional/wallet_multiwallet.py
  test/lint/check-doc.py
  test/lint/lint-python-utf8-encoding.sh
  test/lint/lint-whitespace.sh
  test/lint/logprint-scanner.py
Labels: Scripts and Tools, Upstream

#2503 [RPC][Net] Add getnodeaddresses RPC command
  doc/release-notes.md
  src/addrman.cpp
  src/addrman.h
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/netaddress.cpp
  src/netaddress.h
  src/rpc/client.cpp
  src/rpc/net.cpp
  src/test/addrman_tests.cpp
  test/functional/rpc_net.py
Labels: RPC, P2P, Upstream, Network

#2506 GUI: bugfix, the command line interface is called "pivx-cli" not "pivx-core".
  src/qt/pivx/settings/settingsfaqwidget.cpp
Labels: Docs and Output, Trivial

#2500 [Doc] Updated documentation related to macOS SDK extraction
  depends/README.md
  doc/gitian-building.md
  doc/gitian-building/gitian-building-mac-os-sdk.md
Labels: Documentation

#2501 [BUG][RPC] Fix listmasternodes and getmasternodewinners
  src/budget/budgetmanager.cpp
  src/budget/budgetmanager.h
  src/init.cpp
  src/masternode-payments.cpp
  src/masternode-payments.h
  src/rpc/masternode.cpp
  src/validation.cpp
  test/functional/tiertwo_governance_sync_basic.py
Labels: RPC, Bug, Masternode

#2505 [Cleanup][Trivial] Remove unused SPORK_5
  src/spork.cpp
  src/sporkid.h
Labels: Cleanup, Trivial

#2507 [Cleanup] Drop unneeded protocol version checks and constants
  src/masternode.cpp
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/protocol.h
  src/version.h
Labels: Refactoring, Cleanup

#2482 [Refactor] Make HexStr take a span
  src/core_write.cpp
  src/evo/providertx.cpp
  src/net_processing.cpp
  src/rest.cpp
  src/rpc/blockchain.cpp
  src/rpc/masternode.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/protocol.cpp
  src/rpc/rawtransaction.cpp
  src/sapling/sapling_core_write.cpp
  src/sapling/saplingscriptpubkeyman.cpp
  src/test/coins_tests.cpp
  src/test/sighash_tests.cpp
  src/test/util_tests.cpp
  src/uint256.cpp
  src/utilstrencodings.cpp
  src/utilstrencodings.h
  src/wallet/db.cpp
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/test/crypto_tests.cpp
Labels: Upstream, Refactoring

#2510 [TierTwo] Enforce MessageVersion::MESS_VER_HASH (mnb/mnp) with 5.3
  src/masternode.cpp
  src/masternodeman.cpp
Labels: Bug, P2P, Masternode

#2508 [BugFix] Correct mnb ser/unser of BIP155 node addresses.
  src/masternode-payments.h
  src/masternode.cpp
  src/masternode.h
  src/masternodeman.cpp
  src/net_processing.cpp
  src/protocol.cpp
  src/protocol.h
  src/version.h
Labels: Bug

#2502 [Net] Add Tor v3 hardcoded seeds
  contrib/seeds/generate-seeds.py
  src/chainparams.cpp
  src/chainparams.h
  src/chainparamsseeds.h
  src/net.cpp
Labels: P2P

#2511 [Refactor][GUI] Clean up mninfodialog
  src/qt/pivx/mninfodialog.cpp
  src/qt/pivx/mninfodialog.h
Labels: GUI, Refactoring

#2516 [GUI][BUG] Console: allow empty arguments
  src/qt/rpcexecutor.cpp
Labels: RPC, GUI, Bug, Upstream

#2513 [GUI] Remove extra jump line in mnb creation error message
  src/masternode.cpp
  src/qt/pivx/masternodeswidget.cpp
Labels: RPC, GUI

#2514 [TierTwo][BugFix] Fix peer banning for not synced tiertwo + GetMNList and inv performance improvements.
  src/masternode-payments.cpp
  src/masternodeman.cpp
  src/masternodeman.h
  src/net_processing.cpp
Labels: Refactoring, Masternode

#2518 [Consensus] Establish v5.3 NU enforcement height for mainnet
  src/blockassembler.cpp
  src/chainparams.cpp
  src/primitives/block.h
  test/functional/test_framework/messages.py
Labels: Consensus

#2519 [RPC] Do not register DMN-related RPC commands
  src/rpc/rpcevo.cpp
Labels: RPC, Masternode

#2520 [Gitian] Set version to 5.3
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-osx.yml
  contrib/gitian-descriptors/gitian-win.yml
Labels: Build System

#2524 [Network] Add mainnet DNS seeder from furszy.
  src/chainparams.cpp
Labels: Network

#2529 [GUI][BugFix] Masternodes screen, fix impossibility to start Masternodes
  src/qt/pivx/masternodeswidget.cpp
  src/qt/pivx/masternodeswidget.h
Labels: GUI, Bug, Needs Backport

#2535 [Build] Bump master to 5.3.99
  build-aux/snap/snapcraft.yaml
  configure.ac
  doc/release-notes/release-notes-5.3.0.md
Labels: Build System, Docs and Output
