Repository PIVX-Project/PIVX, pull requests merged in 2021-10, with the labels that each got.

#2565 [BUG] Consider also DMNs in CountEnabled and CountNetworks
  src/activemasternode.cpp
  src/budget/budgetmanager.cpp
  src/budget/budgetmanager.h
  src/budget/budgetproposal.cpp
  src/evo/deterministicmns.cpp
  src/evo/deterministicmns.h
  src/masternode-sync.cpp
  src/masternodeman.cpp
  src/masternodeman.h
  src/qt/clientmodel.cpp
  src/rpc/masternode.cpp
  src/test/evo_deterministicmns_tests.cpp
  test/functional/tiertwo_deterministicmns.py
  test/functional/tiertwo_mn_compatibility.py
Labels: Bug, Masternode

#2522 [Depends] Use latest config guess/sub
  depends/config.guess
  depends/config.sub
Labels: Build System

#2578 [GUI] dashboard chart, fix last day of the month not being shown.
  src/qt/pivx/dashboardwidget.cpp
Labels: GUI, Bug

#2616 [Tests] Replace usage of tostring() with tobytes()
  test/functional/test_framework/netutil.py
Labels: Upstream, Tests

#2589 [CMake] Further Apple M1 path improvements
  CMakeLists.txt
  src/qt/CMakeLists.txt
Labels: Build System

#2617 [GUI] Force argument insertion when switching languages
  src/qt/pivx/welcomecontentwidget.cpp
Labels: GUI, Bug, Trivial
