Repository PIVX-Project/PIVX, pull requests merged in 2022-01, with the labels that each got.

#2700 lockedpool: avoid sensitive data in core dumps
  src/support/lockedpool.cpp
Labels: Upstream, Util / log / libs

#2697 Kill 'zpivchain' files and, with them, many circular dependencies.
  CMakeLists.txt
  src/Makefile.am
  src/blocksignature.cpp
  src/consensus/zerocoin_verify.cpp
  src/consensus/zerocoin_verify.h
  src/crypter.cpp
  src/init.cpp
  src/kernel.cpp
  src/legacy/validation_zerocoin_legacy.cpp
  src/validation.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/zpiv/zpivmodule.cpp
  src/zpiv/zpivmodule.h
  src/zpiv/zpos.cpp
  src/zpivchain.cpp
  src/zpivchain.h
  test/lint/lint-circular-dependencies.sh
Labels: Refactoring, zPiv

#2705 [GUI][BugFix] Fix missing dashboard chart date filter initialization at startup
  src/qt/pivx/dashboardwidget.cpp
Labels: GUI

#2690 [Refactoring] Decouple and encapsulate tier two synchronization state
  CMakeLists.txt
  src/Makefile.am
  src/activemasternode.cpp
  src/bench/walletprocessblock.cpp
  src/budget/budgetmanager.cpp
  src/budget/finalizedbudget.cpp
  src/init.cpp
  src/masternode-payments.cpp
  src/masternode-sync.cpp
  src/masternode-sync.h
  src/masternode.cpp
  src/masternodeman.cpp
  src/net.cpp
  src/net_processing.cpp
  src/qt/pivx/governancemodel.cpp
  src/qt/pivx/mnmodel.cpp
  src/qt/pivx/topbar.cpp
  src/rpc/budget.cpp
  src/rpc/masternode.cpp
  src/rpc/misc.cpp
  src/test/budget_tests.cpp
  src/test/evo_deterministicmns_tests.cpp
  src/test/mnpayments_tests.cpp
  src/tiertwo/tiertwo_sync_state.cpp
  src/tiertwo/tiertwo_sync_state.h
  src/tiertwo_networksync.cpp
  src/validation.cpp
  test/functional/rpc_budget.py
  test/lint/lint-circular-dependencies.sh
Labels: Refactoring

#2709 [Trivial] Fix LogPrintf arguments in WipeAccChecksums
  src/txdb.cpp
Labels: Trivial

#2710 [Build] Clean up additional coverage and test data
  src/Makefile.am
  src/Makefile.test.include
Labels: Build System

#2699 [Refactor] Deduplicate final commitment validity checks
  src/consensus/params.cpp
  src/consensus/params.h
  src/consensus/validation.h
  src/evo/deterministicmns.cpp
  src/evo/deterministicmns.h
  src/evo/specialtx_validation.cpp
  src/evo/specialtx_validation.h
  src/llmq/quorums_blockprocessor.cpp
  src/llmq/quorums_commitment.cpp
  src/llmq/quorums_commitment.h
  src/llmq/quorums_init.cpp
  src/llmq/quorums_utils.cpp
  src/llmq/quorums_utils.h
  src/test/evo_deterministicmns_tests.cpp
  test/lint/lint-circular-dependencies.sh
Labels: Refactoring, Masternode

#2702 [Core][Build] Fix atomic data races in BLS operations
  build-aux/m4/l_atomic.m4
  src/Makefile.am
  src/bls/bls_worker.cpp
  src/bls/bls_worker.h
  src/ctpl_stl.h
  src/util/threadnames.cpp
Labels: Build System, Bug, Util / log / libs

#2712 [BUG] Fix SPORK-21 check in CMasternodePayments::ProcessBlock
  src/masternode-payments.cpp
  src/masternodeman.cpp
Labels: Bug, Masternode

#2648 [wallet] Reopen CDBEnv after encryption instead of shutting down
  src/qt/askpassphrasedialog.cpp
  src/test/librust/sapling_rpc_wallet_tests.cpp
  src/wallet/db.cpp
  src/wallet/db.h
  src/wallet/rpcwallet.cpp
  src/wallet/test/wallet_test_fixture.cpp
  src/wallet/test/wallet_test_fixture.h
  src/wallet/wallet.cpp
  test/functional/rpc_fundrawtransaction.py
  test/functional/sapling_wallet_nullifiers.py
  test/functional/test_framework/test_node.py
  test/functional/wallet_bumpfee.py
  test/functional/wallet_dump.py
  test/functional/wallet_encryption.py
  test/functional/wallet_keypool.py
Labels: Upstream, Wallet

#2713 [Refactor] differentiate bad-qc-quorum-hash: not-found/not-active-chain
  src/evo/specialtx_validation.cpp
  src/llmq/quorums_blockprocessor.cpp
  src/test/evo_deterministicmns_tests.cpp
  src/test/test_pivx.cpp
  src/test/test_pivx.h
Labels: Refactoring, Masternode

#2716 [GUI] Don't error on zero amount for new cold staking address
  src/qt/pivx/requestdialog.cpp
  src/qt/pivx/requestdialog.h
Labels: GUI, Bug

#2647 [TierTwo] Long Living Masternode Quorums - Part 2, network layer
  CMakeLists.txt
  src/Makefile.am
  src/activemasternode.cpp
  src/activemasternode.h
  src/chainparams.cpp
  src/chainparams.h
  src/evo/evonotificationinterface.cpp
  src/evo/mnauth.cpp
  src/evo/mnauth.h
  src/flatdb.h
  src/init.cpp
  src/llmq/quorums_utils.cpp
  src/llmq/quorums_utils.h
  src/logging.cpp
  src/logging.h
  src/masternode-sync.cpp
  src/masternode-sync.h
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/protocol.cpp
  src/protocol.h
  src/rpc/client.cpp
  src/rpc/misc.cpp
  src/rpc/net.cpp
  src/rpc/rpcevo.cpp
  src/tiertwo/init.cpp
  src/tiertwo/init.h
  src/tiertwo/masternode_meta_manager.cpp
  src/tiertwo/masternode_meta_manager.h
  src/tiertwo/net_masternodes.cpp
  src/tiertwo/net_masternodes.h
  src/version.h
  test/functional/p2p_quorum_connect.py
  test/functional/test_framework/messages.py
  test/functional/test_runner.py
  test/lint/lint-circular-dependencies.sh
Labels: P2P, Network, Masternode

#2715 [Refactor] Add LookupBlockIndex
  src/budget/budgetmanager.cpp
  src/budget/finalizedbudget.cpp
  src/evo/specialtx_validation.cpp
  src/init.cpp
  src/net_processing.cpp
  src/rest.cpp
  src/rpc/blockchain.cpp
  src/rpc/mining.cpp
  src/rpc/rawtransaction.cpp
  src/validation.cpp
  src/validation.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
Labels: Upstream, Refactoring

#2725 [test] Rewrite rpc_wallet_encrypted_wallet_sapzkeys unit test as functional test
  src/test/librust/sapling_rpc_wallet_tests.cpp
  test/functional/sapling_wallet_encryption.py
  test/functional/test_runner.py
Labels: Tests

#2728 Bug: fix missing cs_main lock in AppInitMain and LoadExternalBlockFile
  src/bench/checkblock.cpp
  src/evo/specialtx_validation.cpp
  src/evo/specialtx_validation.h
  src/init.cpp
  src/net_processing.cpp
  src/rest.cpp
  src/rpc/blockchain.cpp
  src/rpc/rawtransaction.cpp
  src/rpc/rpcevo.cpp
  src/test/checkblock_tests.cpp
  src/test/evo_deterministicmns_tests.cpp
  src/test/evo_specialtx_tests.cpp
  src/txdb.cpp
  src/validation.cpp
  src/validation.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Refactoring

#2717 [GUI][Bug] Don't set a proposal's status to PASSING_NOT_FUNDED prematurely
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/qt/pivx/governancemodel.cpp
  src/qt/pivx/governancemodel.h
  src/qt/pivx/proposalcard.cpp
  src/qt/pivx/proposalcard.h
  src/qt/pivx/settings/settingsinformationwidget.cpp
Labels: GUI, Bug, Refactoring

#2731 [Build] Add CMake option to compile with debug flags
  CMakeLists.txt
Labels: Build System

#2704 [Wallet] Crypter code cleanup, updates and styling corrections
  src/crypter.cpp
  src/crypter.h
  src/keystore.cpp
  src/keystore.h
  src/sapling/crypter_sapling.cpp
  src/wallet/wallet.cpp
Labels: Wallet

#2723 Finish moving tier two initialization code from init.cpp to tiertwo/init.cpp and add disabledkg init flag
  src/init.cpp
  src/tiertwo/init.cpp
  src/tiertwo/init.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  test/functional/p2p_quorum_connect.py
  test/lint/lint-circular-dependencies.sh
Labels: Refactoring

#2706 [Net] Implement poll(), fix race condition and enable p2p_timeouts.py test
  src/compat.h
  src/init.cpp
  src/net.cpp
  src/net.h
  src/netbase.cpp
  test/functional/p2p_timeouts.py
  test/functional/test_runner.py
Labels: P2P, Upstream

#2714 [validation] Reject valid qfc older than a certain depth.
  src/chainparams.cpp
  src/consensus/params.h
  src/evo/specialtx_validation.cpp
  src/test/evo_deterministicmns_tests.cpp
Labels: Validation, Masternode

#2727 [trivial] Fixing several QT related circular dependencies
  src/logging.cpp
  src/qt/askpassphrasedialog.cpp
  src/qt/pivx/addresseswidget.cpp
  src/qt/pivx/navmenuwidget.cpp
  src/qt/pivx/tooltipmenu.cpp
  test/lint/lint-circular-dependencies.sh
Labels: Cleanup

#2724 [test] wallet_zapwallettxes.py whitelist peers to speed up tx relay.
  test/functional/wallet_zapwallettxes.py
Labels: Tests

#2721 [GUI] Decouple legacy MNs code from the GUI elements
  src/chainparams.cpp
  src/consensus/params.h
  src/evo/deterministicmns.cpp
  src/masternode.cpp
  src/masternode.h
  src/masternodeman.cpp
  src/qt/clientmodel.cpp
  src/qt/clientmodel.h
  src/qt/pivx/guitransactionsutils.cpp
  src/qt/pivx/guitransactionsutils.h
  src/qt/pivx/masternodeswidget.cpp
  src/qt/pivx/masternodeswidget.h
  src/qt/pivx/masternodewizarddialog.cpp
  src/qt/pivx/masternodewizarddialog.h
  src/qt/pivx/mnmodel.cpp
  src/qt/pivx/mnmodel.h
  src/qt/pivx/pivxgui.cpp
  src/qt/pivx/pivxgui.h
  src/qt/pivx/send.cpp
  src/qt/pivx/settings/settingsfaqwidget.cpp
  src/qt/pivx/settings/settingsfaqwidget.h
  src/wallet/wallet.cpp
Labels: GUI
