Repository PIVX-Project/PIVX, pull requests merged in 2022-09, with the labels that each got.

#2769 [GA] Disable Unit tests for win64 build in GA
  .github/workflows/build-and-test.yml
Labels: Build System, Trivial

#2767 [GA] Run unit/functional tests on native macOS 11
  .github/workflows/build-and-test.yml
  test/functional/wallet_multiwallet.py
Labels: Upstream, Tests

#2766 [Tests] Native secp256k1 for functional tests
  test/functional/feature_block.py
  test/functional/mining_pos_coldStaking.py
  test/functional/mining_pos_fakestake.py
  test/functional/test_framework/key.py
  test/functional/test_framework/messages.py
  test/functional/test_framework/script.py
  test/functional/test_framework/test_framework.py
Labels: Upstream, Tests

#2760 [GUI][BUG] Properly validate proposal creation Name/URL
  src/budget/budgetproposal.cpp
  src/budget/budgetproposal.h
  src/qt/pivx/forms/createproposaldialog.ui
  src/qt/pivx/governancemodel.cpp
  src/utilstrencodings.cpp
  src/utilstrencodings.h
Labels: GUI, Bug

#2763 [Consensus] New block rewards
  src/budget/budgetmanager.cpp
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/upgrades.cpp
  src/masternode-payments.cpp
  src/qt/transactionrecord.cpp
  src/test/budget_tests.cpp
  src/test/evo_deterministicmns_tests.cpp
  src/validation.cpp
  src/validation.h
  src/version.h
  test/functional/test_framework/test_framework.py
  test/functional/tiertwo_dkg_errors.py
Labels: Needs Release Notes, Protocol-Update, Consensus

#2759 [Build][CMake] Use CMake internal instead of custom command for moc
  src/qt/CMakeLists.txt
Labels: Build System

#2768 [GUI] Fix Passing Not Funded logic
  src/qt/clientmodel.cpp
  src/qt/pivx/governancemodel.cpp
  src/qt/pivx/governancewidget.cpp
Labels: GUI, Bug, Trivial

#2771 [GA] Use explicit llvm version for macOS CMake build.
  .github/workflows/build-and-test.yml
Labels: Build System, Trivial

#2770 [Consensus] Set testnet new rewards height
  src/chainparams.cpp
Labels: Consensus, Trivial
