Repository PIVX-Project/PIVX, pull requests merged in 2023-02, with the labels that each got.

#2787 [GA] Update depreciated actions
  .github/workflows/build-and-test.yml
  CMakeLists.txt
Labels: Build System

#2788 [Doc] Don't include dependency paths in Doxygen or Coverage
  Makefile.am
  doc/Doxyfile.in
Labels: Build System, Docs and Output

#2793 [Consensus] Set v5.5.0 superblock checkpoint block hash.
  src/chainparams.cpp
Labels: Consensus, Trivial

#2789 Add Liquid369 gpg key
  contrib/gitian-keys/keys.txt
Labels: Build System
