Repository PIVX-Project/PIVX, pull requests merged in 2023-05, with the labels that each got.

#2857 [GA] Overhaul GA caches
  .github/workflows/build-and-test.yml
  .github/workflows/pr-cache-cleanup.yml
  CMakeLists.txt
Labels: Build System

#2854 [Qt] Don't always clear coin control
  src/qt/pivx/send.cpp
Labels: GUI, Bug

#2852 [GUI] Fix ban actions in peer list
  src/qt/rpcconsole.cpp
Labels: GUI, Bug

#2860 [Bug] Fix toggle lock button
  src/qt/coincontroldialog.cpp
  src/qt/coincontroldialog.h
Labels: GUI, Bug

#2850 Increase performance of Good
  src/addrman.cpp
Labels: P2P, Upstream

#2862 [Qt] CoinControl for masternodes
  src/qt/pivx/forms/masternodeswidget.ui
  src/qt/pivx/masternodeswidget.cpp
  src/qt/pivx/masternodeswidget.h
  src/qt/pivx/mnmodel.cpp
  src/qt/pivx/mnmodel.h
  src/qt/pivx/pivxgui.cpp
Labels: GUI, Masternode

#2824 [P2P] Rate limiting rumored address processing
  src/net.h
  src/net_processing.cpp
  src/net_processing.h
  src/rpc/net.cpp
  test/functional/p2p_addr_relay.py
  test/functional/p2p_addrv2_relay.py
  test/functional/p2p_invalid_messages.py
  test/functional/test_runner.py
Labels: Bug, P2P

#2849 Do not fully sort all nodes for addr relay
  src/net_processing.cpp
Labels: P2P, Upstream

#2868 Add header files
  src/support/lockedpool.h
  src/sync.h
  src/util/string.h
Labels: Trivial

#2844 [TierTwo] ChainLocks (Dip 8)
  CMakeLists.txt
  src/Makefile.am
  src/chainparams.cpp
  src/consensus/params.h
  src/evo/evonotificationinterface.cpp
  src/evo/evonotificationinterface.h
  src/init.cpp
  src/llmq/quorums.cpp
  src/llmq/quorums.h
  src/llmq/quorums_chainlocks.cpp
  src/llmq/quorums_chainlocks.h
  src/llmq/quorums_init.cpp
  src/llmq/quorums_init.h
  src/llmq/quorums_signing.cpp
  src/llmq/quorums_signing.h
  src/net_processing.cpp
  src/protocol.cpp
  src/protocol.h
  src/rpc/blockchain.cpp
  src/rpc/rawtransaction.cpp
  src/spork.cpp
  src/sporkid.h
  src/test/test_pivx.cpp
  src/tiertwo/init.cpp
  src/tiertwo/init.h
  src/tiertwo_networksync.cpp
  src/validation.cpp
  src/validation.h
  src/validationinterface.cpp
  src/validationinterface.h
  test/functional/test_framework/test_framework.py
  test/functional/test_runner.py
  test/functional/tiertwo_chainlocks.py
  test/lint/lint-circular-dependencies.sh
Labels: Masternode, Upstream Dash

#2861 [Wallet] Locked sapling notes
  src/qt/coincontroldialog.cpp
  src/qt/pivx/mnmodel.cpp
  src/qt/pivx/send.cpp
  src/qt/pivx/topbar.cpp
  src/qt/walletmodel.cpp
  src/qt/walletmodel.h
  src/rpc/client.cpp
  src/sapling/saplingscriptpubkeyman.cpp
  src/sapling/saplingscriptpubkeyman.h
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  src/wallet/wallet.h
  test/functional/mining_pos_coldStaking.py
  test/functional/rpc_fundrawtransaction.py
  test/functional/sapling_wallet_send.py
  test/functional/test_framework/test_framework.py
  test/functional/test_framework/util.py
  test/functional/tiertwo_deterministicmns.py
  test/functional/tiertwo_reorg_mempool.py
  test/functional/wallet_basic.py
Labels: RPC, Wallet, Needs Release Notes, Sapling
