Repository PIVX-Project/PIVX, pull requests merged in 2023-04, with the labels that each got.

#2827 [Tools] Fix case typo in .clang-format
  src/.clang-format
Labels: Scripts and Tools, Bug

#2822 [Tests] Replace hashlib.ripemd160 with native implementation
  test/functional/test_framework/ripemd160.py
  test/functional/test_framework/script.py
Labels: Upstream, Tests

#2829 [GUI] Fix bug in proposal creation
  src/qt/pivx/governancemodel.cpp
Labels: GUI, Bug

#2832 [Tests] Run tiertwo and sapling functional tests by default
  test/functional/test_runner.py
Labels: Tests, Trivial

#2819 [Core] Solve BLS Memleak
  src/bls/bls_worker.cpp
Labels: Resource usage, Upstream Dash

#2839 [Build] Minor fixups and simplifications for macdeploy
  contrib/macdeploy/macdeployqtplus
Labels: Build System, macOS, Upstream

#2823 [TierTwo] Signing Request (DIP 7)
  CMakeLists.txt
  src/Makefile.am
  src/bls/bls_batchverifier.h
  src/llmq/quorums.cpp
  src/llmq/quorums_blockprocessor.cpp
  src/llmq/quorums_debug.cpp
  src/llmq/quorums_debug.h
  src/llmq/quorums_init.cpp
  src/llmq/quorums_init.h
  src/llmq/quorums_signing.cpp
  src/llmq/quorums_signing.h
  src/llmq/quorums_signing_shares.cpp
  src/llmq/quorums_signing_shares.h
  src/llmq/quorums_utils.cpp
  src/llmq/quorums_utils.h
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/net_processing.h
  src/protocol.cpp
  src/protocol.h
  src/rpc/client.cpp
  src/rpc/rpcquorums.cpp
  src/serialize.h
  src/test/test_pivx.cpp
  src/tiertwo/init.cpp
  src/tiertwo/net_masternodes.cpp
  src/tiertwo/net_masternodes.h
  src/tiertwo_networksync.cpp
  test/functional/test_framework/test_framework.py
  test/functional/test_runner.py
  test/functional/tiertwo_signing_session.py
  test/lint/lint-circular-dependencies.sh
Labels: Masternode, Upstream Dash

#2825 [GA] Reorganize and optimize GA runner flow
  .github/workflows/build-and-test.yml
Labels: Build System

#2841 [Core] Remove unused PoW block signing code
  src/blocksignature.cpp
Labels: Refactoring, NoFunctionalChanges, Cleanup

#2833 [RPC] Cleanup startmasternode command
  src/rpc/client.cpp
  src/rpc/masternode.cpp
  test/functional/test_framework/test_framework.py
  test/functional/tiertwo_governance_reorg.py
  test/functional/tiertwo_masternode_ping.py
Labels: RPC, Needs Release Notes, Cleanup

#2845 [Core] Unify binary exit codes
  src/bench/bench_pivx.cpp
  src/pivx-cli.cpp
  src/pivx-tx.cpp
  src/pivxd.cpp
  src/qt/pivx.cpp
  test/functional/feature_help.py
Labels: Upstream, Refactoring

#2847 [zmq] Call va_end() on va_start()ed args.
  src/zmq/zmqpublishnotifier.cpp
Labels: Upstream, ZMQ

#2840 [Tests] Add further RPC test coverage for cold staking
  test/functional/mining_pos_coldStaking.py
Labels: Tests

#2842 [GUI] Show memo in self s->s txs
  src/qt/transactionrecord.cpp
Labels: Bug

#2848 [Misc] Cleanup whitespace and guard RPC tables from clang-format
  src/rpc/blockchain.cpp
  src/rpc/budget.cpp
  src/rpc/client.cpp
  src/rpc/masternode.cpp
  src/rpc/mining.cpp
  src/rpc/misc.cpp
  src/rpc/net.cpp
  src/rpc/rawtransaction.cpp
  src/rpc/rpcevo.cpp
  src/rpc/rpcquorums.cpp
  src/wallet/rpcwallet.cpp
Labels: Scripts and Tools, NoFunctionalChanges, Trivial

#2851 [Net] Add Liquid DNS Seeder for mainnet
  src/chainparams.cpp
Labels: Network, Trivial

#2846 [Doc] Remove bitness from pivx-qt help message and manpage
  src/qt/utilitydialog.cpp
Labels: Upstream, Docs and Output

#2798 [Qt] Adds copy button to proposal recipient address
  src/qt/pivx/forms/proposalinfodialog.ui
  src/qt/pivx/proposalinfodialog.cpp
Labels: GUI

#2828 [GUI] Proposal Generate Address
  src/qt/pivx/createproposaldialog.cpp
  src/qt/pivx/createproposaldialog.h
  src/qt/pivx/forms/createproposaldialog.ui
Labels: GUI
