Repository PIVX-Project/PIVX, pull requests merged in 2023-08, with the labels that each got.

#2874 [GUI] Periodic make translate
  src/qt/locale/pivx_en.ts
  src/qt/pivxstrings.cpp
Labels: GUI

#2873 [RPC][MN] Serialize in ADDRV2 for TorV3 in RPC's
  src/rpc/masternode.cpp
Labels: RPC

#2870 Update librustzcash
  .cargo/config.offline
  Cargo.lock
  Cargo.toml
  src/rust/src/rustzcash.rs
  src/rust/src/tests/key_agreement.rs
  src/rust/src/tests/key_components.rs
  src/rust/src/tests/mod.rs
  src/rust/src/tests/notes.rs
  src/rust/src/tests/signatures.rs
Labels: Util / log / libs
