Repository PIVX-Project/PIVX, pull requests merged in 2024-04, with the labels that each got.

#2916 [Test] speed un tiertwo_governance_sync_basic
  test/functional/test_framework/test_framework.py
  test/functional/tiertwo_governance_sync_basic.py
Labels: Tests

#2920 [Http] [Test] Fix test failures on shutdown
  src/httpserver.cpp
  src/init.cpp
  src/rpc/client.cpp
  src/rpc/server.cpp
  test/functional/feature_shutdown.py
  test/functional/test_framework/test_framework.py
  test/functional/test_framework/test_node.py
  test/functional/test_runner.py
Labels: Backport, Tests

#2922 [GA] Bump native macOS runner versions
  .github/workflows/build-and-test.yml
  CMakeLists.txt
  configure.ac
  src/Makefile.am
  src/Makefile.test.include
Labels: Build System

#2923 [Bug] Fix wallet data race
  src/net_processing.cpp
  src/validation.h
  src/wallet/wallet.cpp
  src/wallet/wallet.h
Labels: Bug

#2918 [Build] Update m4 macros from upstream
  build-aux/m4/ax_boost_base.m4
  build-aux/m4/ax_boost_chrono.m4
  build-aux/m4/ax_boost_filesystem.m4
  build-aux/m4/ax_boost_system.m4
  build-aux/m4/ax_boost_thread.m4
  build-aux/m4/ax_boost_unit_test_framework.m4
  build-aux/m4/ax_check_compile_flag.m4
  build-aux/m4/ax_check_link_flag.m4
  build-aux/m4/ax_check_preproc_flag.m4
  build-aux/m4/ax_cxx_compile_stdcxx.m4
  build-aux/m4/ax_gcc_func_attribute.m4
  build-aux/m4/ax_pthread.m4
Labels: Build System, Trivial

#2924 [Bug] Fix validation interface data race
  src/miner.cpp
  src/rpc/mining.cpp
  src/test/miner_tests.cpp
  src/test/mnpayments_tests.cpp
  src/test/util/blocksutil.cpp
  src/test/validation_block_tests.cpp
  src/test/validation_tests.cpp
  src/util/blockstatecatcher.h
  src/validation.cpp
  src/validationinterface.cpp
  src/validationinterface.h
  src/wallet/test/pos_validations_tests.cpp
Labels: Bug

#2925 [BUG] Fix more thread issues
  src/llmq/quorums_signing_shares.cpp
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/tiertwo/net_masternodes.cpp
  test/lint/lint-circular-dependencies.sh
Labels: Bug
