Repository PIVX-Project/PIVX, pull requests merged in 2024-02, with the labels that each got.

#2893 [GUI] Remove unused addressbookpage references
  src/Makefile.qt.include
  src/qt/CMakeLists.txt
  src/qt/addressbookpage.cpp
  src/qt/addressbookpage.h
  src/qt/locale/pivx_en.ts
  src/qt/pivx/settings/settingssignmessagewidgets.cpp
  src/qt/pivx/settings/settingssignmessagewidgets.h
  src/qt/pivxstrings.cpp
Labels: GUI, NoFunctionalChanges, Cleanup, Trivial

#2894 [Doc] Update Ubuntu ppa source for db4.8
  doc/build-unix.md
Labels: Docs and Output, NoFunctionalChanges, Trivial

#2897 [GA] Update actions to node20 versions
  .github/workflows/build-and-test.yml
  .github/workflows/pr-cache-cleanup.yml
Labels: Build System, NoFunctionalChanges, Trivial

#2898 [Doc] Update gpg keyserver URL
  contrib/gitian-keys/README.md
  contrib/gitian-keys/keys.txt
Labels: Docs and Output, NoFunctionalChanges, Trivial

#2901 [Build] Add duddino GPG key
  contrib/gitian-keys/keys.txt
Labels: Build System

#2896 [Build] Further security and symbol checking updates
  .github/workflows/build-and-test.yml
  Makefile.am
  configure.ac
  contrib/devtools/pixie.py
  contrib/devtools/security-check.py
  contrib/devtools/symbol-check.py
  contrib/devtools/test-security-check.py
  src/Makefile.am
  src/pivx-cli.cpp
Labels: Build System

#2903 [GA] Link Boost 1.76 regardless of pre-existing version
  .github/workflows/build-and-test.yml
Labels: Build System, Trivial

#2895 [Core][GUI][RPC] Exchange Address
  doc/release-notes/release-notes-5.6.0.md
  src/addressbook.cpp
  src/addressbook.h
  src/blocksignature.cpp
  src/chainparams.cpp
  src/chainparams.h
  src/consensus/params.h
  src/consensus/tx_verify.cpp
  src/consensus/upgrades.cpp
  src/destination_io.cpp
  src/destination_io.h
  src/key_io.cpp
  src/key_io.h
  src/keystore.h
  src/primitives/transaction.cpp
  src/primitives/transaction.h
  src/pubkey.h
  src/qt/addresstablemodel.cpp
  src/qt/pivx/addresseswidget.cpp
  src/qt/pivx/send.cpp
  src/qt/pivx/sendchangeaddressdialog.cpp
  src/qt/pivx/sendconfirmdialog.cpp
  src/qt/walletmodel.cpp
  src/rpc/misc.cpp
  src/rpc/rpcevo.cpp
  src/sapling/sapling_validation.cpp
  src/script/interpreter.cpp
  src/script/ismine.cpp
  src/script/script.cpp
  src/script/script.h
  src/script/script_error.cpp
  src/script/script_error.h
  src/script/sign.cpp
  src/script/standard.cpp
  src/script/standard.h
  src/test/base58_tests.cpp
  src/test/data/script_tests.json
  src/test/script_standard_tests.cpp
  src/wallet/rpcdump.cpp
  src/wallet/rpcwallet.cpp
  src/wallet/wallet.cpp
  test/functional/feature_exchangeaddr.py
  test/functional/test_framework/script.py
  test/functional/test_runner.py
Labels: RPC, GUI

#2899 [Build] Update copyright year to 2024
  configure.ac
Labels: Build System, Trivial

#2900 [Core] Bump Protocol Version to 70927
  src/validation.cpp
  src/version.h
  test/functional/test_framework/messages.py
Labels: Protocol-Update

#2904 Fix unititialized booleans
  src/qt/pivx/addresseswidget.cpp
  src/qt/pivx/send.cpp
  src/qt/pivx/sendchangeaddressdialog.cpp
  src/qt/walletmodel.cpp
Labels: GUI, Bug

#2905 Restore Mainnet 'EXM' Prefix
  src/chainparams.cpp
Labels: High Priority, Wallet

#2906 Fix optional memo not being checked
  src/qt/transactionrecord.cpp
Labels: High Priority, GUI
