Repository PIVX-Project/PIVX, pull requests merged in 2024-11, with the labels that each got.

#2941 More Dash llmq backports
  src/llmq/quorums_chainlocks.cpp
  src/llmq/quorums_init.cpp
  src/llmq/quorums_signing.cpp
  src/llmq/quorums_signing.h
  src/llmq/quorums_signing_shares.cpp
  src/llmq/quorums_signing_shares.h
  src/protocol.cpp
  src/protocol.h
  src/tiertwo_networksync.cpp
Labels: Masternode, Upstream Dash

#2942 [GA] Bump standard macOS runners to macos-13
  .github/workflows/build-and-test.yml
Labels: High Priority, Build System, NoFunctionalChanges, Trivial

#2946 Dash LLMQ backports
  src/llmq/quorums.cpp
  src/llmq/quorums_chainlocks.cpp
  src/llmq/quorums_chainlocks.h
  src/llmq/quorums_dkgsession.h
  src/llmq/quorums_dkgsessionhandler.cpp
  src/llmq/quorums_dkgsessionhandler.h
  src/llmq/quorums_dkgsessionmgr.cpp
  src/llmq/quorums_dkgsessionmgr.h
  src/llmq/quorums_init.cpp
  src/llmq/quorums_init.h
  src/llmq/quorums_signing.cpp
  src/llmq/quorums_signing.h
  src/llmq/quorums_signing_shares.cpp
  src/llmq/quorums_signing_shares.h
  src/logging.cpp
  src/logging.h
  src/net.cpp
  src/net.h
  test/functional/tiertwo_chainlocks.py
  test/functional/tiertwo_signing_session.py
Labels: Upstream Dash

#2944 [CMake] Fix typo in FindMiniupnp.cmake
  contrib/cmake/FindMiniupnp.cmake
Labels: Build System, NoFunctionalChanges, Trivial

#2949 Dash LLMQ backports part 4
  src/chainparams.cpp
  src/consensus/params.h
  src/evo/evonotificationinterface.cpp
  src/llmq/quorums.cpp
  src/llmq/quorums_chainlocks.cpp
  src/llmq/quorums_chainlocks.h
  src/llmq/quorums_init.h
  src/llmq/quorums_signing.cpp
  src/llmq/quorums_signing.h
  src/llmq/quorums_signing_shares.cpp
  src/llmq/quorums_signing_shares.h
  src/net.cpp
  src/net.h
Labels: Upstream Dash

#2948 [Tests] Actually wait for nodes to connect
  test/functional/example_test.py
  test/functional/feature_abortnode.py
  test/functional/feature_fee_estimation.py
  test/functional/feature_minchainwork.py
  test/functional/feature_notifications.py
  test/functional/interface_rest.py
  test/functional/mining_pos_reorg.py
  test/functional/p2p_disconnect_ban.py
  test/functional/p2p_quorum_connect.py
  test/functional/p2p_sendheaders.py
  test/functional/p2p_time_offset.py
  test/functional/p2p_unrequested_blocks.py
  test/functional/rpc_invalidateblock.py
  test/functional/rpc_net.py
  test/functional/rpc_rawtransaction.py
  test/functional/sapling_wallet.py
  test/functional/sapling_wallet_anchorfork.py
  test/functional/test_framework/test_framework.py
  test/functional/test_framework/test_node.py
  test/functional/test_framework/util.py
  test/functional/tiertwo_chainlocks.py
  test/functional/tiertwo_deterministicmns.py
  test/functional/tiertwo_governance_reorg.py
  test/functional/tiertwo_governance_sync_basic.py
  test/functional/tiertwo_masternode_activation.py
  test/functional/tiertwo_mn_compatibility.py
  test/functional/tiertwo_reorg_mempool.py
  test/functional/wallet_abandonconflict.py
  test/functional/wallet_backup.py
  test/functional/wallet_basic.py
  test/functional/wallet_hd.py
  test/functional/wallet_import_rescan.py
  test/functional/wallet_keypool_topup.py
  test/functional/wallet_listsinceblock.py
  test/functional/wallet_reorgsrestore.py
  test/functional/wallet_txn_clone.py
  test/functional/wallet_txn_doublespend.py
Labels: Tests
