Repository PIVX-Project/PIVX, pull requests merged in 2025-01, with the labels that each got.

#2951 Dash LLMQ backports part 5
  src/llmq/quorums.cpp
  src/llmq/quorums.h
  src/llmq/quorums_chainlocks.cpp
  src/llmq/quorums_chainlocks.h
  src/llmq/quorums_connections.cpp
  src/llmq/quorums_signing.cpp
  src/llmq/quorums_signing.h
  src/llmq/quorums_signing_shares.cpp
  src/llmq/quorums_signing_shares.h
  src/net.cpp
  src/net.h
  src/net_processing.cpp
  src/protocol.cpp
  src/protocol.h
  src/rpc/blockchain.cpp
  src/rpc/rpcquorums.cpp
  src/tiertwo_networksync.cpp
  src/version.h
  test/functional/tiertwo_signing_session.py
Labels: Upstream Dash

#2955 [Depends] Update Boost source URL
  depends/packages/boost.mk
Labels: Build System, Trivial

#2945 [Build] Update .gitignore
  .gitignore
Labels: Build System, NoFunctionalChanges, Trivial

#2957 [Refactor] Remove 'settings' prefix from GUI settings file names
  src/Makefile.qt.include
  src/qt/CMakeLists.txt
  src/qt/pivx/pivxgui.h
  src/qt/pivx/settings/backupwallet.cpp
  src/qt/pivx/settings/backupwallet.h
  src/qt/pivx/settings/bittoolwidget.cpp
  src/qt/pivx/settings/bittoolwidget.h
  src/qt/pivx/settings/consolewidget.cpp
  src/qt/pivx/settings/consolewidget.h
  src/qt/pivx/settings/displayoptionswidget.cpp
  src/qt/pivx/settings/displayoptionswidget.h
  src/qt/pivx/settings/exportcsv.cpp
  src/qt/pivx/settings/exportcsv.h
  src/qt/pivx/settings/faqwidget.cpp
  src/qt/pivx/settings/faqwidget.h
  src/qt/pivx/settings/forms/backupwallet.ui
  src/qt/pivx/settings/forms/bittoolwidget.ui
  src/qt/pivx/settings/forms/consolewidget.ui
  src/qt/pivx/settings/forms/displayoptionswidget.ui
  src/qt/pivx/settings/forms/exportcsv.ui
  src/qt/pivx/settings/forms/faqwidget.ui
  src/qt/pivx/settings/forms/informationwidget.ui
  src/qt/pivx/settings/forms/mainoptionswidget.ui
  src/qt/pivx/settings/forms/signmessagewidgets.ui
  src/qt/pivx/settings/forms/walletoptionswidget.ui
  src/qt/pivx/settings/forms/walletrepairwidget.ui
  src/qt/pivx/settings/informationwidget.cpp
  src/qt/pivx/settings/informationwidget.h
  src/qt/pivx/settings/mainoptionswidget.cpp
  src/qt/pivx/settings/mainoptionswidget.h
  src/qt/pivx/settings/networkwidget.cpp
  src/qt/pivx/settings/networkwidget.h
  src/qt/pivx/settings/settingswidget.h
  src/qt/pivx/settings/signmessagewidgets.cpp
  src/qt/pivx/settings/signmessagewidgets.h
  src/qt/pivx/settings/walletoptionswidget.cpp
  src/qt/pivx/settings/walletoptionswidget.h
  src/qt/pivx/settings/walletrepairwidget.cpp
  src/qt/pivx/settings/walletrepairwidget.h
Labels: Refactoring, NoFunctionalChanges, Cleanup
